//! Build-time offsets for the TypeScript views, evaluated in the WASM artifact.
use crate::manifold_abi::*;
#[export_name = "contactRecordOffset"]
pub extern "C" fn offset(index: usize) -> usize {
    [
        DIR_STRIDE,
        DIR_MANIFOLD_COUNT,
        DIR_MANIFOLD_BASE,
        DIR_FLAGS,
        DIR_FRICTION,
        DIR_RESTITUTION,
        DIR_ROLLING_RESISTANCE,
        DIR_TANGENT_VELOCITY,
        MANIFOLD_STRIDE,
        M_NORMAL,
        M_TWIST,
        M_FRICTION,
        M_ROLLING,
        M_POINT_COUNT,
        M_POINTS,
        POOL_POINT_STRIDE,
        P_ANCHOR_A,
        P_ANCHOR_B,
        P_SEPARATION,
        P_BASE_SEPARATION,
        P_NORMAL_IMPULSE,
        P_TOTAL_NORMAL_IMPULSE,
        P_NORMAL_VELOCITY,
        P_FEATURE_ID,
        P_TRIANGLE_INDEX,
        P_PERSISTED,
        DIR_FLAGS,
        DIR_MANIFOLD_COUNT,
        DIR_INDEX_A,
        DIR_INDEX_B,
        DIR_SET_INDEX,
        DIR_COLOR_INDEX,
        DIR_LOCAL_INDEX,
        DIR_EDGE_A,
        DIR_EDGE_A + 1,
        DIR_EDGE_A + 2,
        DIR_EDGE_B,
        DIR_EDGE_B + 1,
        DIR_EDGE_B + 2,
        DIR_SHAPE_A,
        DIR_SHAPE_B,
        DIR_CHILD_INDEX,
        DIR_ISLAND_ID,
        DIR_ISLAND_INDEX,
        DIR_CONTACT_ID,
        DIR_GENERATION,
    ][index]
}
