import { describe, test, expect } from "bun:test";
import {
    satHullHull,
    satHullBox,
    satHullSphere,
    satHullCapsule,
    boxToHull,
    type SatBody,
} from "../src/standard/physics/sat";
import type { ConvexHull, ConvexHullFace } from "../src/standard/physics/hull";
import goldVectors from "./sat-gold-vectors.json";

function body(
    pos: number[],
    quat: number[] = [0, 0, 0, 1],
    halfExtents: number[] = [0.5, 0.5, 0.5],
): SatBody {
    return {
        pos: new Float32Array(pos),
        quat: new Float32Array(quat),
        halfExtents: new Float32Array(halfExtents),
    };
}

const CUBE_HULL = boxToHull(new Float32Array([0.5, 0.5, 0.5]));

function tetHull(): ConvexHull {
    const s = 0.5;
    const vertices = new Float32Array([s, s, s, s, -s, -s, -s, s, -s, -s, -s, s]);
    const tris: [number, number, number][] = [
        [0, 1, 2],
        [0, 3, 1],
        [0, 2, 3],
        [1, 3, 2],
    ];
    const faces: ConvexHullFace[] = tris.map(([a, b, c]) => {
        const ax = vertices[a * 3],
            ay = vertices[a * 3 + 1],
            az = vertices[a * 3 + 2];
        const bx = vertices[b * 3] - ax,
            by = vertices[b * 3 + 1] - ay,
            bz = vertices[b * 3 + 2] - az;
        const cx = vertices[c * 3] - ax,
            cy = vertices[c * 3 + 1] - ay,
            cz = vertices[c * 3 + 2] - az;
        let nx = by * cz - bz * cy,
            ny = bz * cx - bx * cz,
            nz = bx * cy - by * cx;
        const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
        nx /= len;
        ny /= len;
        nz /= len;
        const d = -(nx * ax + ny * ay + nz * az);
        return {
            plane: new Float32Array([nx, ny, nz, d]),
            vertexIndices: new Uint32Array([a, b, c]),
        };
    });
    const edgePairs: [number, number][] = [
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 2],
        [1, 3],
        [2, 3],
    ];
    const edgeDirs: number[] = [];
    for (const [i, j] of edgePairs) {
        let dx = vertices[j * 3] - vertices[i * 3];
        let dy = vertices[j * 3 + 1] - vertices[i * 3 + 1];
        let dz = vertices[j * 3 + 2] - vertices[i * 3 + 2];
        const len = Math.sqrt(dx * dx + dy * dy + dz * dz);
        dx /= len;
        dy /= len;
        dz /= len;
        if (
            dx < -1e-8 ||
            (Math.abs(dx) < 1e-8 && dy < -1e-8) ||
            (Math.abs(dx) < 1e-8 && Math.abs(dy) < 1e-8 && dz < 0)
        ) {
            dx = -dx;
            dy = -dy;
            dz = -dz;
        }
        edgeDirs.push(dx, dy, dz);
    }
    return {
        vertices,
        numVertices: 4,
        faces,
        numFaces: 4,
        uniqueEdges: new Float32Array(edgeDirs),
        numUniqueEdges: 6,
        localCenter: new Float32Array(3),
        extents: new Float32Array([s, s, s]),
    };
}

// ── Bullet3 gold vector validation ─────────────────────────────────
// Each scenario was generated by Bullet3's b3FindSeparatingAxis +
// b3ClipHullAgainstHull + b3ReduceContacts (proven, battle-tested).
// Our SAT must produce matching results within float tolerance.

function hullForGold(name: string): [ConvexHull, ConvexHull] {
    if (name.startsWith("cube-cube")) return [CUBE_HULL, CUBE_HULL];
    if (name === "tet-cube-overlap") return [tetHull(), CUBE_HULL];
    if (name.startsWith("tet-tet")) return [tetHull(), tetHull()];
    throw new Error(`unknown hull config: ${name}`);
}

// Bullet3 uses normal pointing from B→A (negative of our A→B convention)
// and contact points are on body B's surface. We compare structurally:
// - separated vs not
// - contact count
// - depth values (sign-agnostic magnitude comparison)
// - normal axis alignment

describe("bullet3 gold vectors", () => {
    for (const gv of goldVectors) {
        // Skip cone scenarios (not yet in our hull builder)
        if (gv.name.includes("cone")) continue;

        test(gv.name, () => {
            const [hullA, hullB] = hullForGold(gv.name);
            const a = body(gv.posA, gv.quatA);
            const b = body(gv.posB, gv.quatB);
            const result = satHullHull(a, hullA, b, hullB);

            if (gv.separated) {
                expect(result.length).toBe(0);
                return;
            }

            expect(result.length).toBeGreaterThan(0);

            // Contact count should match Bullet3
            expect(result.length).toBe(gv.numReducedContacts as number);

            // Separating normal should be parallel (same or opposite direction)
            const goldN = gv.separatingNormal!;
            const ourN = result[0].normal;
            const nDot = Math.abs(ourN[0] * goldN[0] + ourN[1] * goldN[1] + ourN[2] * goldN[2]);
            expect(nDot).toBeGreaterThan(0.95);

            // Depths should match in magnitude
            const goldDepths = gv.contacts
                .map((c: { depth: number }) => c.depth)
                .sort((a: number, b: number) => a - b);
            const ourDepths = result.map((c) => c.depth).sort((a, b) => a - b);
            for (let i = 0; i < goldDepths.length; i++) {
                expect(Math.abs(Math.abs(ourDepths[i]) - Math.abs(goldDepths[i]))).toBeLessThan(
                    0.05,
                );
            }
        });
    }
});

// ── Hull-box delegation ────────────────────────────────────────────

describe("hull-box", () => {
    test("satHullBox delegates to satHullHull", () => {
        const tet = tetHull();
        const a = body([0, 0, 0], [0, 0, 0, 1]);
        const b = body([0.8, 0, 0]);
        const r1 = satHullBox(a, tet, b);
        const r2 = satHullHull(a, tet, b, CUBE_HULL);
        expect(r1.length).toBe(r2.length);
        for (let i = 0; i < r1.length; i++) {
            expect(Math.abs(r1[i].depth - r2[i].depth)).toBeLessThan(1e-4);
        }
    });
});

// ── Hull-sphere (no Bullet3 reference — tested structurally) ──────

describe("hull-sphere", () => {
    test("sphere penetrating cube face", () => {
        const a = body([0, 0, 0]);
        const b = body([0.7, 0, 0], [0, 0, 0, 1], [0.3, 0.3, 0.3]);
        const result = satHullSphere(a, CUBE_HULL, b);
        expect(result.length).toBe(1);
        expect(result[0].depth).toBeLessThan(0);
    });

    test("sphere separated", () => {
        const a = body([0, 0, 0]);
        const b = body([2, 0, 0], [0, 0, 0, 1], [0.3, 0.3, 0.3]);
        const result = satHullSphere(a, CUBE_HULL, b);
        expect(result.length).toBe(0);
    });
});

// ── Hull-capsule (no Bullet3 reference — tested structurally) ─────

describe("hull-capsule", () => {
    test("capsule endpoint penetrating cube face", () => {
        const a = body([0, 0, 0]);
        const b = body([0, 0.65, 0], [0, 0, 0, 1], [0.1, 0.2, 0.1]);
        const result = satHullCapsule(a, CUBE_HULL, b);
        expect(result.length).toBeGreaterThanOrEqual(1);
    });

    test("capsule separated", () => {
        const a = body([0, 0, 0]);
        const b = body([0, 3, 0], [0, 0, 0, 1], [0.1, 0.3, 0.1]);
        const result = satHullCapsule(a, CUBE_HULL, b);
        expect(result.length).toBe(0);
    });
});

// ── Edge cases ─────────────────────────────────────────────────────

describe("edge cases", () => {
    test("parallel edges: no NaN", () => {
        const a = body([0, 0, 0]);
        const b = body([0.9, 0, 0]);
        const result = satHullHull(a, CUBE_HULL, b, CUBE_HULL);
        for (const c of result) {
            expect(Number.isNaN(c.normal[0])).toBe(false);
            expect(Number.isNaN(c.depth)).toBe(false);
        }
    });
});
