import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Plugin } from "../../src/engine/app";
import { deviceTier } from "../../src/engine/app/compose";

export interface DeviceTierSet {
    readonly name: "standard" | "extras";
    readonly plugins: readonly Plugin[];
}

export interface DeviceTierContextSet {
    readonly tier: "cpu" | "gpu";
    readonly required: readonly string[];
    readonly optional: readonly string[];
    readonly undeclared: readonly string[];
}

export type DeviceTierContext = Readonly<Record<DeviceTierSet["name"], DeviceTierContextSet>>;

function pluginsFrom(namespace: Record<string, unknown>): Plugin[] {
    return Object.entries(namespace)
        .filter(
            ([key, value]) => key.endsWith("Plugin") && value !== null && typeof value === "object",
        )
        .map(([, value]) => value as Plugin)
        .filter((plugin) => typeof plugin.name === "string")
        .sort((a, b) => a.name.localeCompare(b.name));
}

/** The complete plugin sets whose declarations are published in the contributor context. */
export async function deviceTierSets(): Promise<readonly DeviceTierSet[]> {
    const [standard, extras] = await Promise.all([
        import("../../src/standard/index"),
        import("../../src/extras/index"),
    ]);
    return [
        { name: "standard", plugins: pluginsFrom(standard) },
        { name: "extras", plugins: pluginsFrom(extras) },
    ];
}

export async function deviceTierContext(): Promise<DeviceTierContext> {
    const result = {} as Record<DeviceTierSet["name"], DeviceTierContextSet>;
    for (const set of await deviceTierSets()) {
        const tier = deviceTier(set.plugins);
        const declared = new Set([...tier.required, ...tier.optional]);
        result[set.name] = {
            tier: tier.tier,
            required: tier.required,
            optional: tier.optional,
            undeclared: set.plugins
                .filter((plugin) => !declared.has(plugin.name))
                .map((plugin) => plugin.name),
        };
    }
    return result;
}

function cell(names: readonly string[]): string {
    return names.length === 0 ? "—" : names.join(", ");
}

export function renderTierTable(context: DeviceTierContext): string {
    const rows = (["standard", "extras"] as const).map((name) => {
        const set = context[name];
        return `| ${name} | ${set.tier} | ${cell(set.required)} | ${cell(set.optional)} | ${cell(set.undeclared)} |`;
    });
    return [
        "<!-- device-tiers:start -->",
        "| Plugin set | Composition tier | `required` (GPU) | `optional` (CPU/GPU) | absent declaration (CPU) |",
        "| --- | --- | --- | --- | --- |",
        ...rows,
        "<!-- device-tiers:end -->",
    ].join("\n");
}

export function renderPackedContext(context: DeviceTierContext): string {
    const set = (name: "standard" | "extras"): string => {
        const value = context[name];
        const list = (names: readonly string[]) =>
            `[${names.map((entry) => JSON.stringify(entry)).join(", ")}]`;
        return [
            `    ${name}: {`,
            `        tier: ${JSON.stringify(value.tier)},`,
            `        required: ${list(value.required)},`,
            `        optional: ${list(value.optional)},`,
            `        undeclared: ${list(value.undeclared)},`,
            "    },",
        ].join("\n");
    };
    return [
        "/** GENERATED by scripts/generate/device-tiers.ts — do not hand-edit. */",
        "export const DEVICE_TIER_CONTEXT = {",
        set("standard"),
        set("extras"),
        "} as const;",
        "",
    ].join("\n");
}

export function replaceGeneratedTable(document: string, table: string, file: string): string {
    const pattern = /<!-- device-tiers:start -->[\s\S]*?<!-- device-tiers:end -->/;
    if (!pattern.test(document))
        throw new Error(`${file} is missing the device tier table markers`);
    return document.replace(pattern, table);
}

if (import.meta.main) {
    const root = resolve(import.meta.dir, "../..");
    const context = await deviceTierContext();
    const contributing = resolve(root, "CONTRIBUTING.md");
    const current = readFileSync(contributing, "utf8");
    await Bun.write(
        contributing,
        replaceGeneratedTable(current, renderTierTable(context), "CONTRIBUTING.md"),
    );
    await Bun.write(
        resolve(root, "src/engine/app/device-tiers.generated.ts"),
        renderPackedContext(context),
    );
    console.log("generated CONTRIBUTING.md and src/engine/app/device-tiers.generated.ts");
}
