//! Bit-exact parity of the Rust pose-finalize phase against the box3d C reference
//! (BOX3D_DISABLE_SIMD + FORCE_OVERFLOW), read from the committed gold vectors
//! (`src/finalize.gold.json`, generated by `bun run gen-finalize-gold`). The generator reproduces
//! b3FinalizeBodiesTask's pose-advance arithmetic over the real b3 math library; this drives the Rust
//! port over the same shared columns and asserts every written column field bit-for-bit.

use serde_json::Value;
use tumble_kernel::body::{
    flags::DYNAMIC, FIN_OUT_STRIDE, FIN_STRIDE, SIM_STRIDE, SIM2_STRIDE, STATE_LIVE, STATE_STRIDE,
    S2_CENTER0, S2_MIN_EXTENT, S2_ROTATION0,
};
use tumble_kernel::col::Col;
use tumble_kernel::finalize::finalize;

/// SAFETY: a gold harness is single-threaded and each column has exactly one user, so `Col`'s
/// disjoint-write promise holds trivially.
fn col<T: Copy>(v: &mut [T]) -> Col<'_, T> {
    unsafe { Col::of(v) }
}

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/finalize.gold.json");

fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

fn scalar(v: &Value) -> f32 {
    from_bits(v.as_str().expect("hex str"))
}

fn floats(v: &Value) -> Vec<f32> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| from_bits(e.as_str().expect("hex str")))
        .collect()
}

fn assert_bits(got: f32, want: f32, label: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{label}: got 0x{:08x} ({got}), want 0x{:08x} ({want})",
        got.to_bits(),
        want.to_bits(),
    );
}

#[test]
fn finalize_matches_c() {
    let gold: Value = serde_json::from_str(GOLD).expect("gold json");
    let cases = gold["cases"].as_array().expect("cases");
    assert!(!cases.is_empty());

    for (c, case) in cases.iter().enumerate() {
        let sim_in = floats(&case["sim"]); // SIM_STRIDE
        let state_live = floats(&case["state"]); // STATE_LIVE
        let fin_in = floats(&case["fin"]); // FIN_STRIDE
        let h = scalar(&case["h"]);
        let inv_dt = scalar(&case["invDt"]);

        let want_sim = floats(&case["outSim"]);
        let want_state = floats(&case["outState"]);
        let want_fin = floats(&case["outFin"]);
        let want_out = floats(&case["out"]);

        assert_eq!(sim_in.len(), SIM_STRIDE);
        assert_eq!(fin_in.len(), FIN_STRIDE);

        let mut sim_col = sim_in.clone();
        // Rebuild the padded state column: the gold's live fields, pad slots stay zero.
        let mut state_col = vec![0.0f32; STATE_STRIDE];
        state_col[0..STATE_LIVE].copy_from_slice(&state_live[0..STATE_LIVE]);
        let mut fin_col = fin_in.clone();
        let mut out_col = vec![0.0f32; FIN_OUT_STRIDE];
        // Sweep-base fold: flags = 0 (not dynamic) makes every body a non-candidate, so finalize always
        // writes center0/rotation0 into sim2 — the path this test then asserts against the advanced pose.
        let mut sim2_col = vec![0.0f32; SIM2_STRIDE];
        let mut flags_col = vec![0u32; 1];

        finalize(
            col(&mut state_col),
            col(&mut sim_col),
            col(&mut fin_col),
            col(&mut out_col),
            col(&mut sim2_col),
            col(&mut flags_col),
            0,
            1,
            h,
            inv_dt,
            true,
        );

        for k in 0..SIM_STRIDE {
            assert_bits(sim_col[k], want_sim[k], &format!("case[{c}].sim[{k}]"));
        }
        for k in 0..STATE_LIVE {
            assert_bits(
                state_col[k],
                want_state[k],
                &format!("case[{c}].state[{k}]"),
            );
        }
        for k in 0..FIN_STRIDE {
            assert_bits(fin_col[k], want_fin[k], &format!("case[{c}].fin[{k}]"));
        }
        for k in 0..FIN_OUT_STRIDE {
            assert_bits(out_col[k], want_out[k], &format!("case[{c}].out[{k}]"));
        }
        // The sweep base is a raw copy of the advanced pose: center0 = advanced center (fin slots 0..3),
        // rotation0 = advanced rotation (sim slots 28..32).
        for k in 0..3 {
            assert_bits(
                sim2_col[S2_CENTER0 + k],
                want_fin[k],
                &format!("case[{c}].center0[{k}]"),
            );
        }
        for k in 0..4 {
            assert_bits(
                sim2_col[S2_ROTATION0 + k],
                want_sim[28 + k],
                &format!("case[{c}].rotation0[{k}]"),
            );
        }
    }
}

/// Pins the fast-candidate skip branch the gold cases (flags = 0) never reach: two DYNAMIC bodies whose
/// `max_motion` (0.4 — a pure delta-position advance) straddles `0.5 * minExtent`. With continuous
/// enabled, the above-threshold body's sweep base must NOT be overwritten (the CCD path owns it) while
/// the below-threshold body's must be the advanced pose; with continuous disabled, no body is a fast
/// candidate and both get the base. A predicate inversion fails all three assertions.
#[test]
fn sweep_base_skips_fast_candidates() {
    const SENTINEL: f32 = 99.0;
    let n = 2;

    let build = || {
        let mut state = vec![0.0f32; n * STATE_STRIDE];
        let mut sim = vec![0.0f32; n * SIM_STRIDE];
        let mut fin = vec![0.0f32; n * FIN_STRIDE];
        let out = vec![0.0f32; n * FIN_OUT_STRIDE];
        let mut sim2 = vec![SENTINEL; n * SIM2_STRIDE];
        let flags = vec![DYNAMIC; n];
        for i in 0..n {
            // deltaPosition = (0.4, 0, 0), deltaRotation = identity, velocities zero:
            // maxDeltaPosition = 0.4, maxVelocity = 0 → maxMotion = 0.4.
            state[i * STATE_STRIDE + 6] = 0.4;
            state[i * STATE_STRIDE + 12] = 1.0; // deltaRotation.s
            sim[i * SIM_STRIDE + 31] = 1.0; // rotation = identity
            fin[i * FIN_STRIDE] = 1.0; // center = (1, 2, 3)
            fin[i * FIN_STRIDE + 1] = 2.0;
            fin[i * FIN_STRIDE + 2] = 3.0;
        }
        // Body 0: 0.4 > 0.5 * 0.5 → fast candidate. Body 1: 0.4 > 0.5 * 2.0 is false → not.
        sim2[S2_MIN_EXTENT] = 0.5;
        sim2[SIM2_STRIDE + S2_MIN_EXTENT] = 2.0;
        (state, sim, fin, out, sim2, flags)
    };

    let assert_base = |sim2: &[f32], sim: &[f32], fin: &[f32], i: usize, written: bool| {
        let s2 = i * SIM2_STRIDE;
        for k in 0..4 {
            let want = if written { sim[i * SIM_STRIDE + 28 + k] } else { SENTINEL };
            assert_bits(
                sim2[s2 + S2_ROTATION0 + k],
                want,
                &format!("body[{i}].rotation0[{k}] (written={written})"),
            );
        }
        for k in 0..3 {
            let want = if written { fin[i * FIN_STRIDE + k] } else { SENTINEL };
            assert_bits(
                sim2[s2 + S2_CENTER0 + k],
                want,
                &format!("body[{i}].center0[{k}] (written={written})"),
            );
        }
    };

    // Continuous enabled: the fast candidate is skipped, the slow body written.
    let (mut state, mut sim, mut fin, mut out, mut sim2, mut flags) = build();
    finalize(
        col(&mut state),
        col(&mut sim),
        col(&mut fin),
        col(&mut out),
        col(&mut sim2),
        col(&mut flags),
        0,
        n,
        1.0,
        1.0,
        true,
    );
    assert_base(&sim2, &sim, &fin, 0, false);
    assert_base(&sim2, &sim, &fin, 1, true);

    // Continuous disabled: no fast candidates — both bodies get the sweep base.
    let (mut state, mut sim, mut fin, mut out, mut sim2, mut flags) = build();
    finalize(
        col(&mut state),
        col(&mut sim),
        col(&mut fin),
        col(&mut out),
        col(&mut sim2),
        col(&mut flags),
        0,
        n,
        1.0,
        1.0,
        false,
    );
    assert_base(&sim2, &sim, &fin, 0, true);
    assert_base(&sim2, &sim, &fin, 1, true);
}
