//! Bit-exact parity of the Rust body-integration phases against the box3d C reference
//! (BOX3D_DISABLE_SIMD + FORCE_OVERFLOW), read from the committed gold vectors
//! (`src/integrate.gold.json`, generated by `bun run gen-integrate-gold`). The generator reproduces
//! b3IntegrateVelocitiesTask / b3IntegratePositionsTask over the real b3 math library; this drives
//! the Rust port over the same shared body-state columns and asserts every output float bit-for-bit.

use serde_json::Value;
use tumble_kernel::body::{SIM_STRIDE, STATE_LIVE, STATE_STRIDE};
use tumble_kernel::col::Col;
use tumble_kernel::integrate::{integrate_positions, integrate_velocities};
use tumble_kernel::math::Vec3;

/// SAFETY: a gold harness is single-threaded and each column has exactly one user, so `Col`'s
/// disjoint-write promise holds trivially.
fn col<T: Copy>(v: &mut [T]) -> Col<'_, T> {
    unsafe { Col::of(v) }
}

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/integrate.gold.json");

fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

fn floats(v: &Value) -> Vec<f32> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| from_bits(e.as_str().expect("hex str")))
        .collect()
}

fn assert_bits(got: f32, want: f32, label: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{label}: got 0x{:08x} ({got}), want 0x{:08x} ({want})",
        got.to_bits(),
        want.to_bits(),
    );
}

#[test]
fn integrate_velocities_matches_c() {
    let gold: Value = serde_json::from_str(GOLD).expect("gold json");
    let cases = gold["velocities"].as_array().expect("velocities");
    assert!(!cases.is_empty());

    for (c, case) in cases.iter().enumerate() {
        let input = floats(&case["in"]); // sim(32) + lin(3) + ang(3) + dr(4) + gravity(3) + h(1)
        let want = floats(&case["out"]); // lv(3) + av(3)

        let mut sim_col = input[0..SIM_STRIDE].to_vec();
        // Rebuild the full state column; deltaPosition (slots 6..9) is unused by this phase.
        let mut state_col = vec![0.0f32; STATE_STRIDE];
        state_col[0..3].copy_from_slice(&input[32..35]); // linearVelocity
        state_col[3..6].copy_from_slice(&input[35..38]); // angularVelocity
        state_col[9..13].copy_from_slice(&input[38..42]); // deltaRotation
        let gravity = Vec3::new(input[42], input[43], input[44]);
        let h = input[45];

        integrate_velocities(
            col(&mut state_col),
            col(&mut sim_col),
            0,
            1,
            gravity,
            h,
        );

        for k in 0..3 {
            assert_bits(
                state_col[k],
                want[k],
                &format!("vel[{c}].linearVelocity[{k}]"),
            );
            assert_bits(
                state_col[3 + k],
                want[3 + k],
                &format!("vel[{c}].angularVelocity[{k}]"),
            );
        }
    }
}

#[test]
fn integrate_positions_matches_c() {
    let gold: Value = serde_json::from_str(GOLD).expect("gold json");
    let cases = gold["positions"].as_array().expect("positions");
    assert!(!cases.is_empty());

    for (c, case) in cases.iter().enumerate() {
        let input = floats(&case["in"]); // state(13) + h + maxLinearVelocity + inv_dt
        let want = floats(&case["out"]); // full state(13)
        let flags_in = case["flags"].as_u64().expect("flags") as u32;
        let flags_out = case["outFlags"].as_u64().expect("outFlags") as u32;

        // The gold in-array's first 13 floats are exactly the live state fields; the column pads to
        // STATE_STRIDE (unused slots stay zero for the single body).
        let mut state_col = vec![0.0f32; STATE_STRIDE];
        state_col[0..STATE_LIVE].copy_from_slice(&input[0..STATE_LIVE]);
        let mut flags_col = vec![flags_in];
        let h = input[STATE_LIVE];
        let max_linear_velocity = input[STATE_LIVE + 1];
        let inv_dt = input[STATE_LIVE + 2];

        integrate_positions(
            col(&mut state_col),
            col(&mut flags_col),
            0,
            1,
            h,
            max_linear_velocity,
            inv_dt,
        );

        for k in 0..STATE_LIVE {
            assert_bits(state_col[k], want[k], &format!("pos[{c}].state[{k}]"));
        }
        assert_eq!(flags_col[0], flags_out, "pos[{c}].flags");
    }
}
