//! Bit-exact parity of the Rust convex narrowphase against the box3d C reference, read from the
//! committed gold vectors the TS port also verifies against (`src/manifold.gold.json`, generated by
//! `bun run gen-manifold-gold`). Mirrors the convex describe-blocks in `src/manifold.test.ts`
//! (spheres / capsule-sphere / hull-sphere / capsules / hull-capsule / hulls). The mesh-tier
//! triangle scenes stay TS-side (3c ports only the six convex pair functions), so they are not
//! covered here.
//!
//! The port has no quickhull, so each hull scene carries the raw half-edge hull arrays the C harness
//! dumped (`hull` / `hullA` / `hullB`); this test rebuilds an identical `HullData` from them. The
//! cache-taking scenes run twice with one shared cache, matching the C harness's double call.

use serde_json::Value;
use tumble_kernel::distance::SimplexCache;
use tumble_kernel::hull::{HullData, HullFace, HullHalfEdge, HullVertex};
use tumble_kernel::manifold::{
    collide_capsule_and_sphere, collide_capsules, collide_hull_and_capsule,
    collide_hull_and_sphere, collide_hulls, collide_spheres, make_feature_id, Capsule,
    LocalManifold, SatCache, Sphere,
};
use tumble_kernel::math::{Plane, Quat, Transform, Vec3};

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/manifold.gold.json");

fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

fn assert_bits(got: f32, want: &str, label: &str) {
    let want_bits = u32::from_str_radix(want.trim_start_matches("0x"), 16).expect("hex");
    assert_eq!(
        got.to_bits(),
        want_bits,
        "{label}: got 0x{:08x} ({got}), want {want} ({})",
        got.to_bits(),
        from_bits(want),
    );
}

fn vec3(a: &Value) -> Vec3 {
    let a = a.as_array().unwrap();
    Vec3::new(
        from_bits(a[0].as_str().unwrap()),
        from_bits(a[1].as_str().unwrap()),
        from_bits(a[2].as_str().unwrap()),
    )
}

fn assert_vec(got: Vec3, want: &Value, label: &str) {
    let a = want.as_array().unwrap();
    assert_bits(got.x, a[0].as_str().unwrap(), &format!("{label}.x"));
    assert_bits(got.y, a[1].as_str().unwrap(), &format!("{label}.y"));
    assert_bits(got.z, a[2].as_str().unwrap(), &format!("{label}.z"));
}

fn xf(o: &Value) -> Transform {
    let p = o["p"].as_array().unwrap();
    let q = o["q"].as_array().unwrap();
    Transform {
        p: Vec3::new(
            from_bits(p[0].as_str().unwrap()),
            from_bits(p[1].as_str().unwrap()),
            from_bits(p[2].as_str().unwrap()),
        ),
        q: Quat {
            v: Vec3::new(
                from_bits(q[0].as_str().unwrap()),
                from_bits(q[1].as_str().unwrap()),
                from_bits(q[2].as_str().unwrap()),
            ),
            s: from_bits(q[3].as_str().unwrap()),
        },
    }
}

fn sphere(o: &Value) -> Sphere {
    Sphere {
        center: vec3(&o["center"]),
        radius: from_bits(o["radius"].as_str().unwrap()),
    }
}

fn capsule(o: &Value) -> Capsule {
    Capsule {
        center1: vec3(&o["center1"]),
        center2: vec3(&o["center2"]),
        radius: from_bits(o["radius"].as_str().unwrap()),
    }
}

/// Owns the hull pools parsed from JSON so a `HullData` view can borrow them (the narrowphase reads a
/// borrowed view; here the pools are plain `Vec`s, mirroring the wasm kernel borrowing the geometry
/// columns).
struct HullStore {
    center: Vec3,
    vertex_count: usize,
    edge_count: usize,
    face_count: usize,
    points: Vec<Vec3>,
    vertices: Vec<HullVertex>,
    edges: Vec<HullHalfEdge>,
    faces: Vec<HullFace>,
    planes: Vec<Plane>,
}

impl HullStore {
    fn view(&self) -> HullData<'_> {
        HullData {
            center: self.center,
            vertex_count: self.vertex_count,
            edge_count: self.edge_count,
            face_count: self.face_count,
            points: &self.points,
            vertices: &self.vertices,
            edges: &self.edges,
            faces: &self.faces,
            planes: &self.planes,
        }
    }
}

fn hull(o: &Value) -> HullStore {
    let points = o["points"].as_array().unwrap().iter().map(vec3).collect();
    let vertices = o["vertices"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| HullVertex {
            edge: e.as_u64().unwrap() as usize,
        })
        .collect();
    let edges = o["edges"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            let e = e.as_array().unwrap();
            HullHalfEdge {
                next: e[0].as_u64().unwrap() as usize,
                twin: e[1].as_u64().unwrap() as usize,
                origin: e[2].as_u64().unwrap() as usize,
                face: e[3].as_u64().unwrap() as usize,
            }
        })
        .collect();
    let faces = o["faces"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| HullFace {
            edge: e.as_u64().unwrap() as usize,
        })
        .collect();
    let planes = o["planes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| Plane {
            normal: vec3(&p["normal"]),
            offset: from_bits(p["offset"].as_str().unwrap()),
        })
        .collect();
    HullStore {
        center: vec3(&o["center"]),
        vertex_count: o["vertexCount"].as_u64().unwrap() as usize,
        edge_count: o["edgeCount"].as_u64().unwrap() as usize,
        face_count: o["faceCount"].as_u64().unwrap() as usize,
        points,
        vertices,
        edges,
        faces,
        planes,
    }
}

fn check_manifold(m: &LocalManifold, want: &Value, label: &str) {
    let want_count = want["pointCount"].as_u64().unwrap() as usize;
    assert_eq!(m.point_count, want_count, "{label}.pointCount");
    // The normal is only meaningful when there are points; C leaves it stale otherwise.
    if m.point_count > 0 {
        assert_vec(m.normal, &want["normal"], &format!("{label}.normal"));
    }
    let pts = want["points"].as_array().unwrap();
    for i in 0..want_count {
        let pt = &m.points[i];
        let wp = &pts[i];
        assert_vec(
            pt.point,
            &wp["point"],
            &format!("{label}.points[{i}].point"),
        );
        assert_bits(
            pt.separation,
            wp["separation"].as_str().unwrap(),
            &format!("{label}.points[{i}].separation"),
        );
        assert_eq!(
            make_feature_id(pt.pair) as u64,
            wp["featureId"].as_u64().unwrap(),
            "{label}.points[{i}].featureId"
        );
    }
}

fn check_sat_cache(c: &SatCache, want: &Value, label: &str) {
    assert_bits(
        c.separation,
        want["separation"].as_str().unwrap(),
        &format!("{label}.separation"),
    );
    assert_eq!(c.ty as u64, want["type"].as_u64().unwrap(), "{label}.type");
    assert_eq!(
        c.index_a as u64,
        want["indexA"].as_u64().unwrap(),
        "{label}.indexA"
    );
    assert_eq!(
        c.index_b as u64,
        want["indexB"].as_u64().unwrap(),
        "{label}.indexB"
    );
}

fn gold() -> Value {
    serde_json::from_str(GOLD).expect("parse manifold.gold.json")
}

#[test]
fn spheres_bit_exact() {
    let g = gold();
    for scene in g["spheres"].as_array().unwrap() {
        let name = scene["name"].as_str().unwrap();
        let a = sphere(&scene["a"]);
        let b = sphere(&scene["b"]);
        let t = xf(&scene["xf"]);
        let mut m = LocalManifold::new();
        collide_spheres(&mut m, 1, &a, &b, t);
        check_manifold(&m, &scene["manifold"], name);
    }
}

#[test]
fn capsule_sphere_bit_exact() {
    let g = gold();
    for scene in g["capsuleSphere"].as_array().unwrap() {
        let name = scene["name"].as_str().unwrap();
        let a = capsule(&scene["a"]);
        let b = sphere(&scene["b"]);
        let t = xf(&scene["xf"]);
        let mut m = LocalManifold::new();
        collide_capsule_and_sphere(&mut m, 1, &a, &b, t);
        check_manifold(&m, &scene["manifold"], name);
    }
}

#[test]
fn hull_sphere_bit_exact() {
    let g = gold();
    for scene in g["hullSphere"].as_array().unwrap() {
        let name = scene["name"].as_str().unwrap();
        let a_store = hull(&scene["hull"]);
        let a = a_store.view();
        let b = sphere(&scene["b"]);
        let t = xf(&scene["xf"]);
        let mut m = LocalManifold::new();
        let mut cache = SimplexCache::empty();
        for (call, want) in scene["manifolds"].as_array().unwrap().iter().enumerate() {
            collide_hull_and_sphere(&mut m, 1, &a, &b, t, &mut cache);
            check_manifold(&m, want, &format!("{name}[{call}]"));
        }
    }
}

#[test]
fn capsules_bit_exact() {
    let g = gold();
    for scene in g["capsules"].as_array().unwrap() {
        let name = scene["name"].as_str().unwrap();
        let a = capsule(&scene["a"]);
        let b = capsule(&scene["b"]);
        let t = xf(&scene["xf"]);
        let mut m = LocalManifold::new();
        collide_capsules(&mut m, 2, &a, &b, t);
        check_manifold(&m, &scene["manifold"], name);
    }
}

#[test]
fn hull_capsule_bit_exact() {
    let g = gold();
    for scene in g["hullCapsule"].as_array().unwrap() {
        let name = scene["name"].as_str().unwrap();
        let a_store = hull(&scene["hull"]);
        let a = a_store.view();
        let b = capsule(&scene["b"]);
        let t = xf(&scene["xf"]);
        let mut m = LocalManifold::new();
        let mut cache = SimplexCache::empty();
        for (call, want) in scene["manifolds"].as_array().unwrap().iter().enumerate() {
            collide_hull_and_capsule(&mut m, 2, &a, &b, t, &mut cache);
            check_manifold(&m, want, &format!("{name}[{call}]"));
        }
    }
}

#[test]
fn hulls_bit_exact() {
    let g = gold();
    for scene in g["hulls"].as_array().unwrap() {
        let name = scene["name"].as_str().unwrap();
        let a_store = hull(&scene["hullA"]);
        let a = a_store.view();
        let b_store = hull(&scene["hullB"]);
        let b = b_store.view();
        let t = xf(&scene["xf"]);
        let mut m = LocalManifold::new();
        let mut cache = SatCache::empty();
        let manifolds = scene["manifolds"].as_array().unwrap();
        let caches = scene["caches"].as_array().unwrap();
        for call in 0..manifolds.len() {
            collide_hulls(&mut m, 8, &a, &b, t, &mut cache);
            check_manifold(&m, &manifolds[call], &format!("{name}[{call}]"));
            check_sat_cache(&cache, &caches[call], &format!("{name}.cache[{call}]"));
        }
    }
}
