//! Bit-exact parity of the Rust scalar math against the box3d C reference (BOX3D_DISABLE_SIMD +
//! FORCE_OVERFLOW), read from the committed gold vectors the TS port also verifies against
//! (`src/math.gold.json`, generated by `bun run gen-math-gold`). This is the load-bearing proof
//! that Rust native f32 equals the fround-per-op TS port equals C scalar, op for op — the premise
//! the whole kernel port rests on. Mirrors the `dispatch` table in `src/math.test.ts`.

use serde_json::Value;
use tumble_kernel::math::*;

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/math.gold.json");

// Reconstruct an exact f32 from the raw hex bits the C generator emitted — no decimal round-trip.
fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

// Bit-exact: compare raw bit patterns so ±0 and NaN payloads count as divergence (like Object.is).
fn assert_bits(got: f32, want: &str, label: &str) {
    let want_bits = u32::from_str_radix(want.trim_start_matches("0x"), 16).expect("hex");
    assert_eq!(
        got.to_bits(),
        want_bits,
        "{label}: got 0x{:08x} ({got}), want {want} ({})",
        got.to_bits(),
        from_bits(want),
    );
}

// --- flat reconstruct / flatten, matching the C generator's field order ----------------------

fn v3(a: &[f32], o: usize) -> Vec3 {
    Vec3::new(a[o], a[o + 1], a[o + 2])
}
fn quat(a: &[f32], o: usize) -> Quat {
    Quat {
        v: v3(a, o),
        s: a[o + 3],
    }
}
fn mat3(a: &[f32], o: usize) -> Mat3 {
    Mat3 {
        cx: v3(a, o),
        cy: v3(a, o + 3),
        cz: v3(a, o + 6),
    }
}
fn mat2(a: &[f32], o: usize) -> Mat2 {
    Mat2 {
        cx: Vec2::new(a[o], a[o + 1]),
        cy: Vec2::new(a[o + 2], a[o + 3]),
    }
}
fn xf(a: &[f32], o: usize) -> Transform {
    Transform {
        p: v3(a, o),
        q: quat(a, o + 3),
    }
}

fn flat_v(v: Vec3) -> Vec<f32> {
    vec![v.x, v.y, v.z]
}
fn flat_v2(v: Vec2) -> Vec<f32> {
    vec![v.x, v.y]
}
fn flat_q(q: Quat) -> Vec<f32> {
    vec![q.v.x, q.v.y, q.v.z, q.s]
}
fn flat_m(m: Mat3) -> Vec<f32> {
    vec![
        m.cx.x, m.cx.y, m.cx.z, m.cy.x, m.cy.y, m.cy.z, m.cz.x, m.cz.y, m.cz.z,
    ]
}
fn flat_m2(m: Mat2) -> Vec<f32> {
    vec![m.cx.x, m.cx.y, m.cy.x, m.cy.y]
}
fn flat_t(t: Transform) -> Vec<f32> {
    vec![t.p.x, t.p.y, t.p.z, t.q.v.x, t.q.v.y, t.q.v.z, t.q.s]
}

// Each case maps its flat input array to the port's flat output array (mirrors src/math.test.ts).
fn dispatch(name: &str, a: &[f32]) -> Vec<f32> {
    match name {
        "normalizeVec3" => flat_v(v3(a, 0).normalize()),
        "lengthVec3" => vec![v3(a, 0).length()],
        "arbitraryPerp" => flat_v(arbitrary_perp(v3(a, 0))),
        "scalarTripleProduct" => vec![scalar_triple_product(v3(a, 0), v3(a, 3), v3(a, 6))],
        "normalizeQuat" => flat_q(quat(a, 0).normalize()),
        "makeQuatFromAxisAngle" => flat_q(Quat::from_axis_angle(v3(a, 0), a[3])),
        "mulQuat" => flat_q(quat(a, 0).mul(quat(a, 4))),
        "invMulQuat" => flat_q(quat(a, 0).inv_mul(quat(a, 4))),
        "rotateVector" => flat_v(quat(a, 0).rotate(v3(a, 4))),
        "invRotateVector" => flat_v(quat(a, 0).inv_rotate(v3(a, 4))),
        "computeQuatBetween" | "computeQuatBetweenAntiparallel" => {
            flat_q(compute_quat_between_unit_vectors(v3(a, 0), v3(a, 3)))
        }
        "makeQuatFromMatrix" => flat_q(make_quat_from_matrix(mat3(a, 0))),
        "makeMatrixFromQuat" => flat_m(Mat3::from_quat(quat(a, 0))),
        "invertMatrix" => flat_m(mat3(a, 0).invert()),
        "solve3" => flat_v(mat3(a, 0).solve(v3(a, 9))),
        "mulMV" => flat_v(mat3(a, 0).mul_v(v3(a, 9))),
        "mulMM" => flat_m(mat3(a, 0).mul(mat3(a, 9))),
        "invert2" => flat_m2(mat2(a, 0).invert()),
        "solve2" => flat_v2(mat2(a, 0).solve(Vec2::new(a[4], a[5]))),
        "nlerp" => flat_q(quat(a, 0).nlerp(quat(a, 4), a[8])),
        "getTwistAngle" => vec![quat(a, 0).get_twist_angle()],
        "getSwingAngle" => vec![quat(a, 0).get_swing_angle()],
        "transformPoint" => flat_v(xf(a, 0).point(v3(a, 7))),
        "invTransformPoint" => flat_v(xf(a, 0).inv_point(v3(a, 7))),
        "mulTransforms" => flat_t(xf(a, 0).mul(xf(a, 7))),
        // Gold `in` is [t2, t1]; the reference computed b3InvMulTransforms(t1, t2), so swap.
        "invMulTransforms" => flat_t(xf(a, 7).inv_mul(xf(a, 0))),
        other => panic!("unmapped gold case fn: {other}"),
    }
}

fn gold() -> Value {
    serde_json::from_str(GOLD).expect("parse math.gold.json")
}

#[test]
fn atan2_sweep() {
    let g = gold();
    for row in g["atan2"].as_array().unwrap() {
        let y = from_bits(row[0].as_str().unwrap());
        let x = from_bits(row[1].as_str().unwrap());
        let want = row[2].as_str().unwrap();
        assert_bits(atan2(y, x), want, "atan2");
    }
}

#[test]
fn compute_cos_sin_sweep() {
    let g = gold();
    for row in g["cosSin"].as_array().unwrap() {
        let angle = from_bits(row[0].as_str().unwrap());
        let cs = compute_cos_sin(angle);
        assert_bits(cs.cosine, row[1].as_str().unwrap(), "cos");
        assert_bits(cs.sine, row[2].as_str().unwrap(), "sin");
    }
}

#[test]
fn vec_quat_matrix_transform_cases() {
    let g = gold();
    for case in g["cases"].as_array().unwrap() {
        let name = case["fn"].as_str().unwrap();
        let input: Vec<f32> = case["in"]
            .as_array()
            .unwrap()
            .iter()
            .map(|h| from_bits(h.as_str().unwrap()))
            .collect();
        let out = case["out"].as_array().unwrap();
        let got = dispatch(name, &input);
        assert_eq!(got.len(), out.len(), "{name}: output arity");
        for (i, want) in out.iter().enumerate() {
            assert_bits(got[i], want.as_str().unwrap(), &format!("{name}[{i}]"));
        }
    }
}
