//! Bit-exact parity of the Rust contact-recycle port against the box3d C reference
//! (BOX3D_DISABLE_SIMD), read from the committed gold vectors (`src/recycle.gold.json`, generated by
//! `bun run gen-recycle-gold`). The generator reproduces b3CollideTask's recycle branch (gate +
//! per-point separation update) over the real b3 math library; this drives the Rust port over the same
//! synthetic manifold pool and asserts the returned recycle decision plus every written pool slot
//! bit-for-bit.

use serde_json::Value;
use tumble_kernel::manifold_abi::{DIR_MANIFOLD_BASE, DIR_STRIDE};
use tumble_kernel::math::{Quat, Transform, Vec3};
use tumble_kernel::col::Col;
use tumble_kernel::recycle::try_recycle;

/// SAFETY: a gold harness is single-threaded and each column has exactly one user, so `Col`'s
/// disjoint-write promise holds trivially.
fn col<T: Copy>(v: &mut [T]) -> Col<'_, T> {
    unsafe { Col::of(v) }
}

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/recycle.gold.json");

fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

fn u32_bits(hex: &str) -> u32 {
    u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex")
}

fn floats(v: &Value) -> Vec<f32> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| from_bits(e.as_str().expect("hex str")))
        .collect()
}

fn u32s(v: &Value) -> Vec<u32> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| u32_bits(e.as_str().expect("hex str")))
        .collect()
}

fn vec3(f: &[f32]) -> Vec3 {
    Vec3::new(f[0], f[1], f[2])
}

/// A flattened `[px, py, pz, qx, qy, qz, qs]` -> Transform.
fn xf(f: &[f32]) -> Transform {
    Transform {
        p: Vec3::new(f[0], f[1], f[2]),
        q: Quat {
            v: Vec3::new(f[3], f[4], f[5]),
            s: f[6],
        },
    }
}

/// A flattened `[qx, qy, qz, qs]` -> Quat.
fn quat(f: &[f32]) -> Quat {
    Quat {
        v: Vec3::new(f[0], f[1], f[2]),
        s: f[3],
    }
}

#[test]
fn recycle_matches_c() {
    let gold: Value = serde_json::from_str(GOLD).expect("gold json");
    let cases = gold["cases"].as_array().expect("cases");
    assert!(!cases.is_empty());

    for (c, case) in cases.iter().enumerate() {
        let xf_a = xf(&floats(&case["xfA"]));
        let xf_b = xf(&floats(&case["xfB"]));
        let cached_rot_a = quat(&floats(&case["cachedRotA"]));
        let cached_rot_b = quat(&floats(&case["cachedRotB"]));
        let cached_rel_pose = xf(&floats(&case["cachedRelPose"]));
        let center_a = vec3(&floats(&case["centerA"]));
        let center_b = vec3(&floats(&case["centerB"]));
        let max_extent_a = vec3(&floats(&case["maxExtentA"]));
        let max_extent_b = vec3(&floats(&case["maxExtentB"]));
        let tol = from_bits(case["tol"].as_str().expect("hex str"));
        let base = case["base"].as_u64().expect("base") as u32;
        let manifold_count = case["manifoldCount"].as_u64().expect("count") as usize;
        let want_recycled = case["recycled"].as_u64().expect("recycled") != 0;

        let pool_in = u32s(&case["poolIn"]);
        let want_pool = u32s(&case["poolOut"]);

        // Contact 0's directory record with the manifold base slot set; the rest is unread by recycle.
        let mut dir = vec![0u32; DIR_STRIDE];
        dir[DIR_MANIFOLD_BASE] = base;

        let mut pool: Vec<f32> = pool_in.iter().map(|&b| f32::from_bits(b)).collect();

        let got_recycled = try_recycle(
            col(&mut dir),
            col(&mut pool),
            0,
            manifold_count,
            xf_a,
            xf_b,
            cached_rot_a,
            cached_rot_b,
            cached_rel_pose,
            center_a,
            center_b,
            max_extent_a,
            max_extent_b,
            tol,
        );

        assert_eq!(
            got_recycled, want_recycled,
            "case[{c}] recycled: got {got_recycled}, want {want_recycled}"
        );
        for (k, &want) in want_pool.iter().enumerate() {
            let got = pool[k].to_bits();
            assert_eq!(
                got, want,
                "case[{c}].pool[{k}]: got 0x{got:08x}, want 0x{want:08x}"
            );
        }
    }
}
