//! Bit-exact gold gate for the in-kernel dynamic-tree query + rebuild (3d), against the Box3D C
//! reference vectors in `src/tree.gold.json` (generated by `fixtures/tree_gold.c`, the same file the TS
//! `tree.test.ts` replays). Not self-referential: every expected state — the rebuilt node pools and the
//! query hit/visit counts — is produced by the C reference, not by this port.
//!
//! The gold's op stream reaches three fully-captured tree states (checkpoints): `afterDestroy` (S0),
//! `afterRebuild` (S1 = S0 rebuilt with `full=false`), `afterFullRebuild` (S2 = S1 rebuilt with
//! `full=true`), and its query ops run against S2. We reconstruct each checkpoint's exact node pool
//! (allocated records + free chain) and check: `rebuild(S0, false) == S1`, `rebuild(S1, true) == S2`,
//! and each query over S2 matches the C hits + node/leaf visit counts.

use serde_json::Value;
use tumble_kernel::tree::{self, Rebuild, STACK_SIZE, STRIDE};

fn load() -> Value {
    let raw = include_str!("../../../src/standard/tumble/engine/tree.gold.json");
    serde_json::from_str(raw).expect("parse tree.gold.json")
}

fn hex_bits(s: &str) -> u32 {
    u32::from_str_radix(s.trim_start_matches("0x"), 16).expect("hex u32")
}

fn checkpoint<'a>(gold: &'a Value, name: &str) -> &'a Value {
    for op in gold["ops"].as_array().unwrap() {
        if op["op"] == "checkpoint" && op["name"] == name {
            return &op["tree"];
        }
    }
    panic!("checkpoint {name} not found");
}

struct Pool {
    slots: Vec<u32>,
    root: i32,
    node_count: usize,
    free_list: i32,
    proxy_count: usize,
}

/// Reconstruct a node pool from a checkpoint's captured state — the exact C memory image (allocated
/// records at their indices + the free-list chain), so a rebuild replays C's node-index allocation.
fn reconstruct(tree_json: &Value) -> Pool {
    let cap = tree_json["nodeCapacity"].as_u64().unwrap() as usize;
    let mut slots = vec![0u32; cap * STRIDE];

    for node in tree_json["nodes"].as_array().unwrap() {
        let i = node["i"].as_u64().unwrap() as usize;
        let n = i * STRIDE;
        let aabb = &node["aabb"];
        let lo = aabb["lo"].as_array().unwrap();
        let hi = aabb["hi"].as_array().unwrap();
        slots[n] = hex_bits(lo[0].as_str().unwrap());
        slots[n + 1] = hex_bits(lo[1].as_str().unwrap());
        slots[n + 2] = hex_bits(lo[2].as_str().unwrap());
        slots[n + 3] = hex_bits(hi[0].as_str().unwrap());
        slots[n + 4] = hex_bits(hi[1].as_str().unwrap());
        slots[n + 5] = hex_bits(hi[2].as_str().unwrap());

        let category: u64 = node["category"].as_str().unwrap().parse().unwrap();
        slots[n + 6] = (category >> 32) as u32;
        slots[n + 7] = (category & 0xffff_ffff) as u32;

        let leaf = node["leaf"].as_bool().unwrap();
        if leaf {
            let ud: u32 = node["userData"].as_str().unwrap().parse().unwrap();
            slots[n + 8] = ud;
            slots[n + 9] = -1i32 as u32;
        } else {
            slots[n + 8] = node["child1"].as_i64().unwrap() as i32 as u32;
            slots[n + 9] = node["child2"].as_i64().unwrap() as i32 as u32;
        }
        slots[n + 10] = node["parent"].as_i64().unwrap() as i32 as u32;
        let height = node["height"].as_u64().unwrap() as u32;
        let flags = node["flags"].as_u64().unwrap() as u32;
        slots[n + 11] = (height << 16) | flags;
    }

    // Free chain: each free node's `next` (slot 10) points at the next, tail at -1. flags = 0.
    let chain: Vec<i32> = tree_json["freeChain"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    for (k, &idx) in chain.iter().enumerate() {
        let n = idx as usize * STRIDE;
        let next = if k + 1 < chain.len() { chain[k + 1] } else { -1 };
        slots[n + 10] = next as u32;
        slots[n + 11] = 0;
    }

    Pool {
        slots,
        root: tree_json["root"].as_i64().unwrap() as i32,
        node_count: tree_json["nodeCount"].as_u64().unwrap() as usize,
        free_list: tree_json["freeList"].as_i64().unwrap() as i32,
        proxy_count: tree_json["proxyCount"].as_u64().unwrap() as usize,
    }
}

/// Assert a rebuilt pool matches the expected checkpoint node-for-node (structure, aabb, category,
/// height, links) plus the tree scalars.
fn assert_matches(pool: &Pool, expect: &Value, new_root: i32, label: &str) {
    assert_eq!(
        new_root,
        expect["root"].as_i64().unwrap() as i32,
        "{label}: root"
    );
    assert_eq!(
        pool.node_count,
        expect["nodeCount"].as_u64().unwrap() as usize,
        "{label}: nodeCount"
    );
    assert_eq!(
        pool.free_list,
        expect["freeList"].as_i64().unwrap() as i32,
        "{label}: freeList"
    );

    for node in expect["nodes"].as_array().unwrap() {
        let i = node["i"].as_u64().unwrap() as usize;
        let n = i * STRIDE;
        let s = &pool.slots;
        for (k, key) in ["lo", "hi"].iter().enumerate() {
            let arr = node["aabb"][key].as_array().unwrap();
            for c in 0..3 {
                let got = s[n + k * 3 + c];
                let want = hex_bits(arr[c].as_str().unwrap());
                assert_eq!(got, want, "{label}: node {i} aabb {key}[{c}]");
            }
        }
        let category: u64 = node["category"].as_str().unwrap().parse().unwrap();
        assert_eq!(
            s[n + 6],
            (category >> 32) as u32,
            "{label}: node {i} category hi"
        );
        assert_eq!(
            s[n + 7],
            (category & 0xffff_ffff) as u32,
            "{label}: node {i} category lo"
        );
        assert_eq!(
            s[n + 11] >> 16,
            node["height"].as_u64().unwrap() as u32,
            "{label}: node {i} height"
        );
        assert_eq!(
            s[n + 11] & 0xffff,
            node["flags"].as_u64().unwrap() as u32,
            "{label}: node {i} flags"
        );
        assert_eq!(
            s[n + 10] as i32,
            node["parent"].as_i64().unwrap() as i32,
            "{label}: node {i} parent"
        );
        if node["leaf"].as_bool().unwrap() {
            let ud: u32 = node["userData"].as_str().unwrap().parse().unwrap();
            assert_eq!(s[n + 8], ud, "{label}: node {i} userData");
        } else {
            assert_eq!(
                s[n + 8] as i32,
                node["child1"].as_i64().unwrap() as i32,
                "{label}: node {i} child1"
            );
            assert_eq!(
                s[n + 9] as i32,
                node["child2"].as_i64().unwrap() as i32,
                "{label}: node {i} child2"
            );
        }
    }
}

fn run_rebuild(pool: &mut Pool, full: bool) -> i32 {
    let mut leaf_indices = vec![0i32; pool.proxy_count.max(1)];
    let mut leaf_centers = vec![0f32; pool.proxy_count.max(1) * 3];
    let mut gather = vec![0i32; STACK_SIZE];
    let mut build = vec![0i32; STACK_SIZE * 5];
    let mut rb = Rebuild {
        node_count: pool.node_count,
        free_list: pool.free_list,
        leaf_indices: &mut leaf_indices,
        leaf_centers: &mut leaf_centers,
        gather_stack: &mut gather,
        build_stack: &mut build,
    };
    let new_root = tree::rebuild(&mut pool.slots, pool.root, pool.proxy_count, full, &mut rb);
    pool.node_count = rb.node_count;
    pool.free_list = rb.free_list;
    pool.root = new_root;
    new_root
}

#[test]
fn rebuild_partial_matches_c() {
    let gold = load();
    let mut pool = reconstruct(checkpoint(&gold, "afterDestroy"));
    let new_root = run_rebuild(&mut pool, false);
    assert_matches(&pool, checkpoint(&gold, "afterRebuild"), new_root, "afterRebuild");
}

#[test]
fn rebuild_full_matches_c() {
    let gold = load();
    let mut pool = reconstruct(checkpoint(&gold, "afterRebuild"));
    let new_root = run_rebuild(&mut pool, true);
    assert_matches(
        &pool,
        checkpoint(&gold, "afterFullRebuild"),
        new_root,
        "afterFullRebuild",
    );
}

#[test]
fn query_matches_c() {
    let gold = load();
    let pool = reconstruct(checkpoint(&gold, "afterFullRebuild"));
    let mut stack = vec![0i32; STACK_SIZE];

    let mut ran = 0;
    for op in gold["ops"].as_array().unwrap() {
        if op["op"] != "query" {
            continue;
        }
        ran += 1;
        let aabb = &op["aabb"];
        let lo_a = aabb["lo"].as_array().unwrap();
        let hi_a = aabb["hi"].as_array().unwrap();
        let lo = [
            f32::from_bits(hex_bits(lo_a[0].as_str().unwrap())),
            f32::from_bits(hex_bits(lo_a[1].as_str().unwrap())),
            f32::from_bits(hex_bits(lo_a[2].as_str().unwrap())),
        ];
        let hi = [
            f32::from_bits(hex_bits(hi_a[0].as_str().unwrap())),
            f32::from_bits(hex_bits(hi_a[1].as_str().unwrap())),
            f32::from_bits(hex_bits(hi_a[2].as_str().unwrap())),
        ];
        let mask: u64 = op["mask"].as_str().unwrap().parse().unwrap();
        let mask_hi = (mask >> 32) as u32;
        let mask_lo = (mask & 0xffff_ffff) as u32;
        let require_all = op["requireAll"].as_bool().unwrap();

        let mut hits: Vec<i64> = Vec::new();
        let (nv, lv) = tree::query(
            &pool.slots,
            pool.root,
            pool.node_count,
            lo,
            hi,
            mask_hi,
            mask_lo,
            require_all,
            &mut stack,
            |node_id, _ud| {
                hits.push(node_id as i64);
                true
            },
        );

        let want_hits: Vec<i64> = op["hits"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_i64().unwrap())
            .collect();
        assert_eq!(hits, want_hits, "query hits");
        assert_eq!(nv, op["nodeVisits"].as_u64().unwrap() as u32, "nodeVisits");
        assert_eq!(lv, op["leafVisits"].as_u64().unwrap() as u32, "leafVisits");
    }
    assert!(ran >= 5, "expected the gold's query ops");
}
