// Generated by bun scripts/branding.ts from assets/branding; do not edit.
export const MARK = {
    m: [
        "     ▄▄",
        "    ▄██▄",
        "   ▄████▄",
        " ▄████████▄",
        "████████████",
        "▀██████████▀",
        "  ▀▀▀▀▀▀▀▀",
    ],
} as const;

export const FONT: Record<string, readonly string[]> = {
    s: [".....", ".....", ".####", "#....", ".###.", "....#", "####."],
    h: ["#....", "#....", "####.", "#...#", "#...#", "#...#", "#...#"],
    a: [".....", ".....", ".###.", "....#", ".####", "#...#", ".####"],
    l: ["#..", "#..", "#..", "#..", "#..", "#..", ".##"],
    o: [".....", ".....", ".###.", "#...#", "#...#", "#...#", ".###."],
    t: [".#..", ".#..", "####", ".#..", ".#..", ".#..", "..##"],
};

export const NAME = "shallot";

export const DARK = {
    gold: "#d49560",
    dim: "#7a5a3a",
    ink: "#f0e6d6",
    bg: "#141210",
} as const;

export const LIGHT = {
    gold: "#d49560",
    dim: "#e6c6a4",
    ink: "#2a231e",
    bg: "#f7f3ec",
} as const;
