import type { GBuf, Binding } from "../compute";
import type { PrefixSumState } from "../radix";
import type { ProfileState } from "../compute/core";
import type { PhysicsLBVH } from "./lbvh";

export interface SolverParams {
    dt: number;
    gravity: number;
    iterations: number;
    alpha: number;
    betaLin: number;
    betaAng: number;
    gamma: number;
}

export interface PhysicsGPU {
    device: GPUDevice;
    lbvh: PhysicsLBVH;
    warmstartPipeline: GPUComputePipeline;
    clearHashPipeline: GPUComputePipeline;
    rebuildPipeline: GPUComputePipeline;
    bvhTraversalPipeline: GPUComputePipeline;
    narrowphasePipelines: GPUComputePipeline[];
    pairBuffer: GBuf;
    pairBindGroup: Binding;
    detectJointsPipeline: GPUComputePipeline;
    initBodyCachePipeline: GPUComputePipeline;
    cacheContactCPipeline: GPUComputePipeline;
    dualPipeline: GPUComputePipeline;
    advancePipeline: GPUComputePipeline;
    velocityPipeline: GPUComputePipeline;
    writebackPipeline: GPUComputePipeline;
    clearColorPipeline: GPUComputePipeline;
    countBodyConstraintsPipeline: GPUComputePipeline;
    scatterBodyConstraintsPipeline: GPUComputePipeline;
    buildAdjacencyPipeline: GPUComputePipeline;
    graphColorPipeline: GPUComputePipeline;
    countColorsPipeline: GPUComputePipeline;
    prefixSumColorsPipeline: GPUComputePipeline;
    sortBodiesPipeline: GPUComputePipeline;
    primalPipeline: GPUComputePipeline;
    advanceColorPipeline: GPUComputePipeline;
    resetColorPipeline: GPUComputePipeline;
    syncBodyColsPipeline: GPUComputePipeline;
    prepareIndirectPipeline: GPUComputePipeline;
    prepareIndirectBindGroup: Binding;
    packPipeline: GPUComputePipeline;
    bodyBuffer: GBuf;
    bodyBufferPrev: GBuf;
    bodyColsBuffer: GBuf;
    constraintsBuffer: GBuf;
    prevConstraintsBuffer: GBuf;
    rebuildParamsBuffer: GPUBuffer;
    warmstartBuffer: GBuf;
    solverStateBuffer: GBuf;
    jointsBuffer: GPUBuffer;
    jointSlot: { buffer: GPUBuffer; capacity: number };
    paramsBuffer: GPUBuffer;
    csrCountsBuffer: GBuf;
    indirectBuffer: GPUBuffer;
    csrPrefixSum: PrefixSumState;
    unpackTransformBuffer: GBuf;
    syncTransformsPipeline: GPUComputePipeline;
    syncTransformsBindGroup: Binding;
    compactPipeline: GPUComputePipeline;
    compactBindGroup: Binding;
    compactBuffer: GBuf;
    compactParamsBuffer: GPUBuffer;
    emitContactsPipeline: GPUComputePipeline;
    emitContactsBindGroup: Binding;
    contactsBuffer: GPUBuffer;
    contactScratch: Uint32Array;
    contactScratchCount: number;
    contactScratchOverflow: number;
    sizesBuffer: GBuf;
    shapesBuffer: GBuf;
    bodyPropsBuffer: GBuf;
    eidsBuffer: GBuf;
    packParamsBuffer: GPUBuffer;
    solverBindGroup: Binding;
    narrowBindGroup: Binding;
    rebuildBindGroup: Binding;
    packBindGroup: Binding;
    hullDataBuffer: { buffer: GPUBuffer };
    hullIdsBuffer: GBuf;
    forceBuffer: GBuf;
    paramsData: ArrayBuffer;
    paramsView: DataView;
    physicsActive: boolean;
    params: SolverParams;
    bodyEids: number[];
    jointCount: number;
    jointsNeedUpload: boolean;
    pendingChanges: Int32Array;
    pendingChangeCount: number;
    cachedCapacity: number;
    profile: ProfileState | null;
    debugReadbackData: Uint32Array;
    transformReadbackData: Float32Array;
    readbackStaging: GPUBuffer;
    readbackPending: boolean;
    readbackReady: boolean;
    readbackTick: number;
    readbackGeneration: number;
    readbackBodyCount: number;
    lastSyncTick: number;
    bodyGeneration: number;
    characterSweepPipeline: GPUComputePipeline;
    characterApplyPipeline: GPUComputePipeline;
    characterSweepBindGroup: Binding;
    characterBuffer: GPUBuffer;
    characterIndicesBuffer: GPUBuffer;
    characterParamsBuffer: GPUBuffer;
    characterGroundBuffer: GPUBuffer;
    characterCount: number;
    characters: number[];
    characterVerticalVelocity: Map<number, number>;
    characterCoyoteTimers: Map<number, number>;
    characterReadbackStaging: GPUBuffer;
    characterReadbackPending: boolean;
}

export { BODY_STRUCT_WGSL, QUAT_WGSL, SHAPE_CONSTS_WGSL } from "./lbvh";
export type { PhysicsLBVH } from "./lbvh";
