// Tumble's extension surface for escape-hatch consumers: the CPU pose-compose helper plus the engine's
// own public authoring API. `Tumble` + `TumblePlugin` ride the main barrel; driving `Tumble.world` (or a
// consumer-owned `World`) past the atomic `PhysicsBackend` core needs the engine's free functions — the
// shape builders (`makeBoxHull`, `createHull`, `createMesh`…), the `BodyType`/joint configs, the debug
// draw walk (`DebugDraw` / `defaultDebugDraw`), the world-state hash (`hashWorldState`) — none of which
// live on a `World` instance. This subpath mirrors the engine barrel's already-curated public API so a gym
// sample port or custom tooling authors a scene the same way the engine's own samples do, without reaching
// into `engine/` internals.
//
// This is an explicit re-export, NOT `export * from "./engine"`, for one reason: the engine barrel exports
// `shutdown`, which terminates the process-singleton kernel's worker pool that TumblePlugin shares — a
// consumer calling it would silently degrade every physics scene to single-thread. `shutdown` is engine-
// owned lifecycle, deliberately withheld here (`init` / `threads` stay — a standalone author legitimately
// boots + introspects the kernel). Mirror the engine barrel here whenever it gains a public symbol.

export { nlerpShortest } from "./compose";
export {
    type AABB,
    type BaseJointConfig,
    Body,
    type BodyCastHit,
    type BodyDef,
    type BodyEvents,
    type BodyMoveEvent,
    type BodyPlane,
    BodyType,
    type Capacity,
    type Capsule,
    type CastCallback,
    type CastHit,
    type CollisionPlane,
    type CompoundCapsuleDef,
    type CompoundData,
    type CompoundDef,
    type CompoundHullDef,
    type CompoundMeshDef,
    type CompoundSphereDef,
    Contact,
    type ContactData,
    type ContactEvents,
    type ContactHitEvent,
    type ContactTouchEvent,
    type Counters,
    clipVector,
    createBoxMesh,
    createCompound,
    createCone,
    createCylinder,
    createGrid,
    createGridMesh,
    createHeightField,
    createHollowBoxMesh,
    createHull,
    createMesh,
    createRock,
    createTorusMesh,
    createWave,
    createWaveMesh,
    DebugColor,
    type DebugDraw,
    DistanceJoint,
    type DistanceJointConfig,
    defaultBodyDef,
    defaultDebugDraw,
    defaultFilter,
    defaultQueryFilter,
    defaultShapeDef,
    defaultSurfaceMaterial,
    defaultWorldDef,
    type Filter,
    HEIGHT_FIELD_HOLE,
    type HeightFieldData,
    type HeightFieldDef,
    type HullData,
    hashWorldState,
    type InitOptions,
    init,
    Joint,
    type JointEvent,
    JointType,
    type Manifold,
    type ManifoldPoint,
    type MassData,
    type Mat3,
    type Mesh,
    type MeshData,
    type MeshDef,
    MeshEdgeFlags,
    type MotionLocks,
    MotorJoint,
    type MotorJointConfig,
    type MoverFilterCallback,
    makeBoxHull,
    makeCubeHull,
    makeOffsetBoxHull,
    makeTransformedBoxHull,
    type OverlapCallback,
    ParallelJoint,
    type ParallelJointConfig,
    type PlaneResult,
    type PlaneResultCallback,
    type PlaneSolverResult,
    type Pos,
    PrismaticJoint,
    type PrismaticJointConfig,
    type Profile,
    type Quat,
    type QueryFilter,
    type RayResult,
    RevoluteJoint,
    type RevoluteJointConfig,
    type SensorEvents,
    type SensorTouchEvent,
    Shape,
    type ShapeDef,
    type ShapeProxy,
    ShapeType,
    type Sphere,
    SphericalJoint,
    type SphericalJointConfig,
    type SurfaceMaterial,
    solvePlanes,
    type Transform,
    type TreeStats,
    threads,
    type Vec3,
    WeldJoint,
    type WeldJointConfig,
    WheelJoint,
    type WheelJointConfig,
    World,
    type WorldDef,
    type WorldState,
    type WorldTransform,
} from "./engine";
