/** GENERATED by scripts/generate/device-tiers.ts — do not hand-edit. */
export const DEVICE_TIER_CONTEXT = {
    standard: {
        tier: "gpu",
        required: ["BVH", "Fog", "Glaze", "Mirror", "Render", "Sear"],
        optional: ["Part", "Physics", "Slab", "Transforms"],
        undeclared: ["Audio", "Character", "Input", "Player"],
    },
    extras: {
        tier: "gpu",
        required: ["Profile"],
        optional: ["Cells", "Gltf", "Lines", "Outline", "Skin", "Sky", "Sprite", "Text"],
        undeclared: ["Orbit", "OrbitOverlay"],
    },
} as const;
