/** GENERATED by scripts/generate/device-tiers.ts — do not hand-edit. */
export const DEVICE_TIER_CONTEXT = {
    core: {
        tier: "gpu",
        required: ["Render"],
        optional: [],
        undeclared: ["BrowserInput", "Input"],
    },
    standard: {
        tier: "gpu",
        required: ["BVH", "Glaze", "Mirror", "Sear"],
        optional: ["Part", "Physics", "Slab", "Transforms"],
        undeclared: ["Audio", "Character"],
    },
    extras: {
        tier: "gpu",
        required: ["Fog", "Profile"],
        optional: ["Cells", "Gltf", "Lines", "Outline", "Skin", "Sky", "Sprite", "Text"],
        undeclared: ["Orbit", "OrbitOverlay", "PhysicsProfile", "Player"],
    },
} as const;
