#![cfg_attr(windows, windows_subsystem = "windows")]

// Backend by build mode (not by platform). `portable` ships the Chromium runtime (CEF) and runs
// anywhere; the default uses the platform's system webview via wry (WebView2 on Windows, WKWebView
// on macOS, WebKitGTK on Linux). A system-webview build is small but depends on the host — and
// WebKitGTK has no usable WebGPU, so a default Linux build reaches the engine's diagnostic tier at
// launch. macOS WKWebView lacks subgroup support, so a physics app there needs `--portable`.
#[cfg(feature = "portable")]
mod cef_backend;
#[cfg(all(feature = "portable", target_os = "macos"))]
mod mac;
#[cfg(not(feature = "portable"))]
mod wry_backend;

use std::borrow::Cow;
use std::path::PathBuf;

#[cfg(not(feature = "portable"))]
pub(crate) const BG: (u8, u8, u8) = (14, 13, 12); // #0e0d0c

#[cfg(windows)]
fn local_app_data() -> PathBuf {
    std::env::var("LOCALAPPDATA")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let home = std::env::var("USERPROFILE").unwrap_or_else(|_| ".".into());
            PathBuf::from(home).join("AppData").join("Local")
        })
}

pub(crate) fn cache_dir(name: &str) -> PathBuf {
    #[cfg(windows)]
    {
        local_app_data().join("shallot").join(name)
    }
    #[cfg(target_os = "macos")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home)
            .join("Library")
            .join("Application Support")
            .join("shallot")
            .join(name)
    }
    #[cfg(target_os = "linux")]
    {
        let base = std::env::var("XDG_DATA_HOME").unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
            format!("{}/.local/share", home)
        });
        PathBuf::from(base).join("shallot").join(name)
    }
}

// generated by build.rs from SHALLOT_DIST: `pub static ASSETS: &[(&str, &[u8])]`. Always present —
// empty `&[]` when SHALLOT_DIST is unset — so both profiles share one resolution path (see
// `resolve_asset`). The release exe carries no appended overlay and never extracts itself at
// runtime; both are dropper signatures that trip Windows Defender on unsigned builds (build.rs).
mod embedded {
    include!(concat!(env!("OUT_DIR"), "/assets.rs"));
}

/// Directory holding the on-disk dist/ the exe serves when its embedded `ASSETS` is empty. On
/// macOS the exe lives in `<app>.app/Contents/MacOS/`, where web assets can't sit beside it
/// (codesign treats everything under MacOS/ as nested code and rejects the bundle), so the bundle
/// stages dist/ in the sibling `Contents/Resources/`. Elsewhere it's the exe's sibling `dist/`.
/// Compiled in both profiles: debug always reads disk; release reads disk only when nothing is
/// baked in (the prebuilt-shell fallback).
fn dist_dir() -> PathBuf {
    let exe = std::env::current_exe().expect("failed to get exe path");
    let dir = exe.parent().expect("exe has no parent");
    #[cfg(target_os = "macos")]
    {
        dir.parent().expect("MacOS has no parent").join("Resources").join("dist")
    }
    #[cfg(not(target_os = "macos"))]
    {
        dir.join("dist")
    }
}

/// Where a web-asset request resolves to. cfg-independent so both the debug and release profiles
/// share one resolution path: a debug `cargo test` (where the release `#[cfg]` branch is compiled
/// out) exercises the same empty-list → disk fallback a release binary with no baked assets takes.
#[derive(Debug)]
pub(crate) enum AssetResolution<'a> {
    /// Serve these bytes baked into the binary by build.rs.
    Embedded(&'a [u8]),
    /// The embedded list is empty; read `path` from the sibling dist/ on disk.
    Disk,
}

/// Pure choice over (embedded asset list, requested path):
/// - empty list → `Disk` (serve the sibling dist/ on disk, exactly as debug does — the prebuilt
///   shell with no baked assets falls back to disk rather than rendering blank);
/// - non-empty list + hit → `Embedded(bytes)`;
/// - non-empty list + miss → `None` (404): a binary that carries its assets does not silently fall
///   through to disk for a path it doesn't hold, which would mask a stale dist/ behind a fresh embed.
pub(crate) fn resolve_asset<'a>(
    assets: &'a [(&'a str, &'a [u8])],
    path: &str,
) -> Option<AssetResolution<'a>> {
    if assets.is_empty() {
        Some(AssetResolution::Disk)
    } else {
        assets
            .iter()
            .find(|entry| entry.0 == path)
            .map(|entry| AssetResolution::Embedded(entry.1))
    }
}

/// Web asset bytes for a request path (e.g. `"index.html"`). Resolution is shared with the
/// release profile via `resolve_asset`: baked-in bytes when present, the sibling dist/ on disk
/// when the embedded list is empty (the prebuilt-shell fallback), 404 on a miss against a
/// non-empty list. Either way the exe never reads or extracts its own image at runtime.
pub(crate) fn asset(path: &str) -> Option<Cow<'static, [u8]>> {
    match resolve_asset(embedded::ASSETS, path) {
        Some(AssetResolution::Embedded(bytes)) => Some(Cow::Borrowed(bytes)),
        Some(AssetResolution::Disk) => std::fs::read(dist_dir().join(path)).ok().map(Cow::Owned),
        None => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_embedded_list_falls_back_to_disk() {
        let assets: &[(&str, &[u8])] = &[];
        assert!(
            matches!(resolve_asset(assets, "index.html"), Some(AssetResolution::Disk)),
            "empty embedded list must resolve to disk, not None"
        );
    }

    #[test]
    fn non_empty_list_hit_serves_embedded_bytes() {
        let bytes: &[u8] = b"<html></html>";
        let assets: &[(&str, &[u8])] = &[("index.html", bytes)];
        match resolve_asset(assets, "index.html") {
            Some(AssetResolution::Embedded(b)) => assert_eq!(b, bytes),
            other => panic!("expected Embedded, got {other:?}"),
        }
    }

    #[test]
    fn non_empty_list_miss_returns_none_no_disk_fallback_for_a_baked_binary() {
        // A binary that bakes its assets does not fall through to disk for a path it doesn't carry
        // — that would mask a stale dist/ behind a fresh embed. Miss is a 404.
        let assets: &[(&str, &[u8])] = &[("index.html", b"<html></html>")];
        assert!(matches!(resolve_asset(assets, "missing.js"), None));
    }
}

pub(crate) fn app_name() -> String {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.file_stem().map(|s| s.to_string_lossy().into_owned()))
        .unwrap_or_else(|| "shallot".into())
}

pub(crate) fn content_type(path: &str) -> &'static str {
    if path.ends_with(".html") {
        "text/html"
    } else if path.ends_with(".js") {
        "text/javascript"
    } else if path.ends_with(".css") {
        "text/css"
    } else if path.ends_with(".wasm") {
        "application/wasm"
    } else if path.ends_with(".json") {
        "application/json"
    } else if path.ends_with(".svg") {
        "image/svg+xml"
    } else if path.ends_with(".png") {
        "image/png"
    } else if path.ends_with(".jpg") || path.ends_with(".jpeg") {
        "image/jpeg"
    } else if path.ends_with(".ico") {
        "image/x-icon"
    } else if path.ends_with(".woff2") {
        "font/woff2"
    } else if path.ends_with(".woff") {
        "font/woff"
    } else if path.ends_with(".glb") {
        "model/gltf-binary"
    } else {
        "application/octet-stream"
    }
}

fn main() {
    #[cfg(feature = "portable")]
    cef_backend::run();
    #[cfg(not(feature = "portable"))]
    wry_backend::run();
}
