#![cfg_attr(windows, windows_subsystem = "windows")]

// Backend by build mode (not by platform). `portable` ships the Chromium runtime (CEF) and runs
// anywhere; the default uses the platform's system webview via wry (WebView2 on Windows, WKWebView
// on macOS, WebKitGTK on Linux). A system-webview build is small but depends on the host — and
// WebKitGTK has no usable WebGPU, so a default Linux build reaches the engine's diagnostic tier at
// launch. macOS WKWebView lacks subgroup support, so a physics app there needs `--portable`.
#[cfg(feature = "portable")]
mod cef_backend;
#[cfg(all(feature = "portable", target_os = "macos"))]
mod mac;
#[cfg(not(feature = "portable"))]
mod wry_backend;

use std::borrow::Cow;
use std::path::PathBuf;

#[cfg(not(feature = "portable"))]
pub(crate) const BG: (u8, u8, u8) = (14, 13, 12); // #0e0d0c

#[cfg(windows)]
fn local_app_data() -> PathBuf {
    std::env::var("LOCALAPPDATA")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            let home = std::env::var("USERPROFILE").unwrap_or_else(|_| ".".into());
            PathBuf::from(home).join("AppData").join("Local")
        })
}

pub(crate) fn cache_dir(name: &str) -> PathBuf {
    #[cfg(windows)]
    {
        local_app_data().join("shallot").join(name)
    }
    #[cfg(target_os = "macos")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
        PathBuf::from(home)
            .join("Library")
            .join("Application Support")
            .join("shallot")
            .join(name)
    }
    #[cfg(target_os = "linux")]
    {
        let base = std::env::var("XDG_DATA_HOME").unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
            format!("{}/.local/share", home)
        });
        PathBuf::from(base).join("shallot").join(name)
    }
}

#[cfg(not(debug_assertions))]
mod embedded {
    // generated by build.rs from SHALLOT_DIST: `pub static ASSETS: &[(&str, &[u8])]`
    include!(concat!(env!("OUT_DIR"), "/assets.rs"));
}

#[cfg(debug_assertions)]
fn dist_dir() -> PathBuf {
    let exe = std::env::current_exe().expect("failed to get exe path");
    let dir = exe.parent().expect("exe has no parent");
    // On macOS the exe lives in `<app>.app/Contents/MacOS/`, where web assets can't sit beside it
    // (codesign treats everything under MacOS/ as nested code and rejects the bundle), so the debug
    // bundle stages dist/ in the sibling `Contents/Resources/`. Elsewhere it's the exe's sibling.
    #[cfg(target_os = "macos")]
    {
        dir.parent().expect("MacOS has no parent").join("Resources").join("dist")
    }
    #[cfg(not(target_os = "macos"))]
    {
        dir.join("dist")
    }
}

/// Web asset bytes for a request path (e.g. `"index.html"`). Release reads from the assets baked
/// into the binary by build.rs; debug reads dist/ from disk so asset edits show without a
/// recompile. Either way the exe never reads or extracts its own image at runtime.
pub(crate) fn asset(path: &str) -> Option<Cow<'static, [u8]>> {
    #[cfg(debug_assertions)]
    {
        std::fs::read(dist_dir().join(path)).ok().map(Cow::Owned)
    }
    #[cfg(not(debug_assertions))]
    {
        embedded::ASSETS
            .iter()
            .find(|entry| entry.0 == path)
            .map(|entry| Cow::Borrowed(entry.1))
    }
}

pub(crate) fn app_name() -> String {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.file_stem().map(|s| s.to_string_lossy().into_owned()))
        .unwrap_or_else(|| "shallot".into())
}

pub(crate) fn content_type(path: &str) -> &'static str {
    if path.ends_with(".html") {
        "text/html"
    } else if path.ends_with(".js") {
        "text/javascript"
    } else if path.ends_with(".css") {
        "text/css"
    } else if path.ends_with(".wasm") {
        "application/wasm"
    } else if path.ends_with(".json") {
        "application/json"
    } else if path.ends_with(".svg") {
        "image/svg+xml"
    } else if path.ends_with(".png") {
        "image/png"
    } else if path.ends_with(".jpg") || path.ends_with(".jpeg") {
        "image/jpeg"
    } else if path.ends_with(".ico") {
        "image/x-icon"
    } else if path.ends_with(".woff2") {
        "font/woff2"
    } else if path.ends_with(".woff") {
        "font/woff"
    } else if path.ends_with(".glb") {
        "model/gltf-binary"
    } else {
        "application/octet-stream"
    }
}

fn main() {
    #[cfg(feature = "portable")]
    cef_backend::run();
    #[cfg(not(feature = "portable"))]
    wry_backend::run();
}
