// Stage 13 batch 2 (character mover) bit-exact gold gate. Asserts the plane solver (solvePlanes), the
// velocity clip (clipVector), and the per-shape mover-collide functions (collideMoverAndSphere/Capsule/
// Hull/Mesh/HeightField/Compound) match the Box3D C reference (scalar + force-overflow build) bit-for-
// bit, over the vectors in mover.gold.json (generated by fixtures/mover_gold.c, regenerate via
// scripts/gen-mover-gold.ts). Equality, not tolerance (the README).

import { describe, expect, test } from "bun:test";
import { type CompoundData, collideMoverAndCompound, createCompound } from "./compound";
import {
    type Capsule,
    collideMoverAndCapsule,
    collideMoverAndSphere,
    type Sphere,
} from "./geometry";
import { collideMoverAndHeightField, createGrid } from "./heightfield";
import { collideMoverAndHull, createHull, type HullData, makeBoxHull } from "./hull";
import { type Transform, type Vec3, xf } from "./math";
import { collideMoverAndMesh, createGridMesh, type Mesh } from "./mesh";
import { type CollisionPlane, clipVector, type PlaneResult, solvePlanes } from "./mover";
import gold from "./mover.gold.json";
import { defaultSurfaceMaterial } from "./types";

const dv = new DataView(new ArrayBuffer(4));
function fromBits(hex: string): number {
    dv.setUint32(0, Number.parseInt(hex, 16));
    return dv.getFloat32(0);
}
function bits(f: number): string {
    dv.setFloat32(0, f);
    return dv.getUint32(0).toString(16).padStart(8, "0");
}
function bitEqual(got: number, want: string, label: string): void {
    const w = fromBits(want);
    if (!Object.is(got, w)) {
        throw new Error(`${label}: got 0x${bits(got)} (${got}), want ${want} (${w})`);
    }
}
const v = (x: number, y: number, z: number): Vec3 => ({ x, y, z });
const vecFromHex = (a: string[]): Vec3 => v(fromBits(a[0]), fromBits(a[1]), fromBits(a[2]));
function vecEqual(got: Vec3, want: string[], label: string): void {
    bitEqual(got.x, want[0], `${label}.x`);
    bitEqual(got.y, want[1], `${label}.y`);
    bitEqual(got.z, want[2], `${label}.z`);
}

type PlaneJson = {
    normal: string[];
    offset: string;
    pushLimit: string;
    push: string;
    clipVelocity: boolean;
};

// Reconstruct a CollisionPlane from its gold entry. b3SolvePlanes resets push at entry, so the gold's
// (post-run) push is only load-bearing for clipVector.
const collisionPlane = (p: PlaneJson): CollisionPlane => ({
    plane: { normal: vecFromHex(p.normal), offset: fromBits(p.offset) },
    pushLimit: fromBits(p.pushLimit),
    push: fromBits(p.push),
    clipVelocity: p.clipVelocity,
});

// Compare a returned plane list against gold's count + per-plane {normal, offset, point}.
function planesEqual(
    got: PlaneResult[],
    want: { count: number; planes: { normal: string[]; offset: string; point: string[] }[] },
    name: string,
): void {
    expect(got.length).toBe(want.count);
    for (let i = 0; i < want.count; ++i) {
        vecEqual(got[i].plane.normal, want.planes[i].normal, `${name}[${i}].normal`);
        bitEqual(got[i].plane.offset, want.planes[i].offset, `${name}[${i}].offset`);
        vecEqual(got[i].point, want.planes[i].point, `${name}[${i}].point`);
    }
}

const moverFrom = (m: { center1: string[]; center2: string[]; radius: string }): Capsule => ({
    center1: vecFromHex(m.center1),
    center2: vecFromHex(m.center2),
    radius: fromBits(m.radius),
});

describe("solvePlanes bit-exact vs C reference", () => {
    for (const g of gold.solvePlanes) {
        test(g.name, () => {
            const planes = g.planes.map((p) => collisionPlane(p as PlaneJson));
            const result = solvePlanes(vecFromHex(g.target), planes, planes.length);
            vecEqual(result.delta, g.delta, `${g.name} delta`);
            expect(result.iterationCount).toBe(g.iterationCount);
        });
    }
});

describe("clipVector bit-exact vs C reference", () => {
    for (const g of gold.clipVector) {
        test(g.name, () => {
            const planes = g.planes.map((p) => collisionPlane(p as PlaneJson));
            const out = clipVector(vecFromHex(g.vector), planes, planes.length);
            vecEqual(out, g.out, `${g.name} out`);
        });
    }
});

describe("collideMoverAndSphere bit-exact vs C reference", () => {
    for (const g of gold.sphere) {
        test(g.name, () => {
            const sphere: Sphere = {
                center: vecFromHex(g.center as string[]),
                radius: fromBits(g.radius),
            };
            const p = collideMoverAndSphere(sphere, moverFrom(g.mover));
            planesEqual(p ? [p] : [], g, g.name);
        });
    }
});

describe("collideMoverAndCapsule bit-exact vs C reference", () => {
    for (const g of gold.capsule) {
        test(g.name, () => {
            const shape: Capsule = {
                center1: vecFromHex(g.center1 as string[]),
                center2: vecFromHex(g.center2 as string[]),
                radius: fromBits(g.radius),
            };
            const p = collideMoverAndCapsule(shape, moverFrom(g.mover));
            planesEqual(p ? [p] : [], g, g.name);
        });
    }
});

// The box hull, baked identically to fixtures/mover_gold.c's b3CreateHull(boxCorners, 8, 8).
const boxCorners: Vec3[] = [
    v(-0.5, -0.5, -0.5),
    v(0.5, -0.5, -0.5),
    v(0.5, 0.5, -0.5),
    v(-0.5, 0.5, -0.5),
    v(-0.5, -0.5, 0.5),
    v(0.5, -0.5, 0.5),
    v(0.5, 0.5, 0.5),
    v(-0.5, 0.5, 0.5),
];
const box = createHull(boxCorners, 8) as HullData;

describe("collideMoverAndHull bit-exact vs C reference", () => {
    for (const g of gold.hull) {
        test(g.name, () => {
            const p = collideMoverAndHull(box, moverFrom(g.mover));
            planesEqual(p ? [p] : [], g, g.name);
        });
    }
});

// Mesh / height field / compound reconstructed with the same builders the C gold used.
const gridMesh: Mesh = { data: createGridMesh(4, 4, 1, 0, true), scale: v(1, 1, 1) };
const gridField = createGrid(8, 8, v(1, 1, 1), false);
const slab = makeBoxHull(0.5, 0.5, 0.5);
const cmat = defaultSurfaceMaterial();
const identityAt = (x: number, y: number, z: number): Transform => ({
    p: v(x, y, z),
    q: xf.identity().q,
});
const compound = createCompound({
    hulls: [
        { hull: slab, transform: identityAt(-1, 0, 0), material: cmat },
        { hull: slab, transform: identityAt(1, 0, 0), material: cmat },
    ],
}) as CompoundData;

describe("collideMoverAndMesh bit-exact vs C reference", () => {
    for (const g of gold.mesh) {
        test(g.name, () => {
            planesEqual(collideMoverAndMesh(gridMesh, 16, moverFrom(g.mover)), g, g.name);
        });
    }
});

describe("collideMoverAndHeightField bit-exact vs C reference", () => {
    for (const g of gold.height) {
        test(g.name, () => {
            planesEqual(collideMoverAndHeightField(gridField, 16, moverFrom(g.mover)), g, g.name);
        });
    }
});

describe("collideMoverAndCompound bit-exact vs C reference", () => {
    for (const g of gold.compound) {
        test(g.name, () => {
            planesEqual(collideMoverAndCompound(compound, 16, moverFrom(g.mover)), g, g.name);
        });
    }
});
