// Stage 13 (queries) bit-exact gold gate. Asserts the per-shape ray casts, shape casts, and overlap
// tests match the Box3D C reference (scalar + force-overflow build) bit-for-bit, over the vectors in
// query.gold.json (generated by fixtures/query_gold.c, regenerate via scripts/gen-query-gold.ts).
// These are the genuinely new f32 code paths of the batch — rayCastSphere/Capsule/Hull — plus the
// GJK-backed shape-cast/overlap wrappers. Equality, not tolerance (the README).

import { describe, expect, test } from "bun:test";
import {
    type CompoundData,
    createCompound,
    overlapCompound,
    rayCastCompound,
    shapeCastCompound,
} from "./compound";
import type { CastOutput, ShapeProxy } from "./distance";
import {
    type Capsule,
    overlapSphere,
    rayCastCapsule,
    rayCastSphere,
    type Sphere,
    shapeCastSphere,
} from "./geometry";
import {
    createGrid,
    overlapHeightField,
    rayCastHeightField,
    shapeCastHeightField,
} from "./heightfield";
import {
    createHull,
    type HullData,
    makeBoxHull,
    overlapHull,
    rayCastHull,
    shapeCastHull,
} from "./hull";
import { type Transform, type Vec3, xf } from "./math";
import { createGridMesh, type Mesh, overlapMesh, rayCastMesh, shapeCastMesh } from "./mesh";
import gold from "./query.gold.json";
import { defaultSurfaceMaterial } from "./types";

const dv = new DataView(new ArrayBuffer(4));
function fromBits(hex: string): number {
    dv.setUint32(0, Number.parseInt(hex, 16));
    return dv.getFloat32(0);
}
function bits(f: number): string {
    dv.setFloat32(0, f);
    return dv.getUint32(0).toString(16).padStart(8, "0");
}
function bitEqual(got: number, want: string, label: string): void {
    const w = fromBits(want);
    if (!Object.is(got, w)) {
        throw new Error(`${label}: got 0x${bits(got)} (${got}), want ${want} (${w})`);
    }
}
const v = (x: number, y: number, z: number): Vec3 => ({ x, y, z });
const vecFromHex = (a: string[]): Vec3 => v(fromBits(a[0]), fromBits(a[1]), fromBits(a[2]));
function vecEqual(got: Vec3, want: string[], label: string): void {
    bitEqual(got.x, want[0], `${label}.x`);
    bitEqual(got.y, want[1], `${label}.y`);
    bitEqual(got.z, want[2], `${label}.z`);
}
function outEqual(
    out: CastOutput,
    want: { hit: boolean; fraction: string; point: string[]; normal: string[] },
    name: string,
): void {
    expect(out.hit).toBe(want.hit);
    bitEqual(out.fraction, want.fraction, `${name} fraction`);
    vecEqual(out.point, want.point, `${name} point`);
    vecEqual(out.normal, want.normal, `${name} normal`);
}

// The cube hull, baked identically to fixtures/query_gold.c's b3CreateHull(cubeCorners, 8, 8).
const cubeCorners: Vec3[] = [
    v(-1, -1, -1),
    v(1, -1, -1),
    v(1, 1, -1),
    v(-1, 1, -1),
    v(-1, -1, 1),
    v(1, -1, 1),
    v(1, 1, 1),
    v(-1, 1, 1),
];
const cube = createHull(cubeCorners, 8) as HullData;

// The proxy point cloud is a single point at the origin (pt0/sphere), mirroring query_gold.c.
const originProxy = (radiusHex: string): ShapeProxy => ({
    points: [v(0, 0, 0)],
    count: 1,
    radius: fromBits(radiusHex),
});

const ray = (origin: string[], translation: string[], maxFraction: string) => ({
    origin: vecFromHex(origin),
    translation: vecFromHex(translation),
    maxFraction: fromBits(maxFraction),
});

describe("rayCastSphere bit-exact vs C reference", () => {
    for (const g of gold.raySphere) {
        test(g.name, () => {
            const sphere: Sphere = {
                center: vecFromHex(g.center as string[]),
                radius: fromBits(g.radius as string),
            };
            outEqual(
                rayCastSphere(sphere, ray(g.origin, g.translation, g.maxFraction)),
                g.out,
                g.name,
            );
        });
    }
});

describe("rayCastCapsule bit-exact vs C reference", () => {
    for (const g of gold.rayCapsule) {
        test(g.name, () => {
            const capsule: Capsule = {
                center1: vecFromHex(g.center1),
                center2: vecFromHex(g.center2),
                radius: fromBits(g.radius),
            };
            outEqual(
                rayCastCapsule(capsule, ray(g.origin, g.translation, g.maxFraction)),
                g.out,
                g.name,
            );
        });
    }
});

describe("rayCastHull bit-exact vs C reference", () => {
    for (const g of gold.rayHull) {
        test(g.name, () => {
            outEqual(rayCastHull(cube, ray(g.origin, g.translation, g.maxFraction)), g.out, g.name);
        });
    }
});

describe("shapeCast bit-exact vs C reference", () => {
    for (const g of gold.shapeCast) {
        test(g.name, () => {
            const proxy = originProxy(g.proxyRadius);
            const input = {
                proxy,
                translation: vecFromHex(g.translation),
                maxFraction: fromBits(g.maxFraction),
                canEncroach: g.canEncroach,
            };
            const out =
                g.shape === "cube"
                    ? shapeCastHull(cube, input)
                    : shapeCastSphere(
                          {
                              center: vecFromHex(g.center as string[]),
                              radius: fromBits(g.radius as string),
                          },
                          input,
                      );
            expect(out.hit).toBe(g.out.hit);
            bitEqual(out.fraction, g.out.fraction, `${g.name} fraction`);
            vecEqual(out.point, g.out.point, `${g.name} point`);
            vecEqual(out.normal, g.out.normal, `${g.name} normal`);
        });
    }
});

describe("overlap bit-exact vs C reference", () => {
    for (const g of gold.overlap) {
        test(g.name, () => {
            const proxy = originProxy(g.proxyRadius);
            const transform: Transform = { p: vecFromHex(g.xfp), q: xf.identity().q };
            const result =
                g.shape === "cube"
                    ? overlapHull(cube, transform, proxy)
                    : overlapSphere(
                          {
                              center: vecFromHex(g.center as string[]),
                              radius: fromBits(g.radius as string),
                          },
                          transform,
                          proxy,
                      );
            expect(result).toBe(g.out);
        });
    }
});

// The mesh/height/compound query paths carry the extra output fields; assert them too.
function outFullEqual(
    out: CastOutput,
    want: {
        hit: boolean;
        fraction: string;
        point: string[];
        normal: string[];
        triangleIndex: number;
        childIndex: number;
        materialIndex: number;
    },
    name: string,
): void {
    outEqual(out, want, name);
    expect(out.triangleIndex).toBe(want.triangleIndex);
    expect(out.childIndex).toBe(want.childIndex);
    expect(out.materialIndex).toBe(want.materialIndex);
}

const proxyFrom = (point: string[], radius: string): ShapeProxy => ({
    points: [vecFromHex(point)],
    count: 1,
    radius: fromBits(radius),
});
const castInput = (proxy: ShapeProxy, translation: string[], maxFraction: string) => ({
    proxy,
    translation: vecFromHex(translation),
    maxFraction: fromBits(maxFraction),
    canEncroach: false,
});
const identityAt = (p: string[]): Transform => ({ p: vecFromHex(p), q: xf.identity().q });

// Geometry reconstructed with the exact builders fixtures/query_gold.c uses; construction is proven
// bit-exact by the geometry gold, so this reuses it and validates only the query paths.
const gridMesh: Mesh = { data: createGridMesh(4, 4, 1, 0, true), scale: v(1, 1, 1) };
const gridField = createGrid(8, 8, v(1, 1, 1), false);
const slab = makeBoxHull(1.5, 0.25, 1.5);
const cmat = defaultSurfaceMaterial();
const compound = createCompound({
    hulls: [
        { hull: slab, transform: identityAt(["3fb33333", "be800000", "00000000"]), material: cmat },
        { hull: slab, transform: identityAt(["bfb33333", "be800000", "00000000"]), material: cmat },
    ],
}) as CompoundData;

describe("rayCastMesh bit-exact vs C reference", () => {
    for (const g of gold.rayMesh) {
        test(g.name, () => {
            outFullEqual(
                rayCastMesh(gridMesh, ray(g.origin, g.translation, g.maxFraction)),
                g.out,
                g.name,
            );
        });
    }
});

describe("shapeCastMesh bit-exact vs C reference", () => {
    for (const g of gold.shapeCastMesh) {
        test(g.name, () => {
            const input = castInput(
                proxyFrom(g.proxyPoint, g.proxyRadius),
                g.translation,
                g.maxFraction,
            );
            outFullEqual(shapeCastMesh(gridMesh, input), g.out, g.name);
        });
    }
});

describe("overlapMesh bit-exact vs C reference", () => {
    for (const g of gold.overlapMesh) {
        test(g.name, () => {
            const proxy = proxyFrom(g.proxyPoint, g.proxyRadius);
            expect(overlapMesh(gridMesh, identityAt(g.xfp), proxy)).toBe(g.out);
        });
    }
});

describe("rayCastHeightField bit-exact vs C reference", () => {
    for (const g of gold.rayHeight) {
        test(g.name, () => {
            outFullEqual(
                rayCastHeightField(gridField, ray(g.origin, g.translation, g.maxFraction)),
                g.out,
                g.name,
            );
        });
    }
});

describe("shapeCastHeightField bit-exact vs C reference", () => {
    for (const g of gold.shapeCastHeight) {
        test(g.name, () => {
            const input = castInput(
                proxyFrom(g.proxyPoint, g.proxyRadius),
                g.translation,
                g.maxFraction,
            );
            outFullEqual(shapeCastHeightField(gridField, input), g.out, g.name);
        });
    }
});

describe("overlapHeightField bit-exact vs C reference", () => {
    for (const g of gold.overlapHeight) {
        test(g.name, () => {
            const proxy = proxyFrom(g.proxyPoint, g.proxyRadius);
            expect(overlapHeightField(gridField, identityAt(g.xfp), proxy)).toBe(g.out);
        });
    }
});

describe("rayCastCompound bit-exact vs C reference", () => {
    for (const g of gold.rayCompound) {
        test(g.name, () => {
            outFullEqual(
                rayCastCompound(compound, ray(g.origin, g.translation, g.maxFraction)),
                g.out,
                g.name,
            );
        });
    }
});

describe("shapeCastCompound bit-exact vs C reference", () => {
    for (const g of gold.shapeCastCompound) {
        test(g.name, () => {
            const input = castInput(
                proxyFrom(g.proxyPoint, g.proxyRadius),
                g.translation,
                g.maxFraction,
            );
            outFullEqual(shapeCastCompound(compound, input), g.out, g.name);
        });
    }
});

describe("overlapCompound bit-exact vs C reference", () => {
    for (const g of gold.overlapCompound) {
        test(g.name, () => {
            const proxy = proxyFrom(g.proxyPoint, g.proxyRadius);
            expect(overlapCompound(compound, identityAt(g.xfp), proxy)).toBe(g.out);
        });
    }
});
