/// <reference types="@webgpu/types" />

export {
    type App,
    type AppConfig,
    createApp,
    type Loading,
    type MissingPluginDependency,
    mountOverlay,
    type Plugin,
    type PluginComposition,
    type PluginSwapResult,
    resolvePlugins,
    runApp,
    setDefaultLoading,
    setDefaultPlugins,
    swapPlugins,
    warmPlugins,
} from "./app";
export {
    and,
    type Component,
    component,
    composeGlobalTransform,
    entity,
    type FieldType,
    f16,
    f32,
    GlobalTransform,
    GpuTable,
    globalTransformTable,
    i32,
    not,
    or,
    type Resource,
    type ScalarField,
    type System,
    type TableUploadPath,
    Time,
    Transform,
    type TypedArray,
    u8,
    u16,
    u32,
    type Vector2Field,
    type Vector4Field,
    vec2,
    vec4,
    World,
} from "./ecs";
export {
    type BufferProbe,
    type BufferProbeOptions,
    checkStorageBinding,
    checkTextureLimits,
    checkTgsl,
    deviceLost,
    drainLog,
    type GpuLog,
    type LazyAlloc,
    now,
    PIPELINE_COMPILE_MEASURE_PREFIX,
    type ProbeEncode,
    precompile,
    precompileAll,
    precompileScope,
    probeBuffer,
    probeTexture,
    Runtime,
    readBinary,
    readFile,
    requestFrame,
    requestGPU,
    type ShaderArtifact,
    stampAdapter,
    type TextureProbe,
    type TextureProbeOptions,
    tgslCanary,
    UnsupportedError,
    validateGpu,
} from "./runtime";
export { resizeViewport, type Viewport, Viewports } from "./runtime/viewport";
export {
    clamp,
    composeMat4,
    decomposeMat4,
    eulerToQuat,
    invertMat4,
    lerp,
    linearToSrgb,
    lookAt,
    lookAtRotation,
    multiplyMat4,
    orthographic,
    perspective,
    qRotate,
    quatToEuler,
    type Ray,
    Registry,
    rotateQuatByEuler,
    slerp,
    srgbToLinear,
    unpackColor,
} from "./utils";
