import docs from "./fielddocs.json";

/**
 * per-component + per-field UI reference data, generated by the build (`scripts/fielddocs.ts` →
 * `fielddocs.json`). Keyed by kebab component name; `fields` by kebab field name — the inspector's label.
 * Each field carries its `type` + `default` (the same `fieldRows` reflection the FIELDS table renders) and
 * its `description` (the field's doc comment, `null` where unwritten). One truth for the inspector hover,
 * the docs reference, and IDE hover, with no second copy.
 */
export interface FieldDoc {
    description: string | null;
    type: string;
    default: string;
}

export interface ComponentDoc {
    summary: string | null;
    fields: Record<string, FieldDoc>;
}

export const fieldDocs: Record<string, ComponentDoc> = docs;

/** render a doc string for display: JSDoc `{@link Target}` / `{@link Target|text}` collapse to the plain
 * word the reader sees (the inspector popover isn't markdown, unlike the docs reference). */
export function plain(s: string): string {
    return s.replace(/\{@link\s+([^}|\s]+)(?:[|\s]+([^}]+))?\}/g, (_, target, text) =>
        (text ?? target).trim(),
    );
}
