#!/usr/bin/env bun

import { existsSync, mkdirSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";

export interface TemplateOptions {
    /**
     * dependency spec for `@dylanebert/shallot`. `"latest"` for the published `bun create shallot`
     * scaffold; `"workspace:*"` when `bun run build` regenerates examples/templates/* in-repo.
     */
    shallot?: string;
}

/**
 * the project files keyed by relative path, with the project name interpolated. single source of
 * truth for both `bun create shallot <name>` and the in-repo examples/templates/starter example
 * (regenerated by `bun run build`).
 *
 * the project is pure data — a `shallot.json` manifest + plugin modules + `public/`, no vite
 * boilerplate. the CLI provides every harness over it: `shallot dev` runs it standalone (`bun dev`),
 * `shallot .` opens it in the editor, `shallot build` ships it (web + native targets).
 */
export function template(name: string, opts: TemplateOptions = {}): Record<string, string> {
    const shallot = opts.shallot ?? "latest";

    return {
        "public/icon.svg": ICON,
        ".gitignore": "node_modules/\ndist/\nbuild/\n",
        "package.json":
            JSON.stringify(
                {
                    name,
                    version: "0.0.0",
                    private: true,
                    type: "module",
                    dependencies: { "@dylanebert/shallot": shallot },
                    devDependencies: { typescript: "^5.9.3" },
                },
                null,
                2,
            ) + "\n",
        "tsconfig.json":
            JSON.stringify(
                {
                    compilerOptions: {
                        target: "ESNext",
                        module: "ESNext",
                        moduleResolution: "bundler",
                        lib: ["ESNext", "DOM", "DOM.Iterable"],
                        types: ["@webgpu/types"],
                        strict: true,
                        noEmit: true,
                        skipLibCheck: true,
                    },
                    include: ["src"],
                },
                null,
                2,
            ) + "\n",
        "shallot.json": MANIFEST,
        "src/spin.ts": SPIN,
        "public/scenes/scene.scene": SCENE,
        "README.md": readme(name),
    };
}

/**
 * the committed in-repo template under examples/templates/<dir>. the source of truth for what
 * `bun run build` regenerates and `bun check` gates for staleness.
 */
export const TEMPLATES: { dir: string }[] = [{ dir: "starter" }];

/** write a template file map under dir, creating parent directories as needed. */
export function scaffold(dir: string, files: Record<string, string>): void {
    for (const [rel, content] of Object.entries(files)) {
        const path = join(dir, rel);
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, content);
    }
}

const ICON = `<svg id="Shallot" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80">
  <title>shallot icon</title>
  <defs>
    <radialGradient id="baseGradient" cx="35%" cy="30%" r="70%" fx="25%" fy="20%">
      <stop offset="0%" stop-color="#F5D4B8"/>
      <stop offset="45%" stop-color="#E8A86B"/>
      <stop offset="100%" stop-color="#B87654"/>
    </radialGradient>
  </defs>
  <g transform="rotate(35 40.0 40.0)">
    <path d="M40,2 C44,10 66,28 66,46 C66,60 48,70 40,78 C32,70 14,60 14,46 C14,28 36,10 40,2 Z" fill="#E8A86B"/>
    <path d="M40,6 C37,14 22,28 20,44 C20,52 28,62 36,70 C34,58 26,46 26,38 C26,26 38,12 40,6 Z" fill="#D49560"/>
    <path d="M40,6 C43,14 58,28 60,44 C60,52 52,62 44,70 C46,58 54,46 54,38 C54,26 42,12 40,6 Z" fill="#D49560"/>
    <path d="M40,8 C40,20 40,50 40,72" stroke="#6B4230" stroke-width="1" stroke-opacity="0.4" fill="none" stroke-linecap="round"/>
    <path d="M40,78 C48,70 66,60 66,46 C61,58 44,70 40,73 Z" fill="#D49560"/>
    <path d="M40,2 C44,10 66,28 66,46 C66,60 48,70 40,78 C32,70 14,60 14,46 C14,28 36,10 40,2 Z" fill="none" stroke="#6B4230" stroke-width="2"/>
  </g>
</svg>
`;

const readme = (name: string) => `# ${name}

A shallot project.

## Develop

\`\`\`bash
bun install
bunx shallot dev
\`\`\`

\`bun install\` fetches the engine. \`bunx shallot dev\` runs the project with hot
reload; \`bunx shallot\` opens it in the editor. Edit \`src/spin.ts\` (a plugin) and
\`shallot.json\` (the manifest: scene + plugin enablement) in your IDE.

## Ship

\`\`\`bash
bunx shallot build
\`\`\`

Builds a web bundle to \`dist/\`. For native targets:
\`bunx shallot build --target windows|mac|linux\` (add \`--release\` for an optimized build).
`;

// The project manifest: the editor (\`shallot .\`) and a shipped build both read it. \`scene\`
// is the scene to open; \`plugins\` is enablement — "Orbit": true turns on the orbit camera the
// scene uses, and "Spin": "./src/spin" declares our own plugin by its module path. The default
// plugins (render, lit surface) are on unless you set one false. Toggle these in the editor's
// plugin menu and it rewrites this file, so the editor and a build always agree on what loads.
const MANIFEST = `{
  "$schema": "./node_modules/@dylanebert/shallot/shallot.schema.json",
  "scene": "scenes/scene.scene",
  "plugins": {
    "Orbit": true,
    "Spin": "./src/spin"
  }
}
`;

const SPIN = `import { type Plugin, type State, type System, Part, quat, Transform } from "@dylanebert/shallot";

// A plugin is plain data: components + systems the engine runs. This system spins every Part
// around Y. It runs when the project plays (the editor's preview, or a shipped build) but not
// while you edit — the editor (\`bunx shallot\`) builds in edit mode, where unannotated systems
// are skipped, so the cube stays put and editable there. Delete this file (and its
// \`shallot.json\` entry) for a static scene.
const SpinSystem: System = {
    group: "simulation",
    update(state: State) {
        // Derive the angle from elapsed time, not a module-level accumulator, so it stays
        // correct after a hot reload or State rebuild rather than carrying stale rotation.
        const q = quat(0, (state.time.elapsed * 45) % 360, 0);
        for (const eid of state.query([Part, Transform])) {
            Transform.rot.set(eid, q.x, q.y, q.z, q.w);
        }
    },
};

// The default export is the plugin — \`shallot.json\` references this file by path and imports
// its default. The name ("Spin") is how the plugin menu lists it.
const SpinPlugin: Plugin = { name: "Spin", systems: [SpinSystem] };
export default SpinPlugin;
`;

const SCENE = `<scene>
    <a ambient-light="color: 0xd0dcec; intensity: 0.5" />
    <a directional-light="direction: -0.4 -1 -0.55; color: 0xfff4e0; intensity: 1.1" />

    <!-- the camera auto-binds to the page's <canvas>; drag to orbit, scroll to zoom -->
    <a camera sear orbit="distance: 5; yaw: 0.6; pitch: 0.25" transform />

    <!-- a Part is the engine's drop-in renderable: a mesh (default "cube") wearing a surface (default "default", lit) -->
    <a part transform="pos: 0 0 0" color="rgba: 0.85 0.55 0.35 1" />
</scene>
`;

if (import.meta.main) {
    const args = process.argv.slice(2);
    const name = args.find((a) => !a.startsWith("--"));
    if (!name) {
        console.error("Usage: bun create shallot <project-name>");
        process.exit(1);
    }

    const dir = resolve(name);
    if (existsSync(dir)) {
        console.error(`Directory "${name}" already exists`);
        process.exit(1);
    }

    scaffold(dir, template(name));

    console.log(`Created ${name}/`);
    console.log();
    console.log("Next steps:");
    console.log(`  cd ${name}`);
    console.log("  bun install");
    console.log("  bunx shallot dev");
}
