// Physics extension surface: what an outside solver or custom tooling needs past the author happy path.
// An outside solver registers the shared components with these traits, derives the authored constraint
// set from the defs/signatures, reads hull geometry from `Hulls`, and orders its systems against these
// anchors. Tooling driving `Physics.world` (or its own `World`) past the atomic core needs the solver's
// free functions: shape builders, `BodyType`/joint configs, debug draw, `hashWorldState`.
//
// The solver half is an explicit re-export, not `export * from "./engine"`: the engine barrel exports
// `shutdown`, which terminates the process-singleton kernel's worker pool that PhysicsPlugin shares, so a
// consumer calling it would silently degrade every physics scene to single-thread. `init` and `threads`
// stay. Mirror the engine barrel here whenever it gains a public symbol.

export { nlerpShortest } from "./compose";
export {
    type AABB,
    type BaseJointConfig,
    Body,
    type BodyCastHit,
    type BodyDef,
    type BodyEvents,
    type BodyMoveEvent,
    type BodyPlane,
    BodyType,
    type Capacity,
    type Capsule,
    type CastCallback,
    type CastHit,
    type CollisionPlane,
    type CompoundCapsuleDef,
    type CompoundData,
    type CompoundDef,
    type CompoundHullDef,
    type CompoundMeshDef,
    type CompoundSphereDef,
    Contact,
    type ContactData,
    type ContactEvents,
    type ContactHitEvent,
    type ContactTouchEvent,
    type Counters,
    clipVector,
    createBoxMesh,
    createCompound,
    createCone,
    createCylinder,
    createGrid,
    createGridMesh,
    createHeightField,
    createHollowBoxMesh,
    createHull,
    createMesh,
    createRock,
    createTorusMesh,
    createWave,
    createWaveMesh,
    DebugColor,
    type DebugDraw,
    DistanceJoint,
    type DistanceJointConfig,
    defaultBodyDef,
    defaultDebugDraw,
    defaultFilter,
    defaultQueryFilter,
    defaultShapeDef,
    defaultSurfaceMaterial,
    defaultWorldDef,
    type Filter,
    HEIGHT_FIELD_HOLE,
    type HeightFieldData,
    type HeightFieldDef,
    type HullData,
    hashWorldState,
    type InitOptions,
    init,
    Joint,
    type JointEvent,
    JointType,
    type Manifold,
    type ManifoldPoint,
    type MassData,
    type Mat3,
    type Mesh,
    type MeshData,
    type MeshDef,
    MeshEdgeFlags,
    type MotionLocks,
    MotorJoint,
    type MotorJointConfig,
    type MoverFilterCallback,
    makeBoxHull,
    makeCubeHull,
    makeOffsetBoxHull,
    makeTransformedBoxHull,
    type OverlapCallback,
    ParallelJoint,
    type ParallelJointConfig,
    type PlaneResult,
    type PlaneResultCallback,
    type PlaneSolverResult,
    type Pos,
    PrismaticJoint,
    type PrismaticJointConfig,
    type Profile,
    type Quat,
    type QueryFilter,
    type RayResult,
    RevoluteJoint,
    type RevoluteJointConfig,
    type SensorEvents,
    type SensorTouchEvent,
    Shape,
    type ShapeDef,
    type ShapeProxy,
    ShapeType,
    type Sphere,
    SphericalJoint,
    type SphericalJointConfig,
    type SurfaceMaterial,
    solvePlanes,
    type Transform,
    type TreeStats,
    threads,
    type Vec3,
    WeldJoint,
    type WeldJointConfig,
    WheelJoint,
    type WheelJointConfig,
    World,
    type WorldDef,
    type WorldState,
    type WorldTransform,
} from "./engine";
export { type Hull, type HullFace, Hulls, UNIT_CUBE_ID } from "./hull";
export {
    type BodyState,
    bodyTraits,
    ComposeSystem,
    ConstraintSystem,
    type JointDef,
    jointDefs,
    jointSignature,
    jointTraits,
    type SpringDef,
    StepSystem,
    springDefs,
    springSignature,
    springTraits,
} from "./index";
export { bodyCandidates, cursorRay, forwardRay, grabHit, worldToLocal } from "./pick";
export {
    generateRay,
    qRotate,
    type Ray,
    type RayBody,
    type RayHit,
    rayCapsule,
    raycast,
    rayOBB,
    raySphere,
    screenToRay,
} from "./raycast";
