// the solver port: the free-function World API behind `Physics.world`, re-exported by name.
// The solver half is an explicit re-export, not `export * from "./api"`: the engine barrel exports
// `shutdown`, which terminates the process-singleton kernel's worker pool that PhysicsPlugin shares, so a
// consumer calling it would silently degrade every physics scene to single-thread. `init` and `threads`
// stay. Mirror the engine barrel here whenever it gains a public symbol.

export {
    type AABB,
    type BaseJointConfig,
    Body,
    type BodyCastHit,
    type BodyDef,
    type BodyEvents,
    type BodyMoveEvent,
    type BodyPlane,
    BodyType,
    type Capacity,
    type Capsule,
    type CastCallback,
    type CastHit,
    type CollisionPlane,
    type CompoundCapsuleDef,
    type CompoundData,
    type CompoundDef,
    type CompoundHullDef,
    type CompoundMeshDef,
    type CompoundSphereDef,
    Contact,
    type ContactData,
    type ContactEvents,
    type ContactHitEvent,
    type ContactTouchEvent,
    type Counters,
    clipVector,
    createBoxMesh,
    createCompound,
    createCone,
    createCylinder,
    createGrid,
    createGridMesh,
    createHeightField,
    createHollowBoxMesh,
    createHull,
    createMesh,
    createRock,
    createTorusMesh,
    createWave,
    createWaveMesh,
    DebugColor,
    type DebugDraw,
    DistanceJoint,
    type DistanceJointConfig,
    defaultBodyDef,
    defaultDebugDraw,
    defaultFilter,
    defaultQueryFilter,
    defaultShapeDef,
    defaultSurfaceMaterial,
    defaultWorldDef,
    type Filter,
    HEIGHT_FIELD_HOLE,
    type HeightFieldData,
    type HeightFieldDef,
    type HullData,
    hashWorldState,
    type InitOptions,
    init,
    Joint,
    type JointEvent,
    JointType,
    type Manifold,
    type ManifoldPoint,
    type MassData,
    type Mat3,
    type Mesh,
    type MeshData,
    type MeshDef,
    MeshEdgeFlags,
    type MotionLocks,
    MotorJoint,
    type MotorJointConfig,
    type MoverFilterCallback,
    makeBoxHull,
    makeCubeHull,
    makeOffsetBoxHull,
    makeTransformedBoxHull,
    type OverlapCallback,
    ParallelJoint,
    type ParallelJointConfig,
    type PlaneResult,
    type PlaneResultCallback,
    type PlaneSolverResult,
    type Pos,
    PrismaticJoint,
    type PrismaticJointConfig,
    type Profile,
    type Quat,
    type QueryFilter,
    type RayResult,
    RevoluteJoint,
    type RevoluteJointConfig,
    type SensorEvents,
    type SensorTouchEvent,
    Shape,
    type ShapeDef,
    type ShapeProxy,
    ShapeType,
    type Sphere,
    SphericalJoint,
    type SphericalJointConfig,
    type SurfaceMaterial,
    solvePlanes,
    type Transform,
    type TreeStats,
    threads,
    type Vec3,
    WeldJoint,
    type WeldJointConfig,
    WheelJoint,
    type WheelJointConfig,
    World,
    type WorldDef,
    type WorldState,
    type WorldTransform,
} from "./api";
