import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const SOURCE = resolve(ROOT, "assets/branding");
const GENERATED = resolve(ROOT, "src/standard/loading/brand-data.ts");

export interface Palette {
    gold: string;
    dim: string;
    ink: string;
    bg: string;
}

export interface Branding {
    marks: { s: string[]; m: string[]; l: string[] };
    palettes: { dark: Palette; light: Palette };
    name: string;
    font: Record<string, string[]>;
}

function readRows(file: string): string[] {
    return readFileSync(resolve(SOURCE, file), "utf8")
        .replace(/\r\n/g, "\n")
        .replace(/\n$/, "")
        .split("\n");
}

export function readBranding(): Branding {
    const marks = {
        s: readRows("mark-s.txt"),
        m: readRows("mark.txt"),
        l: readRows("mark-l.txt"),
    };
    const palettes = JSON.parse(
        readFileSync(resolve(SOURCE, "palette.json"), "utf8"),
    ) as Branding["palettes"];
    const wordmark = JSON.parse(readFileSync(resolve(SOURCE, "wordmark.json"), "utf8")) as {
        name: string;
        font: Record<string, string[]>;
    };
    return { marks, palettes, ...wordmark };
}

function objectLiteral(value: object): string {
    const properties = Object.entries(value)
        .map(([key, entry]) => {
            const literal = Array.isArray(entry)
                ? `[${entry.map((item) => JSON.stringify(item)).join(", ")}]`
                : JSON.stringify(entry);
            return `    ${key}: ${literal},`;
        })
        .join("\n");
    return `{\n${properties}\n}`;
}

export function renderBrandData(): string {
    const { marks, palettes, name, font } = readBranding();
    const rows = marks.m.map((row) => `        ${JSON.stringify(row)}`).join(",\n");
    return `// Generated by bun scripts/branding.ts from assets/branding; do not edit.\nexport const MARK = {\n    m: [\n${rows},\n    ],\n} as const;\n\nexport const FONT: Record<string, readonly string[]> = ${objectLiteral(font)};\n\nexport const NAME = ${JSON.stringify(name)};\n\nexport const DARK = ${objectLiteral(palettes.dark)} as const;\n\nexport const LIGHT = ${objectLiteral(palettes.light)} as const;\n`;
}

export function writeBrandData(): void {
    writeFileSync(GENERATED, renderBrandData());
}

if (import.meta.main) writeBrandData();
