import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// `bun run examples:index [--check]`: emit `examples/AGENTS.md` from each `examples/*/shallot.json`
// `kind` + `problem` (or `description` where no problem is declared). The index is never hand-written; `--check` reds when the committed file
// differs from what the declarations generate. Every example dir must declare both fields.

const root = resolve(import.meta.dir, "..");
const examples = resolve(root, "examples");
const out = resolve(examples, "AGENTS.md");
const KINDS = ["recipe", "showcase"] as const;
type Kind = (typeof KINDS)[number];

const rows: { name: string; kind: Kind; description: string; checkTier: string }[] = [];
const errors: string[] = [];
for (const name of readdirSync(examples).sort()) {
    if (!statSync(resolve(examples, name)).isDirectory()) continue;
    const path = resolve(examples, name, "shallot.json");
    if (!existsSync(path)) {
        errors.push(`examples/${name}/ has no shallot.json`);
        continue;
    }
    const { kind, description, problem, check } = JSON.parse(readFileSync(path, "utf8"));
    if (!KINDS.includes(kind))
        errors.push(`examples/${name}/shallot.json: kind must be ${KINDS.join(" | ")}`);
    else if (typeof description !== "string" || description.trim() === "")
        errors.push(`examples/${name}/shallot.json: description is missing`);
    else {
        const entries = Array.isArray(check) ? check : check ? [check] : [];
        const checkTier = entries
            .map((entry) =>
                entry && typeof entry === "object" && "tier" in entry
                    ? (entry as { tier?: unknown }).tier
                    : undefined,
            )
            .filter((tier): tier is string => typeof tier === "string" && tier.trim() !== "")
            .join(", ");
        rows.push({
            name,
            kind,
            checkTier: checkTier || "-",
            description: (typeof problem === "string" && problem.trim() !== ""
                ? problem
                : description
            ).trim(),
        });
    }
}
if (errors.length > 0) {
    for (const e of errors) console.error(`✗ ${e}`);
    process.exit(1);
}

const cell = (s: string) => s.replaceAll("|", "\\|");
const lines = [
    "# Examples",
    "",
    "Generated by `bun run examples:index` from `examples/*/shallot.json`; edit manifests. Run with `bunx shallot dev examples/<name>`.",
];
for (const kind of KINDS) {
    const own = rows.filter((r) => r.kind === kind);
    if (own.length === 0) continue;
    lines.push("", kind === "recipe" ? "## Recipes" : "## Showcase", "");
    if (kind === "recipe") {
        lines.push("| name | description | add |", "| --- | --- | --- |");
        for (const r of own)
            lines.push(
                `| \`${r.name}\` | ${cell(r.description)}${r.checkTier === "-" ? "" : ` (check: ${cell(r.checkTier)})`} | \`bunx shallot add ${r.name}\` |`,
            );
    } else {
        lines.push("| name | description |", "| --- | --- |");
        for (const r of own) lines.push(`| \`${r.name}\` | ${cell(r.description)} |`);
    }
}
const text = `${lines.join("\n")}\n`;

if (process.argv.includes("--check")) {
    const committed = existsSync(out) ? readFileSync(out, "utf8") : "";
    if (committed !== text) {
        console.error(
            "✗ examples/AGENTS.md differs from the manifests; run `bun run examples:index`.",
        );
        process.exit(1);
    }
} else {
    writeFileSync(out, text);
}
