// @dylanebert/shallot-ocean — FFT ocean surface extension. The package exposes a butterfly FFT,
// spectral ocean kernels, CPU reference functions, and a Shallot plugin.

export {
    type ComplexArray,
    type CpuStageResult,
    chop,
    idft2,
    type JacobianStats,
    jacobianStats,
    runCpuPipeline,
    spectralGradient,
    updateH,
} from "./cpu-reference";
export { directIdft2, fft1dInPlace, ifft2 } from "./fft";
export {
    type FftLayout,
    getFftKernels,
    makeColFftKernel,
    makeFftLayout,
    makeRowFftKernel,
} from "./gpu-fft";
export {
    type CascadeConfig,
    CascadeParams,
    Complex,
    getCascadeConfigs,
    getDisplacementTexture,
    getProbeBufferForCascade,
    measureFoldFraction,
    OceanPlugin,
    oceanCompute,
    PEAK_FMA_FLOPS,
    PROBE_COUNTS,
    PROBE_TOTAL,
    ProbeData,
    type ProbeRow,
    readStageBuffers,
    type StageBuffers,
    setPeakFmaEnabled,
    updateKernel,
    updateLayout,
} from "./ocean";
export {
    type LabelFn,
    lag1AutocorrParityWitness,
    measuredLag1AutocorrX,
    type ParityWitnessReading,
} from "./parity-witness";
export {
    composedSlopePsd,
    rasterSlopeMoment,
    realizedSlopeMss,
    reduceSlopeMip,
    runSlopeCpuPipeline,
    SLOPE_CASCADE_CONFIGS,
    SLOPE_MIP_LEVELS,
    slopeMomentAgreementTolerance,
    slopeMomentSamplingError,
    slopeSpectra,
} from "./slope";
export {
    ALL_CASCADE_CONFIGS,
    assertAllPowerOfTwo,
    assertCoprimeL,
    C_M,
    CASCADE_CONFIGS,
    declaredBandVariance,
    directDftFlops,
    directionalDensity,
    frictionVelocity,
    fullMeanSquareSlope,
    G,
    gcd,
    generateH0,
    isPowerOfTwo,
    K_M,
    kIndex,
    OMEGA_C,
    philips,
    type RealizationMutation,
    SEA_STATE,
    type SeaState,
    type SpectrumMutation,
    theoreticalFlops,
    tilePeriod,
    totalTheoreticalFlops,
    U10,
} from "./spectrum";
