// @dylanebert/shallot-ocean — FFT ocean surface extension. The package exposes a butterfly FFT,
// spectral ocean kernels, CPU reference functions, and a Shallot plugin.

export {
    buildClipLevels,
    buildClipmapMesh,
    type CascadeTexel,
    type ClipLevel,
    type ContinuityFinding,
    checkContinuity,
    finestCascadeTexel,
    OCEAN_CLIP_CONFIG,
    OCEAN_CLIP_LEVELS,
} from "./clipmap";
export {
    type ComplexArray,
    type CpuStageResult,
    chop,
    idft2,
    type JacobianStats,
    jacobianStats,
    runCpuPipeline,
    spectralGradient,
    updateH,
} from "./cpu-reference";
export { directIdft2, fft1dInPlace, ifft2, ifft2Exact } from "./fft";
export {
    type FftLayout,
    getFftKernels,
    makeColFftKernel,
    makeFftLayout,
    makeRowFftKernel,
    measureTwiddleTrigError,
    type TwiddleErrorReading,
    twiddleAngle,
} from "./gpu-fft";
export {
    type CascadeConfig,
    CascadeParams,
    Complex,
    getCascadeConfigs,
    getDisplacementTexture,
    getProbeBufferForCascade,
    measureFoldFraction,
    OceanPlugin,
    oceanCompute,
    PEAK_FMA_FLOPS,
    PROBE_COUNTS,
    PROBE_TOTAL,
    ProbeData,
    type ProbeRow,
    readStageBuffers,
    type StageBuffers,
    setPeakFmaEnabled,
    updateKernel,
    updateLayout,
} from "./ocean";
export {
    type LabelFn,
    lag1AutocorrParityWitness,
    measuredLag1AutocorrX,
    type ParityWitnessReading,
} from "./parity-witness";
export {
    bicubicSample,
    bilinearSample,
    catmullRom1D,
    type Field,
    nearestSample,
    type ReconstructionKernel,
    syntheticField,
} from "./reconstruction";
export {
    composedSlopePsd,
    getSlopeBuffers,
    rasterSlopeMoment,
    realizedSlopeMss,
    reduceSlopeMip,
    runSlopeCpuPipeline,
    SLOPE_CASCADE_CONFIGS,
    SLOPE_MIP_LEVELS,
    slopeCompute,
    slopeMipSize,
    slopeSpectra,
} from "./slope";
export {
    CHANNELS,
    type Channel,
    complexL2Norm,
    expectedFromPublished,
    expectedLevel0,
    f16Neighbors,
    f16NextDown,
    f16NextUp,
    f16Round,
    f16StepDistance,
    higham242AbsoluteBound,
    higham242RelativeBound,
} from "./slope-seam";
export {
    ALL_CASCADE_CONFIGS,
    assertAllPowerOfTwo,
    assertCoprimeL,
    C_M,
    CASCADE_CONFIGS,
    declaredBandVariance,
    directDftFlops,
    directionalDensity,
    frictionVelocity,
    fullMeanSquareSlope,
    G,
    gcd,
    generateH0,
    isPowerOfTwo,
    K_M,
    kIndex,
    OMEGA_C,
    philips,
    type RealizationMutation,
    SEA_STATE,
    type SeaState,
    type SpectrumMutation,
    theoreticalFlops,
    tilePeriod,
    totalTheoreticalFlops,
    U10,
} from "./spectrum";
export {
    oceanDisplacementLayout,
    oceanDisplacementPatch,
    oceanDisplacementVaryings,
    oceanDisplacementVs,
} from "./vertex-displacement";
