import { mkdtempSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { run } from "../native";
const reference = process.env.BOX3D;
if (!reference) throw new Error("set BOX3D");
const revision = run(["git", "-C", reference, "rev-parse", "HEAD"]).trim();
if (revision !== "47d7f7cc7e091142c08d11dc7d2e493c5d34f536") throw new Error(`BOX3D is at ${revision}, not 47d7f7cc`);
const dir = mkdtempSync(join(tmpdir(), "box3d-counts-"));
run(["bash", "-c", 'git -C "$1" archive HEAD | tar -x -C "$2"', "archive", reference, dir]);
const harness = join(dir, "native.c");
copyFileSync(join(import.meta.dir, "../native.c"), harness);
run(["python3", join(import.meta.dir, "native-counts.py"), dir, harness]);
run(["cmake", "-S", dir, "-B", join(dir, "build"), "-DCMAKE_BUILD_TYPE=Release", "-DBOX3D_BENCHMARKS=ON", `-DFETCHCONTENT_BASE_DIR=${join(tmpdir(), "box3d-parity-47d7f7cc/fetch")}`]);
run(["cmake", "--build", join(dir, "build"), "-j", "8", "--target", "box3d", "shared"]);
const binary = join(dir, "native-counts");
run(["cc", "-O2", "-std=c17", "-ffp-contract=off", ...["src", "include", "shared"].map(p => `-I${join(dir,p)}`), harness, join(dir,"build/shared/libshared.a"), join(dir,"build/src/libbox3d.a"), "-o", binary]);
console.log(`NATIVE_COUNTS=${binary}`);
