export const S = {
    editor: ".editor",
    viewport: ".viewport",
    viewportCanvas: ".viewport-canvas",
    canvas: "canvas",
    outliner: ".outliner",
    inspector: ".inspector",
    toolbar: ".toolbar",
    playBtn: ".transport-btn.play",
    stopBtn: ".transport-btn.stop",
    row: ".outliner .row",
    rowSelected: ".outliner .row.selected",
    label: ".label",
    addEntityBtn: ".add-entity-btn",
    addComponentBtn: ".add-component-btn",
    addComponentPicker: ".add-component-picker",
    addComponentSearch: ".add-component-search",
    addComponentItem: ".add-component-item",
    sectionHeader: ".section-header",
    sectionLabel: ".section-label",
    sectionBody: ".section-body",
    fieldRow: ".field-row",
    fieldInput: ".field-input",
    fieldLabel: ".field-label",
    sidebarHeader: ".sidebar-header",
} as const;
