//! Bit-exact parity of the Rust wide (convex) contact solver against the box3d C reference, read from
//! the committed gold vectors (`src/contact_wide.gold.json`, generated by `bun run
//! gen-contact-wide-gold`). The generator runs a scalar per-lane transcription of the
//! `b3*Contacts_Convex` phases over the real b3 math library; this drives the SIMD-lane Rust port with
//! the same four contacts packed into one wide record and asserts every output float bit-for-bit per
//! lane (graph coloring guarantees the lanes share no body, so each lane is independent).

use serde_json::Value;
use tumble_kernel::body::flags::DYNAMIC;
use tumble_kernel::body::{SIM_STRIDE, STATE_STRIDE};
use tumble_kernel::col::Col;
use tumble_kernel::contact::{Softness, NULL_INDEX};
use tumble_kernel::contact_wide::{
    prepare, restitution, solve, store, warm_start, LANES, WIDE_IDX_STRIDE, WIDE_META_STRIDE,
    WIDE_STRIDE,
};
use tumble_kernel::manifold_abi::{DIR_STRIDE, MANIFOLD_STRIDE};

/// SAFETY: a gold harness is single-threaded and each column has exactly one user, so `Col`'s
/// disjoint-write promise holds trivially.
fn col<T: Copy>(v: &mut [T]) -> Col<'_, T> {
    unsafe { Col::of(v) }
}

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/contact_wide.gold.json");

fn from_bits(hex: &str) -> f32 {
    f32::from_bits(u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex"))
}
fn floats(v: &Value) -> Vec<f32> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|e| from_bits(e.as_str().expect("hex str")))
        .collect()
}
fn soft(v: &Value) -> Softness {
    let a = floats(v);
    Softness {
        bias_rate: a[0],
        mass_scale: a[1],
        impulse_scale: a[2],
    }
}
fn assert_bits(got: f32, want: f32, label: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{label}: got 0x{:08x} ({got}), want 0x{:08x} ({want})",
        got.to_bits(),
        want.to_bits(),
    );
}

// One body's assigned sim index plus its dumped state/sim data.
struct Body {
    idx: usize,
    v: [f32; 3],
    w: [f32; 3],
    dp: [f32; 3],
    dq: [f32; 4],
    inv_mass: f32,
    inv_i: [f32; 9],
}

fn body(lanes_input: &Value, prefix: &str, idx: usize) -> Body {
    let g = |k: &str| floats(&lanes_input[k]);
    let v = g(&format!("v{prefix}"));
    let w = g(&format!("w{prefix}"));
    let dp = g(&format!("dp{prefix}"));
    let dq = g(&format!("dq{prefix}"));
    let inv_i = g(&format!("invI{prefix}"));
    Body {
        idx,
        v: [v[0], v[1], v[2]],
        w: [w[0], w[1], w[2]],
        dp: [dp[0], dp[1], dp[2]],
        dq: [dq[0], dq[1], dq[2], dq[3]],
        inv_mass: from_bits(
            lanes_input[format!("invMass{prefix}")]
                .as_str()
                .expect("invMass"),
        ),
        inv_i: std::array::from_fn(|i| inv_i[i]),
    }
}

fn write_body(state: &mut [f32], sim: &mut [f32], b: &Body) {
    let o = b.idx * STATE_STRIDE;
    state[o..o + 3].copy_from_slice(&b.v);
    state[o + 3..o + 6].copy_from_slice(&b.w);
    state[o + 6..o + 9].copy_from_slice(&b.dp);
    state[o + 9..o + 13].copy_from_slice(&b.dq);
    let so = b.idx * SIM_STRIDE;
    sim[so] = b.inv_mass;
    sim[so + 19..so + 28].copy_from_slice(&b.inv_i); // invInertiaWorld
}

#[test]
fn wide_convex_phases_match_c() {
    let gold: Value = serde_json::from_str(GOLD).expect("gold json");
    let contact_softness = soft(&gold["softness"]["cs"]);
    let static_softness = soft(&gold["softness"]["ss"]);
    let inv_h = from_bits(gold["invH"].as_str().unwrap());
    let contact_speed = from_bits(gold["contactSpeed"].as_str().unwrap());
    let restitution_threshold = from_bits(gold["restitutionThreshold"].as_str().unwrap());
    let hit_threshold = from_bits(gold["hitThreshold"].as_str().unwrap());

    let lanes = gold["lanes"].as_array().expect("lanes");
    let lane_count = lanes.len();
    assert_eq!(lane_count, LANES, "harness emits a full wide record");

    // Assign body sim indices: each lane's A (always dynamic) and B (dynamic, or null when static).
    let mut next = 0usize;
    let mut a_bodies: Vec<Body> = Vec::new();
    let mut b_bodies: Vec<Option<Body>> = Vec::new();
    for lane in lanes {
        let input = &lane["input"];
        let a = body(input, "A", next);
        next += 1;
        a_bodies.push(a);
        if input["bNull"].as_i64().unwrap() == 0 {
            let b = body(input, "B", next);
            next += 1;
            b_bodies.push(Some(b));
        } else {
            b_bodies.push(None);
        }
    }
    let body_count = next;

    let mut state = vec![0.0f32; body_count * STATE_STRIDE];
    let mut sim = vec![0.0f32; body_count * SIM_STRIDE];
    let mut flags = vec![DYNAMIC; body_count];
    for a in &a_bodies {
        write_body(&mut state, &mut sim, a);
    }
    for b in b_bodies.iter().flatten() {
        write_body(&mut state, &mut sim, b);
    }

    // Persistent store columns: each lane is one convex contact (contactId = lane index) with one
    // pool manifold (manifoldBase = lane index). The directory carries the material + body indices +
    // block descriptor the gather reads.
    let mut dir = vec![0u32; lane_count * DIR_STRIDE];
    let mut pool = vec![0.0f32; lane_count * MANIFOLD_STRIDE];

    for (c, lane) in lanes.iter().enumerate() {
        let input = &lane["input"];
        let point_count = input["pointCount"].as_u64().unwrap() as usize;
        let normal = floats(&input["normal"]);
        let tv = floats(&input["tangentVelocity"]);
        let m_friction = floats(&input["mFriction"]);
        let m_rolling = floats(&input["mRolling"]);
        let m_twist = from_bits(input["mTwist"].as_str().unwrap());
        let ra = input["rA"].as_array().unwrap();
        let rb = input["rB"].as_array().unwrap();
        let sep = floats(&input["separation"]);
        let mp_imp = floats(&input["mpNormalImpulse"]);

        let d = c * DIR_STRIDE;
        dir[d] = from_bits(input["friction"].as_str().unwrap()).to_bits();
        dir[d + 1] = from_bits(input["restitution"].as_str().unwrap()).to_bits();
        dir[d + 2] = from_bits(input["rollingResistance"].as_str().unwrap()).to_bits();
        dir[d + 3] = tv[0].to_bits();
        dir[d + 4] = tv[1].to_bits();
        dir[d + 5] = tv[2].to_bits();
        dir[d + 6] = input["flags"].as_u64().unwrap() as u32;
        dir[d + 7] = 1; // manifoldCount
        dir[d + 8] = c as u32; // manifoldBase
        dir[d + 9] = a_bodies[c].idx as u32;
        dir[d + 10] = b_bodies[c]
            .as_ref()
            .map(|b| b.idx as u32)
            .unwrap_or(NULL_INDEX);
        dir[d + 11] = 0; // hit

        let mpo = c * MANIFOLD_STRIDE;
        pool[mpo..mpo + 3].copy_from_slice(&normal[0..3]);
        pool[mpo + 3..mpo + 6].copy_from_slice(&m_friction[0..3]);
        pool[mpo + 6] = m_twist;
        pool[mpo + 7..mpo + 10].copy_from_slice(&m_rolling[0..3]);
        pool[mpo + 10] = f32::from_bits(point_count as u32); // pointCount
        for p in 0..point_count {
            let a = floats(&ra[p]);
            let b = floats(&rb[p]);
            let pp = mpo + 11 + p * 14; // M_POINTS + p * POOL_POINT_STRIDE
            pool[pp..pp + 3].copy_from_slice(&[a[0], a[1], a[2]]); // anchorA
            pool[pp + 3..pp + 6].copy_from_slice(&[b[0], b[1], b[2]]); // anchorB
            pool[pp + 6] = sep[p]; // separation
            pool[pp + 8] = mp_imp[p]; // normalImpulse
        }
    }

    // Wide constraint record + its meta/index columns.
    let mut wide = vec![0.0f32; WIDE_STRIDE];
    let mut idx = vec![0u32; WIDE_IDX_STRIDE];
    let mut meta = vec![0u32; WIDE_META_STRIDE];
    for lane in 0..lane_count {
        meta[lane] = lane as u32; // laneContact = contactId
    }
    meta[LANES] = lane_count as u32; // laneCount

    // warmStartScale is a world-level flag (uniform across a step); the harness uses 1.0 for all lanes.
    let warm = 1.0f32;

    // prepare (gathers state/sim/dir/pool, writes wide + idx)
    prepare(
        col(&mut wide),
        col(&mut idx),
        col(&mut meta),
        col(&mut state),
        col(&mut sim),
        col(&mut dir),
        col(&mut pool),
        0,
        1,
        contact_softness,
        static_softness,
        warm,
    );

    // warm_start -> solve(bias) -> relax -> restitution over the record (all mutate state only)
    warm_start(
        col(&mut wide),
        col(&mut idx),
        col(&mut state),
        col(&mut flags),
        0,
        1,
        0,
    );
    solve(
        col(&mut wide),
        col(&mut idx),
        col(&mut state),
        col(&mut flags),
        0,
        1,
        true,
        inv_h,
        contact_speed,
        0,
    );
    solve(
        col(&mut wide),
        col(&mut idx),
        col(&mut state),
        col(&mut flags),
        0,
        1,
        false,
        inv_h,
        contact_speed,
        0,
    );
    restitution(
        col(&mut wide),
        col(&mut idx),
        col(&mut state),
        col(&mut flags),
        0,
        1,
        restitution_threshold,
        0,
    );

    // store (writes impulses back into the pool manifolds + the directory hit flags)
    store(
        col(&mut wide),
        col(&mut meta),
        col(&mut dir),
        col(&mut pool),
        0,
        1,
        hit_threshold,
    );

    // --- compare per lane ---
    for (c, lane) in lanes.iter().enumerate() {
        let want_body = floats(&lane["body"]);
        let ao = a_bodies[c].idx * STATE_STRIDE;
        for k in 0..6 {
            assert_bits(state[ao + k], want_body[k], &format!("lane{c}.A[{k}]"));
        }
        if let Some(b) = &b_bodies[c] {
            let bo = b.idx * STATE_STRIDE;
            for k in 0..6 {
                assert_bits(state[bo + k], want_body[6 + k], &format!("lane{c}.B[{k}]"));
            }
        }

        // store wrote each lane's impulses back into its pool manifold (record c) + hit flag into dir.
        let want_mf = floats(&lane["manifold"]);
        let mpo = c * MANIFOLD_STRIDE;
        for k in 0..3 {
            assert_bits(
                pool[mpo + 3 + k],
                want_mf[k],
                &format!("lane{c}.mfFriction[{k}]"),
            );
        }
        assert_bits(pool[mpo + 6], want_mf[3], &format!("lane{c}.mfTwist"));
        for k in 0..3 {
            assert_bits(
                pool[mpo + 7 + k],
                want_mf[4 + k],
                &format!("lane{c}.mfRolling[{k}]"),
            );
        }

        let pts = lane["points"].as_array().unwrap();
        for (p, pt) in pts.iter().enumerate() {
            let want = floats(pt);
            let pp = mpo + 11 + p * 14; // M_POINTS + p * POOL_POINT_STRIDE
            assert_bits(
                pool[pp + 8],
                want[0],
                &format!("lane{c}.pt{p}.normalImpulse"),
            );
            assert_bits(
                pool[pp + 9],
                want[1],
                &format!("lane{c}.pt{p}.totalNormalImpulse"),
            );
            assert_bits(
                pool[pp + 10],
                want[2],
                &format!("lane{c}.pt{p}.normalVelocity"),
            );
        }

        let want_hit = lane["hit"].as_u64().unwrap() as u32;
        assert_eq!(dir[c * DIR_STRIDE + 11], want_hit, "lane{c}.hit");
    }
}
