//! Bit-exact parity of the convex-manifold bridge (`narrowphase::compute_convex_manifold`) against
//! the box3d C reference, read from the committed gold vectors (`src/convex_manifold.gold.json`,
//! generated by `bun run gen-convex-manifold-gold`). The bridge maps the geometry manifold the six
//! convex pair functions produce into the persistent center-of-mass-relative manifold the solver
//! reads, carrying warm-start impulses forward by feature id (contact.c b3ComputeConvexManifold).
//!
//! Each scene runs twice: cold (no previous points → nothing persists, impulses zeroed) and warm
//! (previous points seeded with the collide's own feature ids → every point persists, its impulse
//! carried forward). The hull scenes carry the raw half-edge arrays the harness dumped, rebuilt into
//! a `HullData` view exactly as `manifold_gold.rs` does.

use serde_json::Value;
use tumble_kernel::hull::{HullData, HullFace, HullHalfEdge, HullVertex};
use tumble_kernel::manifold::{Capsule, Sphere};
use tumble_kernel::math::{Plane, Quat, Transform, Vec3};
use tumble_kernel::narrowphase::{
    compute_convex_manifold, ConvexContactCache, ConvexShape, Manifold, ManifoldPoint,
};

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/convex_manifold.gold.json");

fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

fn assert_bits(got: f32, want: &str, label: &str) {
    let want_bits = u32::from_str_radix(want.trim_start_matches("0x"), 16).expect("hex");
    assert_eq!(
        got.to_bits(),
        want_bits,
        "{label}: got 0x{:08x} ({got}), want {want} ({})",
        got.to_bits(),
        from_bits(want),
    );
}

fn vec3(a: &Value) -> Vec3 {
    let a = a.as_array().unwrap();
    Vec3::new(
        from_bits(a[0].as_str().unwrap()),
        from_bits(a[1].as_str().unwrap()),
        from_bits(a[2].as_str().unwrap()),
    )
}

fn assert_vec(got: Vec3, want: &Value, label: &str) {
    let a = want.as_array().unwrap();
    assert_bits(got.x, a[0].as_str().unwrap(), &format!("{label}.x"));
    assert_bits(got.y, a[1].as_str().unwrap(), &format!("{label}.y"));
    assert_bits(got.z, a[2].as_str().unwrap(), &format!("{label}.z"));
}

fn xf(o: &Value) -> Transform {
    let p = o["p"].as_array().unwrap();
    let q = o["q"].as_array().unwrap();
    Transform {
        p: Vec3::new(
            from_bits(p[0].as_str().unwrap()),
            from_bits(p[1].as_str().unwrap()),
            from_bits(p[2].as_str().unwrap()),
        ),
        q: Quat {
            v: Vec3::new(
                from_bits(q[0].as_str().unwrap()),
                from_bits(q[1].as_str().unwrap()),
                from_bits(q[2].as_str().unwrap()),
            ),
            s: from_bits(q[3].as_str().unwrap()),
        },
    }
}

fn sphere(o: &Value) -> Sphere {
    Sphere {
        center: vec3(&o["center"]),
        radius: from_bits(o["radius"].as_str().unwrap()),
    }
}

fn capsule(o: &Value) -> Capsule {
    Capsule {
        center1: vec3(&o["center1"]),
        center2: vec3(&o["center2"]),
        radius: from_bits(o["radius"].as_str().unwrap()),
    }
}

/// Owns the hull pools parsed from JSON so a `HullData` view can borrow them.
struct HullStore {
    center: Vec3,
    vertex_count: usize,
    edge_count: usize,
    face_count: usize,
    points: Vec<Vec3>,
    vertices: Vec<HullVertex>,
    edges: Vec<HullHalfEdge>,
    faces: Vec<HullFace>,
    planes: Vec<Plane>,
}

impl HullStore {
    fn view(&self) -> HullData<'_> {
        HullData {
            center: self.center,
            vertex_count: self.vertex_count,
            edge_count: self.edge_count,
            face_count: self.face_count,
            points: &self.points,
            vertices: &self.vertices,
            edges: &self.edges,
            faces: &self.faces,
            planes: &self.planes,
        }
    }
}

fn hull(o: &Value) -> HullStore {
    let points = o["points"].as_array().unwrap().iter().map(vec3).collect();
    let vertices = o["vertices"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| HullVertex {
            edge: e.as_u64().unwrap() as usize,
        })
        .collect();
    let edges = o["edges"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| {
            let e = e.as_array().unwrap();
            HullHalfEdge {
                next: e[0].as_u64().unwrap() as usize,
                twin: e[1].as_u64().unwrap() as usize,
                origin: e[2].as_u64().unwrap() as usize,
                face: e[3].as_u64().unwrap() as usize,
            }
        })
        .collect();
    let faces = o["faces"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| HullFace {
            edge: e.as_u64().unwrap() as usize,
        })
        .collect();
    let planes = o["planes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| Plane {
            normal: vec3(&p["normal"]),
            offset: from_bits(p["offset"].as_str().unwrap()),
        })
        .collect();
    HullStore {
        center: vec3(&o["center"]),
        vertex_count: o["vertexCount"].as_u64().unwrap() as usize,
        edge_count: o["edgeCount"].as_u64().unwrap() as usize,
        face_count: o["faceCount"].as_u64().unwrap() as usize,
        points,
        vertices,
        edges,
        faces,
        planes,
    }
}

/// Seed a manifold with the run's previous points (feature id + normal impulse); the rest of each
/// point is irrelevant to the warm-start match, which reads only those two fields.
fn seed_old(run: &Value) -> Manifold {
    let mut m = Manifold::new();
    let old = run["old"].as_array().unwrap();
    m.point_count = old.len();
    for (j, o) in old.iter().enumerate() {
        let mut pt = ManifoldPoint::ZERO;
        pt.feature_id = o["featureId"].as_u64().unwrap() as u32;
        pt.normal_impulse = from_bits(o["normalImpulse"].as_str().unwrap());
        m.points[j] = pt;
    }
    m
}

/// Run both (cold + warm) runs of a scene through `compute_convex_manifold` and assert bit-for-bit.
fn check_scene(name: &str, shape_a: &ConvexShape, shape_b: &ConvexShape, scene: &Value) {
    let xf_a = xf(&scene["xfA"]);
    let xf_b = xf(&scene["xfB"]);
    for (r, run) in scene["runs"].as_array().unwrap().iter().enumerate() {
        let mut manifold = seed_old(run);
        // Fresh cache per run — the bridge gold isolates the map + warm-start, not the collide cache
        // warming (which manifold_gold.rs covers); both runs collide from a cold cache.
        let mut cache = ConvexContactCache::empty();
        let touching =
            compute_convex_manifold(&mut manifold, shape_a, xf_a, shape_b, xf_b, &mut cache);

        let want = &run["out"];
        let want_count = want["pointCount"].as_u64().unwrap() as usize;
        let label = format!("{name}[run{r}]");
        assert_eq!(touching, want_count > 0, "{label}.touching");
        assert_eq!(manifold.point_count, want_count, "{label}.pointCount");
        if want_count > 0 {
            assert_vec(manifold.normal, &want["normal"], &format!("{label}.normal"));
        }
        let pts = want["points"].as_array().unwrap();
        for i in 0..want_count {
            let pt = &manifold.points[i];
            let wp = &pts[i];
            assert_vec(
                pt.anchor_a,
                &wp["anchorA"],
                &format!("{label}.points[{i}].anchorA"),
            );
            assert_vec(
                pt.anchor_b,
                &wp["anchorB"],
                &format!("{label}.points[{i}].anchorB"),
            );
            assert_bits(
                pt.separation,
                wp["separation"].as_str().unwrap(),
                &format!("{label}.points[{i}].separation"),
            );
            assert_bits(
                pt.normal_impulse,
                wp["normalImpulse"].as_str().unwrap(),
                &format!("{label}.points[{i}].normalImpulse"),
            );
            assert_eq!(
                pt.feature_id as u64,
                wp["featureId"].as_u64().unwrap(),
                "{label}.points[{i}].featureId"
            );
            assert_eq!(
                pt.persisted,
                wp["persisted"].as_bool().unwrap(),
                "{label}.points[{i}].persisted"
            );
        }
    }
}

fn gold() -> Value {
    serde_json::from_str(GOLD).expect("parse convex_manifold.gold.json")
}

#[test]
fn spheres_bridge_bit_exact() {
    let g = gold();
    for scene in g["spheres"].as_array().unwrap() {
        let a = ConvexShape::Sphere(sphere(&scene["a"]));
        let b = ConvexShape::Sphere(sphere(&scene["b"]));
        check_scene(scene["name"].as_str().unwrap(), &a, &b, scene);
    }
}

#[test]
fn capsule_sphere_bridge_bit_exact() {
    let g = gold();
    for scene in g["capsuleSphere"].as_array().unwrap() {
        let a = ConvexShape::Capsule(capsule(&scene["a"]));
        let b = ConvexShape::Sphere(sphere(&scene["b"]));
        check_scene(scene["name"].as_str().unwrap(), &a, &b, scene);
    }
}

#[test]
fn hull_sphere_bridge_bit_exact() {
    let g = gold();
    for scene in g["hullSphere"].as_array().unwrap() {
        let store = hull(&scene["hull"]);
        let a = ConvexShape::Hull(store.view());
        let b = ConvexShape::Sphere(sphere(&scene["b"]));
        check_scene(scene["name"].as_str().unwrap(), &a, &b, scene);
    }
}

#[test]
fn capsules_bridge_bit_exact() {
    let g = gold();
    for scene in g["capsules"].as_array().unwrap() {
        let a = ConvexShape::Capsule(capsule(&scene["a"]));
        let b = ConvexShape::Capsule(capsule(&scene["b"]));
        check_scene(scene["name"].as_str().unwrap(), &a, &b, scene);
    }
}

#[test]
fn hull_capsule_bridge_bit_exact() {
    let g = gold();
    for scene in g["hullCapsule"].as_array().unwrap() {
        let store = hull(&scene["hull"]);
        let a = ConvexShape::Hull(store.view());
        let b = ConvexShape::Capsule(capsule(&scene["b"]));
        check_scene(scene["name"].as_str().unwrap(), &a, &b, scene);
    }
}

#[test]
fn hulls_bridge_bit_exact() {
    let g = gold();
    for scene in g["hulls"].as_array().unwrap() {
        let a_store = hull(&scene["hullA"]);
        let b_store = hull(&scene["hullB"]);
        let a = ConvexShape::Hull(a_store.view());
        let b = ConvexShape::Hull(b_store.view());
        check_scene(scene["name"].as_str().unwrap(), &a, &b, scene);
    }
}
