//! Bit-exact parity of the Rust GJK `shape_distance` against the box3d C reference, read from the
//! committed gold vectors the TS port also verifies against (`src/distance.gold.json`, generated by
//! `bun run gen-distance-gold`). Mirrors the `shapeDistance` gate in `src/distance.test.ts`: the
//! named integer point clouds are the same ones `fixtures/distance_gold.c` collides. Proves the GJK
//! port bit-for-bit before the narrowphase (which consumes it) is verified on top.

use serde_json::Value;
use tumble_kernel::distance::{shape_distance, DistanceInput, ShapeProxy, SimplexCache};
use tumble_kernel::math::{Quat, Transform, Vec3};

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/distance.gold.json");

fn from_bits(hex: &str) -> f32 {
    let bits = u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex");
    f32::from_bits(bits)
}

fn assert_bits(got: f32, want: &str, label: &str) {
    let want_bits = u32::from_str_radix(want.trim_start_matches("0x"), 16).expect("hex");
    assert_eq!(
        got.to_bits(),
        want_bits,
        "{label}: got 0x{:08x} ({got}), want {want} ({})",
        got.to_bits(),
        from_bits(want),
    );
}

fn assert_vec(got: Vec3, want: &Value, label: &str) {
    let a = want.as_array().unwrap();
    assert_bits(got.x, a[0].as_str().unwrap(), &format!("{label}.x"));
    assert_bits(got.y, a[1].as_str().unwrap(), &format!("{label}.y"));
    assert_bits(got.z, a[2].as_str().unwrap(), &format!("{label}.z"));
}

fn xf_from_hex(o: &Value) -> Transform {
    let p = o["p"].as_array().unwrap();
    let q = o["q"].as_array().unwrap();
    Transform {
        p: Vec3::new(
            from_bits(p[0].as_str().unwrap()),
            from_bits(p[1].as_str().unwrap()),
            from_bits(p[2].as_str().unwrap()),
        ),
        q: Quat {
            v: Vec3::new(
                from_bits(q[0].as_str().unwrap()),
                from_bits(q[1].as_str().unwrap()),
                from_bits(q[2].as_str().unwrap()),
            ),
            s: from_bits(q[3].as_str().unwrap()),
        },
    }
}

// Named proxy point clouds, integer coords mirroring fixtures/distance_gold.c exactly (and the
// POINTS map in src/distance.test.ts).
fn points(name: &str) -> Vec<Vec3> {
    let v = |x: f32, y: f32, z: f32| Vec3::new(x, y, z);
    match name {
        "box8" => vec![
            v(-1.0, -1.0, -1.0),
            v(1.0, -1.0, -1.0),
            v(1.0, 1.0, -1.0),
            v(-1.0, 1.0, -1.0),
            v(-1.0, -1.0, 1.0),
            v(1.0, -1.0, 1.0),
            v(1.0, 1.0, 1.0),
            v(-1.0, 1.0, 1.0),
        ],
        "quad4" => vec![
            v(-1.0, -1.0, 0.0),
            v(1.0, -1.0, 0.0),
            v(1.0, 1.0, 0.0),
            v(-1.0, 1.0, 0.0),
        ],
        "segB" => vec![v(2.0, -1.0, 0.0), v(2.0, 1.0, 0.0)],
        "seg0" => vec![v(0.0, -1.0, 0.0), v(0.0, 1.0, 0.0)],
        "pt1" => vec![v(0.0, 0.0, 0.0)],
        _ => panic!("unknown proxy {name}"),
    }
}

#[test]
fn shape_distance_bit_exact() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse distance.gold.json");
    let cases = gold["distance"].as_array().expect("distance array");

    for g in cases {
        let name = g["name"].as_str().unwrap();
        let pa = points(g["proxyA"].as_str().unwrap());
        let pb = points(g["proxyB"].as_str().unwrap());
        let radius_a = from_bits(g["radiusA"].as_str().unwrap());
        let radius_b = from_bits(g["radiusB"].as_str().unwrap());
        let use_radii = g["useRadii"].as_bool().unwrap();
        let transform = xf_from_hex(&g["transform"]);

        let input = DistanceInput {
            proxy_a: ShapeProxy {
                points: &pa,
                count: pa.len(),
                radius: radius_a,
            },
            proxy_b: ShapeProxy {
                points: &pb,
                count: pb.len(),
                radius: radius_b,
            },
            transform,
            use_radii,
        };
        let mut cache = SimplexCache::empty();
        let out = shape_distance(&input, &mut cache);

        let want = &g["out"];
        assert_vec(out.point_a, &want["pointA"], &format!("{name} pointA"));
        assert_vec(out.point_b, &want["pointB"], &format!("{name} pointB"));
        assert_vec(out.normal, &want["normal"], &format!("{name} normal"));
        assert_bits(
            out.distance,
            want["distance"].as_str().unwrap(),
            &format!("{name} distance"),
        );
        assert_eq!(
            out.iterations as i64,
            want["iterations"].as_i64().unwrap(),
            "{name} iterations"
        );

        // Cache is written only on the non-overlap exit; on overlap C leaves it untouched (count 0).
        let wc = &want["cache"];
        assert_bits(
            cache.metric,
            wc["metric"].as_str().unwrap(),
            &format!("{name} cache.metric"),
        );
        let want_count = wc["count"].as_u64().unwrap() as usize;
        assert_eq!(cache.count, want_count, "{name} cache.count");
        let wia = wc["indexA"].as_array().unwrap();
        let wib = wc["indexB"].as_array().unwrap();
        for i in 0..cache.count {
            assert_eq!(
                cache.index_a[i] as u64,
                wia[i].as_u64().unwrap(),
                "{name} cache.indexA[{i}]"
            );
            assert_eq!(
                cache.index_b[i] as u64,
                wib[i].as_u64().unwrap(),
                "{name} cache.indexB[{i}]"
            );
        }
    }
}
