//! Bit-exact parity of the Rust joint solver against the box3d C reference, read from the committed
//! gold vectors (`src/joint.gold.json`, generated by `bun run gen-joint-gold`). The generator
//! transcribes `src/joint.c` (base prepare) + `src/distance_joint.c` (prepare / warm-start / solve)
//! over the real b3 math library; this drives the Rust port over one marshaled joint record + a
//! two-body resident state column and asserts every prepared field, velocity, and impulse bit-for-bit.

use serde_json::Value;
use tumble_kernel::body::flags::DYNAMIC;
use tumble_kernel::body::{write_state, State, STATE_STRIDE};
use tumble_kernel::col::Col;
use tumble_kernel::joint::{prepare, solve, warm_start};
use tumble_kernel::joint_abi::{
    get, get_vec3, DJ_ANCHOR_A, DJ_ANCHOR_B, DJ_AXIAL_MASS, DJ_DAMPING_RATIO, DJ_DELTA_CENTER,
    DJ_DIST_SOFTNESS, DJ_ENABLE, DJ_ENABLE_LIMIT, DJ_ENABLE_MOTOR, DJ_ENABLE_SPRING, DJ_HERTZ,
    DJ_IMPULSE, DJ_LENGTH, DJ_LOWER_IMPULSE, DJ_LOWER_SPRING_FORCE, DJ_MAX_LENGTH, DJ_MAX_MOTOR_FORCE,
    DJ_MIN_LENGTH, DJ_MOTOR_IMPULSE, DJ_MOTOR_SPEED, DJ_UPPER_IMPULSE, DJ_UPPER_SPRING_FORCE,
    JOINT_STRIDE, J_CENTER_A, J_CENTER_B, J_CONSTRAINT_DAMPING, J_CONSTRAINT_HERTZ,
    J_CONSTRAINT_SOFTNESS, J_INV_IA, J_INV_IB, J_INV_MASS_A, J_INV_MASS_B, J_LOCAL_CENTER_A,
    J_LOCAL_CENTER_B, J_LOCAL_FRAME_A, J_LOCAL_FRAME_B, J_QA, J_QB, J_SIM_INDEX_A, J_SIM_INDEX_B,
    J_TYPE, MJ_ANGULAR_DAMPING_RATIO, MJ_ANGULAR_HERTZ, MJ_ANGULAR_SPRING_IMPULSE,
    MJ_ANGULAR_VELOCITY, MJ_ANGULAR_VELOCITY_IMPULSE, MJ_LINEAR_DAMPING_RATIO, MJ_LINEAR_HERTZ,
    MJ_LINEAR_SPRING_IMPULSE, MJ_LINEAR_VELOCITY, MJ_LINEAR_VELOCITY_IMPULSE, MJ_MAX_SPRING_FORCE,
    MJ_MAX_SPRING_TORQUE, MJ_MAX_VELOCITY_FORCE, MJ_MAX_VELOCITY_TORQUE, NULL_INDEX,
    PLJ_DAMPING_RATIO, PLJ_HERTZ, PLJ_MAX_TORQUE, PLJ_PERP_IMPULSE,
    PJ_ANGULAR_IMPULSE, PJ_DAMPING_RATIO, PJ_ENABLE, PJ_ENABLE_LIMIT,
    PJ_ENABLE_MOTOR, PJ_ENABLE_SPRING, PJ_HERTZ, PJ_LOWER_IMPULSE, PJ_LOWER_TRANSLATION,
    PJ_MAX_MOTOR_FORCE, PJ_MOTOR_IMPULSE, PJ_MOTOR_SPEED, PJ_PERP_IMPULSE, PJ_SPRING_IMPULSE,
    PJ_TARGET_TRANSLATION, PJ_UPPER_IMPULSE, PJ_UPPER_TRANSLATION, RJ_DAMPING_RATIO, RJ_ENABLE,
    RJ_ENABLE_LIMIT, RJ_ENABLE_MOTOR,
    RJ_ENABLE_SPRING, RJ_HERTZ, RJ_LINEAR_IMPULSE, RJ_LOWER_ANGLE, RJ_LOWER_IMPULSE,
    RJ_MAX_MOTOR_TORQUE, RJ_MOTOR_IMPULSE, RJ_MOTOR_SPEED, RJ_PERP_IMPULSE, RJ_SPRING_IMPULSE,
    RJ_TARGET_ANGLE, RJ_UPPER_ANGLE, RJ_UPPER_IMPULSE, SJ_CONE_ANGLE, SJ_DAMPING_RATIO, SJ_ENABLE,
    SJ_ENABLE_CONE_LIMIT, SJ_ENABLE_MOTOR, SJ_ENABLE_SPRING, SJ_ENABLE_TWIST_LIMIT, SJ_HERTZ,
    SJ_LINEAR_IMPULSE, SJ_LOWER_TWIST_ANGLE, SJ_LOWER_TWIST_IMPULSE, SJ_MAX_MOTOR_TORQUE,
    SJ_MOTOR_IMPULSE, SJ_MOTOR_VELOCITY, SJ_SPRING_IMPULSE, SJ_SWING_IMPULSE, SJ_TARGET_ROTATION,
    SJ_UPPER_TWIST_ANGLE, SJ_UPPER_TWIST_IMPULSE, TY_DISTANCE, TY_MOTOR, TY_PARALLEL, TY_PRISMATIC,
    TY_REVOLUTE, TY_SPHERICAL, TY_WELD, TY_WHEEL, WHJ_ANGULAR_IMPULSE, WHJ_ENABLE, WHJ_ENABLE_SPIN_MOTOR,
    WHJ_ENABLE_STEERING, WHJ_ENABLE_STEERING_LIMIT, WHJ_ENABLE_SUSPENSION_LIMIT,
    WHJ_ENABLE_SUSPENSION_SPRING, WHJ_LINEAR_IMPULSE, WHJ_LOWER_STEERING_IMPULSE,
    WHJ_LOWER_STEERING_LIMIT, WHJ_LOWER_SUSPENSION_IMPULSE, WHJ_LOWER_SUSPENSION_LIMIT,
    WHJ_MAX_SPIN_TORQUE, WHJ_MAX_STEERING_TORQUE, WHJ_SPIN_IMPULSE, WHJ_SPIN_SPEED,
    WHJ_STEERING_DAMPING_RATIO, WHJ_STEERING_HERTZ, WHJ_STEERING_SPRING_IMPULSE,
    WHJ_SUSPENSION_DAMPING_RATIO, WHJ_SUSPENSION_HERTZ, WHJ_SUSPENSION_SPRING_IMPULSE,
    WHJ_TARGET_STEERING_ANGLE, WHJ_UPPER_STEERING_IMPULSE, WHJ_UPPER_STEERING_LIMIT,
    WHJ_UPPER_SUSPENSION_IMPULSE, WHJ_UPPER_SUSPENSION_LIMIT, WJ_ANGULAR_DAMPING_RATIO,
    WJ_ANGULAR_HERTZ, WJ_ANGULAR_IMPULSE, WJ_LINEAR_DAMPING_RATIO, WJ_LINEAR_HERTZ,
    WJ_LINEAR_IMPULSE,
};

/// SAFETY: a gold harness is single-threaded and each column has exactly one user, so `Col`'s
/// disjoint-write promise holds trivially.
fn col<T: Copy>(v: &mut [T]) -> Col<'_, T> {
    unsafe { Col::of(v) }
}

const GOLD: &str = include_str!("../../../src/standard/tumble/engine/joint.gold.json");

fn from_bits(hex: &str) -> f32 {
    f32::from_bits(u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex"))
}
fn f(v: &Value, key: &str) -> f32 {
    from_bits(v[key].as_str().expect("hex str"))
}
fn arr(v: &Value, key: &str) -> Vec<f32> {
    v[key]
        .as_array()
        .expect("array")
        .iter()
        .map(|e| from_bits(e.as_str().expect("hex str")))
        .collect()
}
fn assert_bits(got: f32, want: f32, label: &str) {
    assert_eq!(
        got.to_bits(),
        want.to_bits(),
        "{label}: got 0x{:08x} ({got}), want 0x{:08x} ({want})",
        got.to_bits(),
        want.to_bits(),
    );
}

/// Build the marshaled joint column (one slot) + a two-body resident state column from a scenario's
/// `input`, exactly as `src/jointcolumns.ts` will: TS writes the two sim indices, invMass/invInertia,
/// the pose fields, the local frames, the base constraint frequency, the type config, and the starting
/// impulses; the kernel derives the anchors + softness in `prepare`.
fn setup(input: &Value) -> (Vec<f32>, Vec<f32>, Vec<u32>) {
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(J_TYPE, f32::from_bits(TY_DISTANCE));
        set(J_SIM_INDEX_A, f32::from_bits(0));
        set(
            J_SIM_INDEX_B,
            f32::from_bits(if b_static { NULL_INDEX } else { 1 }),
        );
        set(J_INV_MASS_A, f(input, "invMassA"));
        set(J_INV_MASS_B, f(input, "invMassB"));
        for (i, x) in arr(input, "invIA").iter().enumerate() {
            set(J_INV_IA + i, *x);
        }
        for (i, x) in arr(input, "invIB").iter().enumerate() {
            set(J_INV_IB + i, *x);
        }
        for (i, x) in arr(input, "qA").iter().enumerate() {
            set(J_QA + i, *x);
        }
        for (i, x) in arr(input, "localCenterA").iter().enumerate() {
            set(J_LOCAL_CENTER_A + i, *x);
        }
        for (i, x) in arr(input, "centerA").iter().enumerate() {
            set(J_CENTER_A + i, *x);
        }
        for (i, x) in arr(input, "qB").iter().enumerate() {
            set(J_QB + i, *x);
        }
        for (i, x) in arr(input, "localCenterB").iter().enumerate() {
            set(J_LOCAL_CENTER_B + i, *x);
        }
        for (i, x) in arr(input, "centerB").iter().enumerate() {
            set(J_CENTER_B + i, *x);
        }
        // local frames: only the anchor point .p is set by these scenarios (.q identity/zeroed).
        for (i, x) in arr(input, "localFrameAp").iter().enumerate() {
            set(J_LOCAL_FRAME_A + i, *x);
        }
        for (i, x) in arr(input, "localFrameBp").iter().enumerate() {
            set(J_LOCAL_FRAME_B + i, *x);
        }
        set(J_CONSTRAINT_HERTZ, f(input, "constraintHertz"));
        set(J_CONSTRAINT_DAMPING, f(input, "constraintDamping"));
        set(DJ_LENGTH, f(input, "length"));
        set(DJ_HERTZ, f(input, "hertz"));
        set(DJ_DAMPING_RATIO, f(input, "dampingRatio"));
        set(DJ_LOWER_SPRING_FORCE, f(input, "lowerSpringForce"));
        set(DJ_UPPER_SPRING_FORCE, f(input, "upperSpringForce"));
        set(DJ_MIN_LENGTH, f(input, "minLength"));
        set(DJ_MAX_LENGTH, f(input, "maxLength"));
        set(DJ_MAX_MOTOR_FORCE, f(input, "maxMotorForce"));
        set(DJ_MOTOR_SPEED, f(input, "motorSpeed"));
        let enable = (if input["enableSpring"].as_i64().unwrap() != 0 { DJ_ENABLE_SPRING } else { 0 })
            | (if input["enableLimit"].as_i64().unwrap() != 0 { DJ_ENABLE_LIMIT } else { 0 })
            | (if input["enableMotor"].as_i64().unwrap() != 0 { DJ_ENABLE_MOTOR } else { 0 });
        set(DJ_ENABLE, f32::from_bits(enable));
        set(DJ_IMPULSE, f(input, "impulse"));
        set(DJ_LOWER_IMPULSE, f(input, "lowerImpulse"));
        set(DJ_UPPER_IMPULSE, f(input, "upperImpulse"));
        set(DJ_MOTOR_IMPULSE, f(input, "motorImpulse"));
    }

    // Two-body resident state column: body 0 = A (dynamic), body 1 = B (dynamic unless static).
    let mut state = vec![0.0f32; 2 * STATE_STRIDE];
    let mut flags = vec![0u32; 2];
    {
        let sc = col(&mut state);
        let va = arr(input, "vA");
        let wa = arr(input, "wA");
        let dpa = arr(input, "dpA");
        let dqa = arr(input, "dqA");
        write_state(sc, 0, &state_of(&va, &wa, &dpa, &dqa));
        let vb = arr(input, "vB");
        let wb = arr(input, "wB");
        let dpb = arr(input, "dpB");
        let dqb = arr(input, "dqB");
        write_state(sc, 1, &state_of(&vb, &wb, &dpb, &dqb));
    }
    flags[0] = DYNAMIC;
    flags[1] = if b_static { 0 } else { DYNAMIC };

    (joints, state, flags)
}

fn state_of(v: &[f32], w: &[f32], dp: &[f32], dq: &[f32]) -> State {
    use tumble_kernel::math::{Quat, Vec3};
    State {
        linear_velocity: Vec3::new(v[0], v[1], v[2]),
        angular_velocity: Vec3::new(w[0], w[1], w[2]),
        delta_position: Vec3::new(dp[0], dp[1], dp[2]),
        delta_rotation: Quat {
            v: Vec3::new(dq[0], dq[1], dq[2]),
            s: dq[3],
        },
    }
}

fn vel(state: &mut [f32], i: usize) -> ([f32; 3], [f32; 3]) {
    let o = i * STATE_STRIDE;
    (
        [state[o], state[o + 1], state[o + 2]],
        [state[o + 3], state[o + 4], state[o + 5]],
    )
}

fn run_scenario(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let (mut joints, mut state, mut flags) = setup(input);

    // prepare ---------------------------------------------------------------------------------
    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
        let g = &sc["prepare"];
        let an_a = arr(g, "anchorA");
        let an_b = arr(g, "anchorB");
        let dc = arr(g, "deltaCenter");
        let a = get_vec3(jc, 0, DJ_ANCHOR_A);
        assert_bits(a.x, an_a[0], &format!("{name}/prepare anchorA.x"));
        assert_bits(a.y, an_a[1], &format!("{name}/prepare anchorA.y"));
        assert_bits(a.z, an_a[2], &format!("{name}/prepare anchorA.z"));
        let b = get_vec3(jc, 0, DJ_ANCHOR_B);
        assert_bits(b.x, an_b[0], &format!("{name}/prepare anchorB.x"));
        assert_bits(b.y, an_b[1], &format!("{name}/prepare anchorB.y"));
        assert_bits(b.z, an_b[2], &format!("{name}/prepare anchorB.z"));
        let d = get_vec3(jc, 0, DJ_DELTA_CENTER);
        assert_bits(d.x, dc[0], &format!("{name}/prepare deltaCenter.x"));
        assert_bits(d.y, dc[1], &format!("{name}/prepare deltaCenter.y"));
        assert_bits(d.z, dc[2], &format!("{name}/prepare deltaCenter.z"));
        assert_bits(get(jc, 0, DJ_AXIAL_MASS), f(g, "axialMass"), &format!("{name}/prepare axialMass"));
        let ds = arr(g, "distSoftness");
        for k in 0..3 {
            assert_bits(get(jc, 0, DJ_DIST_SOFTNESS + k), ds[k], &format!("{name}/prepare distSoftness[{k}]"));
        }
        let cs = arr(g, "constraintSoftness");
        for k in 0..3 {
            assert_bits(get(jc, 0, J_CONSTRAINT_SOFTNESS + k), cs[k], &format!("{name}/prepare constraintSoftness[{k}]"));
        }
        assert_bits(get(jc, 0, DJ_IMPULSE), f(g, "impulse"), &format!("{name}/prepare impulse"));
        assert_bits(get(jc, 0, DJ_LOWER_IMPULSE), f(g, "lowerImpulse"), &format!("{name}/prepare lowerImpulse"));
        assert_bits(get(jc, 0, DJ_UPPER_IMPULSE), f(g, "upperImpulse"), &format!("{name}/prepare upperImpulse"));
        assert_bits(get(jc, 0, DJ_MOTOR_IMPULSE), f(g, "motorImpulse"), &format!("{name}/prepare motorImpulse"));
    }

    // warm start ------------------------------------------------------------------------------
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart", None);

    // solve (biased) --------------------------------------------------------------------------
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        solve(jc, 0, sc2, fc, true, h, inv_h);
    }
    check_vels(&sc["solveBias"], &mut state, b_static, name, "solveBias", Some(&joints));

    // relax (unbiased) ------------------------------------------------------------------------
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        solve(jc, 0, sc2, fc, false, h, inv_h);
    }
    check_vels(&sc["solveRelax"], &mut state, b_static, name, "solveRelax", Some(&joints));
}

fn check_vels(
    g: &Value,
    state: &mut [f32],
    b_static: bool,
    name: &str,
    phase: &str,
    joints: Option<&[f32]>,
) {
    let va = arr(g, "vA");
    let wa = arr(g, "wA");
    let (v0, w0) = vel(state, 0);
    for k in 0..3 {
        assert_bits(v0[k], va[k], &format!("{name}/{phase} vA[{k}]"));
        assert_bits(w0[k], wa[k], &format!("{name}/{phase} wA[{k}]"));
    }
    if !b_static {
        let vb = arr(g, "vB");
        let wb = arr(g, "wB");
        let (v1, w1) = vel(state, 1);
        for k in 0..3 {
            assert_bits(v1[k], vb[k], &format!("{name}/{phase} vB[{k}]"));
            assert_bits(w1[k], wb[k], &format!("{name}/{phase} wB[{k}]"));
        }
    }
    if let Some(joints) = joints {
        let mut jv = joints.to_vec();
        let jc = col(&mut jv);
        assert_bits(get(jc, 0, DJ_IMPULSE), f(g, "impulse"), &format!("{name}/{phase} impulse"));
        assert_bits(get(jc, 0, DJ_LOWER_IMPULSE), f(g, "lowerImpulse"), &format!("{name}/{phase} lowerImpulse"));
        assert_bits(get(jc, 0, DJ_UPPER_IMPULSE), f(g, "upperImpulse"), &format!("{name}/{phase} upperImpulse"));
        assert_bits(get(jc, 0, DJ_MOTOR_IMPULSE), f(g, "motorImpulse"), &format!("{name}/{phase} motorImpulse"));
    }
}

#[test]
fn distance_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["scenarios"].as_array().expect("scenarios array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_scenario(sc);
    }
}

// --- shared header + state builders (revolute/spherical/weld reuse) ----------------------------

/// Write one joint's common header — type, sim indices, invMass/invInertia, the pose fields, and the
/// full local frames (p + q) — exactly as `src/jointcolumns.ts` marshals it. Body 0 = A, body 1 = B.
fn write_base(jc: Col<f32>, input: &Value, ty: u32) {
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let set = |field: usize, val: f32| jc.set(field, val);
    set(J_TYPE, f32::from_bits(ty));
    set(J_SIM_INDEX_A, f32::from_bits(0));
    set(
        J_SIM_INDEX_B,
        f32::from_bits(if b_static { NULL_INDEX } else { 1 }),
    );
    set(J_INV_MASS_A, f(input, "invMassA"));
    set(J_INV_MASS_B, f(input, "invMassB"));
    for (i, x) in arr(input, "invIA").iter().enumerate() {
        set(J_INV_IA + i, *x);
    }
    for (i, x) in arr(input, "invIB").iter().enumerate() {
        set(J_INV_IB + i, *x);
    }
    for (i, x) in arr(input, "qA").iter().enumerate() {
        set(J_QA + i, *x);
    }
    for (i, x) in arr(input, "localCenterA").iter().enumerate() {
        set(J_LOCAL_CENTER_A + i, *x);
    }
    for (i, x) in arr(input, "centerA").iter().enumerate() {
        set(J_CENTER_A + i, *x);
    }
    for (i, x) in arr(input, "qB").iter().enumerate() {
        set(J_QB + i, *x);
    }
    for (i, x) in arr(input, "localCenterB").iter().enumerate() {
        set(J_LOCAL_CENTER_B + i, *x);
    }
    for (i, x) in arr(input, "centerB").iter().enumerate() {
        set(J_CENTER_B + i, *x);
    }
    for (i, x) in arr(input, "localFrameAp").iter().enumerate() {
        set(J_LOCAL_FRAME_A + i, *x);
    }
    for (i, x) in arr(input, "localFrameAq").iter().enumerate() {
        set(J_LOCAL_FRAME_A + 3 + i, *x);
    }
    for (i, x) in arr(input, "localFrameBp").iter().enumerate() {
        set(J_LOCAL_FRAME_B + i, *x);
    }
    for (i, x) in arr(input, "localFrameBq").iter().enumerate() {
        set(J_LOCAL_FRAME_B + 3 + i, *x);
    }
    set(J_CONSTRAINT_HERTZ, f(input, "constraintHertz"));
    set(J_CONSTRAINT_DAMPING, f(input, "constraintDamping"));
}

/// The two-body resident state column + flags from a scenario's `input`.
fn build_state(input: &Value) -> (Vec<f32>, Vec<u32>) {
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let mut state = vec![0.0f32; 2 * STATE_STRIDE];
    let mut flags = vec![0u32; 2];
    {
        let sc = col(&mut state);
        write_state(
            sc,
            0,
            &state_of(
                &arr(input, "vA"),
                &arr(input, "wA"),
                &arr(input, "dpA"),
                &arr(input, "dqA"),
            ),
        );
        write_state(
            sc,
            1,
            &state_of(
                &arr(input, "vB"),
                &arr(input, "wB"),
                &arr(input, "dpB"),
                &arr(input, "dqB"),
            ),
        );
    }
    flags[0] = DYNAMIC;
    flags[1] = if b_static { 0 } else { DYNAMIC };
    (state, flags)
}

/// Assert body A's velocities (always) and body B's (unless static) against a gold velocity block.
fn check_body_vels(g: &Value, state: &mut [f32], b_static: bool, name: &str, phase: &str) {
    let va = arr(g, "vA");
    let wa = arr(g, "wA");
    let (v0, w0) = vel(state, 0);
    for k in 0..3 {
        assert_bits(v0[k], va[k], &format!("{name}/{phase} vA[{k}]"));
        assert_bits(w0[k], wa[k], &format!("{name}/{phase} wA[{k}]"));
    }
    if !b_static {
        let vb = arr(g, "vB");
        let wb = arr(g, "wB");
        let (v1, w1) = vel(state, 1);
        for k in 0..3 {
            assert_bits(v1[k], vb[k], &format!("{name}/{phase} vB[{k}]"));
            assert_bits(w1[k], wb[k], &format!("{name}/{phase} wB[{k}]"));
        }
    }
}

/// Assert a vec3 field of the joint column against a gold vec3.
fn check_vec3(joints: &[f32], field: usize, want: &[f32], name: &str, label: &str) {
    let mut jv = joints.to_vec();
    let jc = col(&mut jv);
    let got = get_vec3(jc, 0, field);
    assert_bits(got.x, want[0], &format!("{name}/{label}.x"));
    assert_bits(got.y, want[1], &format!("{name}/{label}.y"));
    assert_bits(got.z, want[2], &format!("{name}/{label}.z"));
}

// --- weld -------------------------------------------------------------------------------------

fn run_weld(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_WELD);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(WJ_LINEAR_HERTZ, f(input, "linearHertz"));
        set(WJ_LINEAR_DAMPING_RATIO, f(input, "linearDampingRatio"));
        set(WJ_ANGULAR_HERTZ, f(input, "angularHertz"));
        set(WJ_ANGULAR_DAMPING_RATIO, f(input, "angularDampingRatio"));
        for (i, x) in arr(input, "linearImpulse").iter().enumerate() {
            set(WJ_LINEAR_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "angularImpulse").iter().enumerate() {
            set(WJ_ANGULAR_IMPULSE + i, *x);
        }
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        check_vec3(
            &joints,
            WJ_LINEAR_IMPULSE,
            &arr(g, "linearImpulse"),
            name,
            &format!("{phase} linearImpulse"),
        );
        check_vec3(
            &joints,
            WJ_ANGULAR_IMPULSE,
            &arr(g, "angularImpulse"),
            name,
            &format!("{phase} angularImpulse"),
        );
    }
}

#[test]
fn weld_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["weld"].as_array().expect("weld array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_weld(sc);
    }
}

/// Assert a scalar field of the joint column against a gold scalar.
fn check_scalar(joints: &[f32], field: usize, want: f32, name: &str, label: &str) {
    let mut jv = joints.to_vec();
    let jc = col(&mut jv);
    assert_bits(get(jc, 0, field), want, &format!("{name}/{label}"));
}

// --- revolute ---------------------------------------------------------------------------------

fn run_revolute(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_REVOLUTE);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(RJ_HERTZ, f(input, "hertz"));
        set(RJ_DAMPING_RATIO, f(input, "dampingRatio"));
        set(RJ_MAX_MOTOR_TORQUE, f(input, "maxMotorTorque"));
        set(RJ_MOTOR_SPEED, f(input, "motorSpeed"));
        set(RJ_TARGET_ANGLE, f(input, "targetAngle"));
        set(RJ_LOWER_ANGLE, f(input, "lowerAngle"));
        set(RJ_UPPER_ANGLE, f(input, "upperAngle"));
        let enable = (if input["enableSpring"].as_i64().unwrap() != 0 { RJ_ENABLE_SPRING } else { 0 })
            | (if input["enableMotor"].as_i64().unwrap() != 0 { RJ_ENABLE_MOTOR } else { 0 })
            | (if input["enableLimit"].as_i64().unwrap() != 0 { RJ_ENABLE_LIMIT } else { 0 });
        set(RJ_ENABLE, f32::from_bits(enable));
        for (i, x) in arr(input, "linearImpulse").iter().enumerate() {
            set(RJ_LINEAR_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "perpImpulse").iter().enumerate() {
            set(RJ_PERP_IMPULSE + i, *x);
        }
        set(RJ_SPRING_IMPULSE, f(input, "springImpulse"));
        set(RJ_MOTOR_IMPULSE, f(input, "motorImpulse"));
        set(RJ_LOWER_IMPULSE, f(input, "lowerImpulse"));
        set(RJ_UPPER_IMPULSE, f(input, "upperImpulse"));
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        check_vec3(
            &joints,
            RJ_LINEAR_IMPULSE,
            &arr(g, "linearImpulse"),
            name,
            &format!("{phase} linearImpulse"),
        );
        let perp = arr(g, "perpImpulse");
        check_scalar(&joints, RJ_PERP_IMPULSE, perp[0], name, &format!("{phase} perpImpulse.x"));
        check_scalar(&joints, RJ_PERP_IMPULSE + 1, perp[1], name, &format!("{phase} perpImpulse.y"));
        check_scalar(&joints, RJ_SPRING_IMPULSE, f(g, "springImpulse"), name, &format!("{phase} springImpulse"));
        check_scalar(&joints, RJ_MOTOR_IMPULSE, f(g, "motorImpulse"), name, &format!("{phase} motorImpulse"));
        check_scalar(&joints, RJ_LOWER_IMPULSE, f(g, "lowerImpulse"), name, &format!("{phase} lowerImpulse"));
        check_scalar(&joints, RJ_UPPER_IMPULSE, f(g, "upperImpulse"), name, &format!("{phase} upperImpulse"));
    }
}

#[test]
fn revolute_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["revolute"].as_array().expect("revolute array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_revolute(sc);
    }
}

// --- spherical --------------------------------------------------------------------------------

fn run_spherical(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_SPHERICAL);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(SJ_HERTZ, f(input, "hertz"));
        set(SJ_DAMPING_RATIO, f(input, "dampingRatio"));
        set(SJ_MAX_MOTOR_TORQUE, f(input, "maxMotorTorque"));
        for (i, x) in arr(input, "motorVelocity").iter().enumerate() {
            set(SJ_MOTOR_VELOCITY + i, *x);
        }
        set(SJ_LOWER_TWIST_ANGLE, f(input, "lowerTwistAngle"));
        set(SJ_UPPER_TWIST_ANGLE, f(input, "upperTwistAngle"));
        set(SJ_CONE_ANGLE, f(input, "coneAngle"));
        for (i, x) in arr(input, "targetRotation").iter().enumerate() {
            set(SJ_TARGET_ROTATION + i, *x);
        }
        let enable = (if input["enableSpring"].as_i64().unwrap() != 0 { SJ_ENABLE_SPRING } else { 0 })
            | (if input["enableMotor"].as_i64().unwrap() != 0 { SJ_ENABLE_MOTOR } else { 0 })
            | (if input["enableConeLimit"].as_i64().unwrap() != 0 { SJ_ENABLE_CONE_LIMIT } else { 0 })
            | (if input["enableTwistLimit"].as_i64().unwrap() != 0 { SJ_ENABLE_TWIST_LIMIT } else { 0 });
        set(SJ_ENABLE, f32::from_bits(enable));
        for (i, x) in arr(input, "linearImpulse").iter().enumerate() {
            set(SJ_LINEAR_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "springImpulse").iter().enumerate() {
            set(SJ_SPRING_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "motorImpulse").iter().enumerate() {
            set(SJ_MOTOR_IMPULSE + i, *x);
        }
        set(SJ_LOWER_TWIST_IMPULSE, f(input, "lowerTwistImpulse"));
        set(SJ_UPPER_TWIST_IMPULSE, f(input, "upperTwistImpulse"));
        set(SJ_SWING_IMPULSE, f(input, "swingImpulse"));
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        check_vec3(&joints, SJ_LINEAR_IMPULSE, &arr(g, "linearImpulse"), name, &format!("{phase} linearImpulse"));
        check_vec3(&joints, SJ_SPRING_IMPULSE, &arr(g, "springImpulse"), name, &format!("{phase} springImpulse"));
        check_vec3(&joints, SJ_MOTOR_IMPULSE, &arr(g, "motorImpulse"), name, &format!("{phase} motorImpulse"));
        check_scalar(&joints, SJ_LOWER_TWIST_IMPULSE, f(g, "lowerTwistImpulse"), name, &format!("{phase} lowerTwistImpulse"));
        check_scalar(&joints, SJ_UPPER_TWIST_IMPULSE, f(g, "upperTwistImpulse"), name, &format!("{phase} upperTwistImpulse"));
        check_scalar(&joints, SJ_SWING_IMPULSE, f(g, "swingImpulse"), name, &format!("{phase} swingImpulse"));
    }
}

#[test]
fn spherical_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["spherical"].as_array().expect("spherical array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_spherical(sc);
    }
}

// --- prismatic --------------------------------------------------------------------------------

fn run_prismatic(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_PRISMATIC);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(PJ_HERTZ, f(input, "hertz"));
        set(PJ_DAMPING_RATIO, f(input, "dampingRatio"));
        set(PJ_MAX_MOTOR_FORCE, f(input, "maxMotorForce"));
        set(PJ_MOTOR_SPEED, f(input, "motorSpeed"));
        set(PJ_TARGET_TRANSLATION, f(input, "targetTranslation"));
        set(PJ_LOWER_TRANSLATION, f(input, "lowerTranslation"));
        set(PJ_UPPER_TRANSLATION, f(input, "upperTranslation"));
        let enable = (if input["enableSpring"].as_i64().unwrap() != 0 { PJ_ENABLE_SPRING } else { 0 })
            | (if input["enableMotor"].as_i64().unwrap() != 0 { PJ_ENABLE_MOTOR } else { 0 })
            | (if input["enableLimit"].as_i64().unwrap() != 0 { PJ_ENABLE_LIMIT } else { 0 });
        set(PJ_ENABLE, f32::from_bits(enable));
        for (i, x) in arr(input, "perpImpulse").iter().enumerate() {
            set(PJ_PERP_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "angularImpulse").iter().enumerate() {
            set(PJ_ANGULAR_IMPULSE + i, *x);
        }
        set(PJ_SPRING_IMPULSE, f(input, "springImpulse"));
        set(PJ_MOTOR_IMPULSE, f(input, "motorImpulse"));
        set(PJ_LOWER_IMPULSE, f(input, "lowerImpulse"));
        set(PJ_UPPER_IMPULSE, f(input, "upperImpulse"));
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        let perp = arr(g, "perpImpulse");
        check_scalar(&joints, PJ_PERP_IMPULSE, perp[0], name, &format!("{phase} perpImpulse.x"));
        check_scalar(&joints, PJ_PERP_IMPULSE + 1, perp[1], name, &format!("{phase} perpImpulse.y"));
        check_vec3(&joints, PJ_ANGULAR_IMPULSE, &arr(g, "angularImpulse"), name, &format!("{phase} angularImpulse"));
        check_scalar(&joints, PJ_SPRING_IMPULSE, f(g, "springImpulse"), name, &format!("{phase} springImpulse"));
        check_scalar(&joints, PJ_MOTOR_IMPULSE, f(g, "motorImpulse"), name, &format!("{phase} motorImpulse"));
        check_scalar(&joints, PJ_LOWER_IMPULSE, f(g, "lowerImpulse"), name, &format!("{phase} lowerImpulse"));
        check_scalar(&joints, PJ_UPPER_IMPULSE, f(g, "upperImpulse"), name, &format!("{phase} upperImpulse"));
    }
}

#[test]
fn prismatic_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["prismatic"].as_array().expect("prismatic array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_prismatic(sc);
    }
}

// --- wheel ------------------------------------------------------------------------------------

fn run_wheel(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_WHEEL);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(WHJ_MAX_SPIN_TORQUE, f(input, "maxSpinTorque"));
        set(WHJ_SPIN_SPEED, f(input, "spinSpeed"));
        set(WHJ_LOWER_SUSPENSION_LIMIT, f(input, "lowerSuspensionLimit"));
        set(WHJ_UPPER_SUSPENSION_LIMIT, f(input, "upperSuspensionLimit"));
        set(WHJ_SUSPENSION_HERTZ, f(input, "suspensionHertz"));
        set(WHJ_SUSPENSION_DAMPING_RATIO, f(input, "suspensionDampingRatio"));
        set(WHJ_LOWER_STEERING_LIMIT, f(input, "lowerSteeringLimit"));
        set(WHJ_UPPER_STEERING_LIMIT, f(input, "upperSteeringLimit"));
        set(WHJ_TARGET_STEERING_ANGLE, f(input, "targetSteeringAngle"));
        set(WHJ_MAX_STEERING_TORQUE, f(input, "maxSteeringTorque"));
        set(WHJ_STEERING_HERTZ, f(input, "steeringHertz"));
        set(WHJ_STEERING_DAMPING_RATIO, f(input, "steeringDampingRatio"));
        let enable = (if input["enableSpinMotor"].as_i64().unwrap() != 0 { WHJ_ENABLE_SPIN_MOTOR } else { 0 })
            | (if input["enableSuspensionSpring"].as_i64().unwrap() != 0 { WHJ_ENABLE_SUSPENSION_SPRING } else { 0 })
            | (if input["enableSuspensionLimit"].as_i64().unwrap() != 0 { WHJ_ENABLE_SUSPENSION_LIMIT } else { 0 })
            | (if input["enableSteering"].as_i64().unwrap() != 0 { WHJ_ENABLE_STEERING } else { 0 })
            | (if input["enableSteeringLimit"].as_i64().unwrap() != 0 { WHJ_ENABLE_STEERING_LIMIT } else { 0 });
        set(WHJ_ENABLE, f32::from_bits(enable));
        for (i, x) in arr(input, "linearImpulse").iter().enumerate() {
            set(WHJ_LINEAR_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "angularImpulse").iter().enumerate() {
            set(WHJ_ANGULAR_IMPULSE + i, *x);
        }
        set(WHJ_SPIN_IMPULSE, f(input, "spinImpulse"));
        set(WHJ_SUSPENSION_SPRING_IMPULSE, f(input, "suspensionSpringImpulse"));
        set(WHJ_LOWER_SUSPENSION_IMPULSE, f(input, "lowerSuspensionImpulse"));
        set(WHJ_UPPER_SUSPENSION_IMPULSE, f(input, "upperSuspensionImpulse"));
        set(WHJ_STEERING_SPRING_IMPULSE, f(input, "steeringSpringImpulse"));
        set(WHJ_LOWER_STEERING_IMPULSE, f(input, "lowerSteeringImpulse"));
        set(WHJ_UPPER_STEERING_IMPULSE, f(input, "upperSteeringImpulse"));
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        let lin = arr(g, "linearImpulse");
        check_scalar(&joints, WHJ_LINEAR_IMPULSE, lin[0], name, &format!("{phase} linearImpulse.x"));
        check_scalar(&joints, WHJ_LINEAR_IMPULSE + 1, lin[1], name, &format!("{phase} linearImpulse.y"));
        let ang = arr(g, "angularImpulse");
        check_scalar(&joints, WHJ_ANGULAR_IMPULSE, ang[0], name, &format!("{phase} angularImpulse.x"));
        check_scalar(&joints, WHJ_ANGULAR_IMPULSE + 1, ang[1], name, &format!("{phase} angularImpulse.y"));
        check_scalar(&joints, WHJ_SPIN_IMPULSE, f(g, "spinImpulse"), name, &format!("{phase} spinImpulse"));
        check_scalar(&joints, WHJ_SUSPENSION_SPRING_IMPULSE, f(g, "suspensionSpringImpulse"), name, &format!("{phase} suspensionSpringImpulse"));
        check_scalar(&joints, WHJ_LOWER_SUSPENSION_IMPULSE, f(g, "lowerSuspensionImpulse"), name, &format!("{phase} lowerSuspensionImpulse"));
        check_scalar(&joints, WHJ_UPPER_SUSPENSION_IMPULSE, f(g, "upperSuspensionImpulse"), name, &format!("{phase} upperSuspensionImpulse"));
        check_scalar(&joints, WHJ_STEERING_SPRING_IMPULSE, f(g, "steeringSpringImpulse"), name, &format!("{phase} steeringSpringImpulse"));
        check_scalar(&joints, WHJ_LOWER_STEERING_IMPULSE, f(g, "lowerSteeringImpulse"), name, &format!("{phase} lowerSteeringImpulse"));
        check_scalar(&joints, WHJ_UPPER_STEERING_IMPULSE, f(g, "upperSteeringImpulse"), name, &format!("{phase} upperSteeringImpulse"));
    }
}

#[test]
fn wheel_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["wheel"].as_array().expect("wheel array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_wheel(sc);
    }
}

// --- motor ------------------------------------------------------------------------------------

fn run_motor(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_MOTOR);
        let set = |field: usize, val: f32| jc.set(field, val);
        for (i, x) in arr(input, "linearVelocity").iter().enumerate() {
            set(MJ_LINEAR_VELOCITY + i, *x);
        }
        for (i, x) in arr(input, "angularVelocity").iter().enumerate() {
            set(MJ_ANGULAR_VELOCITY + i, *x);
        }
        set(MJ_MAX_VELOCITY_FORCE, f(input, "maxVelocityForce"));
        set(MJ_MAX_VELOCITY_TORQUE, f(input, "maxVelocityTorque"));
        set(MJ_LINEAR_HERTZ, f(input, "linearHertz"));
        set(MJ_LINEAR_DAMPING_RATIO, f(input, "linearDampingRatio"));
        set(MJ_ANGULAR_HERTZ, f(input, "angularHertz"));
        set(MJ_ANGULAR_DAMPING_RATIO, f(input, "angularDampingRatio"));
        set(MJ_MAX_SPRING_FORCE, f(input, "maxSpringForce"));
        set(MJ_MAX_SPRING_TORQUE, f(input, "maxSpringTorque"));
        for (i, x) in arr(input, "linearVelocityImpulse").iter().enumerate() {
            set(MJ_LINEAR_VELOCITY_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "angularVelocityImpulse").iter().enumerate() {
            set(MJ_ANGULAR_VELOCITY_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "linearSpringImpulse").iter().enumerate() {
            set(MJ_LINEAR_SPRING_IMPULSE + i, *x);
        }
        for (i, x) in arr(input, "angularSpringImpulse").iter().enumerate() {
            set(MJ_ANGULAR_SPRING_IMPULSE + i, *x);
        }
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        check_vec3(&joints, MJ_LINEAR_VELOCITY_IMPULSE, &arr(g, "linearVelocityImpulse"), name, &format!("{phase} linearVelocityImpulse"));
        check_vec3(&joints, MJ_ANGULAR_VELOCITY_IMPULSE, &arr(g, "angularVelocityImpulse"), name, &format!("{phase} angularVelocityImpulse"));
        check_vec3(&joints, MJ_LINEAR_SPRING_IMPULSE, &arr(g, "linearSpringImpulse"), name, &format!("{phase} linearSpringImpulse"));
        check_vec3(&joints, MJ_ANGULAR_SPRING_IMPULSE, &arr(g, "angularSpringImpulse"), name, &format!("{phase} angularSpringImpulse"));
    }
}

#[test]
fn motor_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["motor"].as_array().expect("motor array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_motor(sc);
    }
}

// --- parallel ---------------------------------------------------------------------------------

fn run_parallel(sc: &Value) {
    let name = sc["name"].as_str().unwrap();
    let input = &sc["input"];
    let b_static = input["bStatic"].as_i64().unwrap() != 0;
    let h = f(input, "h");
    let inv_h = f(input, "invH");
    let warm = input["enableWarmStarting"].as_i64().unwrap() != 0;

    let mut joints = vec![0.0f32; JOINT_STRIDE];
    {
        let jc = col(&mut joints);
        write_base(jc, input, TY_PARALLEL);
        let set = |field: usize, val: f32| jc.set(field, val);
        set(PLJ_HERTZ, f(input, "hertz"));
        set(PLJ_DAMPING_RATIO, f(input, "dampingRatio"));
        set(PLJ_MAX_TORQUE, f(input, "maxTorque"));
        for (i, x) in arr(input, "perpImpulse").iter().enumerate() {
            set(PLJ_PERP_IMPULSE + i, *x);
        }
    }
    let (mut state, mut flags) = build_state(input);

    {
        let jc = col(&mut joints);
        prepare(jc, 0, h, inv_h, warm);
    }
    {
        let jc = col(&mut joints);
        let sc2 = col(&mut state);
        let fc = col(&mut flags);
        warm_start(jc, 0, sc2, fc);
    }
    check_body_vels(&sc["warmStart"], &mut state, b_static, name, "warmStart");

    for (phase, use_bias) in [("solveBias", true), ("solveRelax", false)] {
        {
            let jc = col(&mut joints);
            let sc2 = col(&mut state);
            let fc = col(&mut flags);
            solve(jc, 0, sc2, fc, use_bias, h, inv_h);
        }
        let g = &sc[phase];
        check_body_vels(g, &mut state, b_static, name, phase);
        let perp = arr(g, "perpImpulse");
        check_scalar(&joints, PLJ_PERP_IMPULSE, perp[0], name, &format!("{phase} perpImpulse.x"));
        check_scalar(&joints, PLJ_PERP_IMPULSE + 1, perp[1], name, &format!("{phase} perpImpulse.y"));
    }
}

#[test]
fn parallel_joint_matches_reference() {
    let gold: Value = serde_json::from_str(GOLD).expect("parse joint.gold.json");
    let scenarios = gold["parallel"].as_array().expect("parallel array");
    assert!(!scenarios.is_empty());
    for sc in scenarios {
        run_parallel(sc);
    }
}
